### ISSUE TITLE
Bug: somehow the bottom bar on the Nexus 5 is wrong

### ISSUE THREAD

**Issue by commjoen** [journeyapps/zxing-android-embedded#101]
It seems that the library changes the rootview in such a way that some of the bottom screen is wrongly adjusted. 
![device-2015-11-17-172723](https://cloud.githubusercontent.com/assets/1457214/11217491/d1e53670-8d50-11e5-8a1d-365c59d50743.png)

This is only on Nexus 5 devices.

**Comment by commjoen** [comment]
This is how it looks on Android emulator:


![screen shot 2015-11-17 at 17 18 22](https://cloud.githubusercontent.com/assets/1457214/11217511/f4d54e40-8d50-11e5-91ba-fe5628f0359a.png)

**Comment by rkistner** [comment]
Do you have a sample project where this happens (does it happen in the sample project)?

This may help for the issue: https://github.com/journeyapps/zxing-android-embedded/issues/90#issuecomment-151067426

**Comment by commjoen** [comment]
It happens on the sample project as well using Android M. However, on your branch surface-texture it does not happen...

**Comment by rkistner** [comment]
There is better preview scaling logic in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0), and TextureView is now the default.

New instructions here:

[EMBEDDING.md](https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md)
