### ISSUE TITLE
preview in the continuesCaptureActivity is not full screen

### ISSUE THREAD

**Issue by maxim-pandra** [journeyapps/zxing-android-embedded#104]
Nexus7 (2012) front camera. On activity launch everything is allright. But when application is resumed after minimizing, this happens). Any ideas why? i'm novice in android (CompaundBarcodeView pause() and resume() are called in coresponding methods)
![device-2015-11-23-124724](https://cloud.githubusercontent.com/assets/9080415/11333782/5e2cc096-91e1-11e5-9648-7abdc28e9224.png)

**Comment by maxim-pandra** [comment]
when i press the square, preview briefly removes its black border, but when i come back everything is the same

**Comment by Sebosam** [comment]
I agree nexus 7(2013) & nexus 5(probably all clean android with soft navigation buttons). I think it's something with DisplayConf. Any action set display in correct way(e.g. recentapps button, u see for the moment proper view, or orientationchange). I will test it on more devices end update answer

**Comment by rkistner** [comment]
Please try this and check if it solves the issue:
https://github.com/journeyapps/zxing-android-embedded/issues/90#issuecomment-151067426

**Comment by Sebosam** [comment]
When I changed dx and dy to 0 in scalePreview function in DisplayConf the surface is correctly added. Something wrong in calculating dx and dy because set x to minus values

**Comment by rkistner** [comment]
Can you post the adb logs for the Application (Android Monitor in Android Studio)? I'd like to see these lines specifically:

        Log.i(TAG, "Viewfinder size: " + desired);
        Log.i(TAG, "Preview in order of preference: " + sizes);
        Log.i(TAG, "Preview: " + previewSize + "; Scaled: " + scaledPreview + "; Want: " + viewfinderSize);

**Comment by Sebosam** [comment]
NEXUS 7 on ViewCreated

11-23 12:12:41.147 18022-18144/com.inewi.terminal I/DisplayConfiguration: Viewfinder size: 1920x1200
11-23 12:12:41.148 18022-18144/com.inewi.terminal I/DisplayConfiguration: Preview in order of preference: [1280x768, 1280x720, 1024x768, 800x600, 800x480, 720x480, 640x480, 352x288, 320x240, 176x144]
11-23 12:12:41.152 18022-18022/com.inewi.terminal I/DisplayConfiguration: Preview: 768x1280; Scaled: 1536x2560; Want: 1200x1920

OnResume
11-23 12:13:21.601 18022-19760/com.inewi.terminal I/DisplayConfiguration: Viewfinder size: 1824x1200
11-23 12:13:21.601 18022-19760/com.inewi.terminal I/DisplayConfiguration: Preview in order of preference: [1280x768, 1280x720, 1024x768, 800x600, 800x480, 720x480, 640x480, 352x288, 320x240, 176x144]
11-23 12:13:21.604 18022-18022/com.inewi.terminal I/DisplayConfiguration: Preview: 768x1280; Scaled: 1536x2560; Want: 1200x1824

I will send u nexus 5 too if u want

**Comment by Sebosam** [comment]
Nexus 5 onViewCreated

11-23 12:16:31.435 7777-8027/ I/DisplayConfiguration: Viewfinder size: 1920x1080
11-23 12:16:31.435 7777-8027/ I/DisplayConfiguration: Preview in order of preference: [1280x960, 1280x768, 1280x720, 1024x768, 800x600, 800x480, 720x480, 640x480, 352x288, 320x240, 176x144]
11-23 12:16:31.439 7777-7777/ I/DisplayConfiguration: Preview: 960x1280; Scaled: 1440x1920; Want: 1080x1920
onResume:

11-23 12:23:12.013 16391-17790/ I/DisplayConfiguration: Viewfinder size: 1776x1080
11-23 12:23:12.013 16391-17790/ I/DisplayConfiguration: Preview in order of preference: [1280x960, 1280x768, 1280x720, 1024x768, 800x600, 800x480, 720x480, 640x480, 352x288, 320x240, 176x144]
11-23 12:23:26.762 16391-16391/ I/DisplayConfiguration: Preview: 960x1280; Scaled: 1440x1920; Want: 1080x1776

**Comment by rkistner** [comment]
According to those logs, the scaled preview should be larger than the screen/viewfinder, so I'm not sure why you'd see that black border.

It is however strange that the viewfinder size is different between the `onViewCreated` and `onResume`. This is essentially the size of the BarcodeView / CompoundBarcodeView. Any idea why that would happen?

**Comment by Sebosam** [comment]
I think its dx and dy problem because screen is correct but with minus x for example. I think its because fullscreen app oncreate, but when u came from recent app button(onresume). Bottom nav buttons is still shows and change real resolution. Before they hide.

**Comment by maxim-pandra** [comment]
@Sebosam thanks for workaround, it works)!

**Comment by Sebosam** [comment]
@maxim-pandra its hotfix maybe author find better way. Stay tune:)

**Comment by rkistner** [comment]
I haven't been able to reproduce this on my phone (don't have a Nexus device), so it's difficult to debug.

@Sebosam In `DisplayConfiguration#scalePreview`, `dx` and `dy` are supposed to be positive, giving the Rect negative coordinates (it uses `-dx, -dy`).

**Comment by rkistner** [comment]
It is now supported in 3.1.0 to use this option on the BarcodeView / CompoundBarcodeView:

```
app:zxing_use_texture_view="true"
```

That should solve this issue.
