### ISSUE TITLE
Continuous Scan 

### ISSUE THREAD

**Issue by mmelchio** [journeyapps/zxing-android-embedded#106]
Hi all,

The library is working very well but I got one problem.
If the user scans a certain QR-Code the barcodeResult-method starts a new activity. But if the QR-Code does not contain the right informations, the app should keep scanning.
If I scan a random QR-Code and then move on to a QR-Code that contains the Information the App needs, nothing happens. So the app somehow stopps scanning. Even when I use barcodeView.decodeContinuous(callback) in my onCreate-method.
What would be a good approach for that?
Thanks.

**Comment by mmelchio** [comment]
I can't figure it out, maybe I'm too stupid for that

**Comment by rkistner** [comment]
Sorry for the late reply.

`decodeContinuous` should continue scanning, as in this example: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

Alternatively, if the barcode is not what you want, just call `decodeSingle(callback)` again.

**Comment by mmelchio** [comment]
Thanks, I just mady a silly mistake and got confused...

**Comment by destro1108** [comment]
> Sorry for the late reply.
> 
> `decodeContinuous` should continue scanning, as in this example: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java
> 
> Alternatively, if the barcode is not what you want, just call `decodeSingle(callback)` again.

Hey man. Is there a similar way to continuously scan QR Codes as well?

**Comment by rkistner** [comment]
> Hey man. Is there a similar way to continuously scan QR Codes as well?

The linked example does exactly that.
