### ISSUE TITLE
Issue When Adding CompoundBarcodeView At Runtime

### ISSUE THREAD

**Issue by EricMaibach** [journeyapps/zxing-android-embedded#109]
I am trying to add the CompoundBarcodeView to an activity at runtime.  It successfully adds it to the activity, and you see the control on the screen, however it does not show the camera view, it just shows black. 

Here is my code for adding the CompundBarcodeView to the activity:

```java
LinearLayout linlay = (LinearLayout)findViewById(R.id.mainroot);
barcodeView = new CompoundBarcodeView(this);
barcodeView.setId(20);
LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, 0, 4.0f);
barcodeView.setLayoutParams(params);
linlay.addView(barcodeView, 0);
barcodeView = (CompoundBarcodeView) findViewById(20);
barcodeView.decodeContinuous(callback);
```

Should this work, or is this not supported?

**Comment by rkistner** [comment]
It should work, but you have to call `barcodeView.resume()` after adding it (and from your Activity's `onResume`), and `barcodeView.pause()` when removing it and on your Activity's `onPause`.

**Comment by EricMaibach** [comment]
Thank you
