### ISSUE TITLE
Error:Execution failed for task: app:transformClassesWithDexForDebug

### ISSUE THREAD

**Issue by konopkoman** [journeyapps/zxing-android-embedded#110]
Got this using your lib when trying run my app for debug.

>Error:Execution failed for task ':app:transformClassesWithDexForDebug'. com.android.build.transform.api.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 2

**Comment by swordray** [comment]
+1

**Comment by rkistner** [comment]
Check if one of the answers here help:

http://stackoverflow.com/questions/32807587/com-android-build-transform-api-transformexception

**Comment by rkistner** [comment]
Please re-open the issue if the above answers do not help, and you are sure it's only an issue with this library.

**Comment by mrprogramator** [comment]
It's so sad that you can't create your first app in android studio and compile it without changing stupid things. Why should you change an app if it is in blank?? It should be configured as default. 

I got this error:

Error:Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 1

And in all forums I've read, they say to add this:

defaultConfig {
    multiDexEnabled true
}

But it doesn't work !!! I've clean it, rebuild it and always appears the same error :(

**Comment by FanyCastro** [comment]
Hello,
Can anyone help? I have exactly the same problem when I try to run an application from Android studio in a Mac. I have also done:

    dexOptions {
        preDexLibraries true
        maxProcessCount 8
        javaMaxHeapSize "4g"
        // Instead of setting the heap size for the DEX process, increase Gradle's
        // heap size to enable dex-in-process. 
    }

    defaultConfig {
        multiDexEnabled true
    }

    @Override
    public void onCreate() {
        super.onCreate();
        MultiDex.install(this);
  }

**Comment by rkistner** [comment]
@FanyCastro The issue is most likely not directly related to this project - StackOverflow will be the best place to ask for help.

**Comment by tb56zily** [comment]
If java 8 or above is used then the problem is the libraries we use are incompatible with java 8. So to solve this add these two lines to build.gradle of your app and all sub modules if any. (Android studio clearly show how to do this in error message) 

targetCompatibility = '1.7' 
sourceCompatibility = '1.7'
