### ISSUE TITLE
Camera zooms in after scan in landscape and rotate to portrait

### ISSUE THREAD

**Issue by Paschmid** [journeyapps/zxing-android-embedded#111]
Hi,

I use this library to decode continously barcodes in any orientation. If I rotate without scanning, everything works well. But as soon as I scan a barcode in landscape and then rotate to portrait, the camera is zoomed in. After rotating again to landscape and back to portrait (without scanning barcode) it is back to normal again. This issues arises only in this order (scan in portrait and then rotate the screen works just fine).

**Comment by rkistner** [comment]
This is probably related to the size of the BarcodeView being different when in those cases (perhaps related to the built-in buttons showing or not), which affects the preview size calculation. I'll see if I can find a solution at some point.

**Comment by rkistner** [comment]
There is better preview scaling logic in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0), which should solve this issue.

Please re-open this issue if you still have trouble with this.
