### ISSUE TITLE
Android 6.0: Camera showing crippled preview

### ISSUE THREAD

**Issue by soenkegissel** [journeyapps/zxing-android-embedded#113]
When deploying the app on new Android 6.0 I first followed issue #89 to fix permission problems. Now the camera opens with following: 
![2016_01_03_09 08 33](https://cloud.githubusercontent.com/assets/13346316/12077891/dd1aba88-b1f9-11e5-8911-962ff8309eab.png)

Thanks in advance.

**Comment by rkistner** [comment]
As mentioned in #12, this seems to be related to a specific Cyanogenmod build.

I've also seen this happen in some other cases. Usually it only affects a specific preview size, and the solution (workaround) is to hardcode a different preview size for that device.
