### ISSUE TITLE
Toolbar is hidden for continuous scan

### ISSUE THREAD

**Issue by meierjan** [journeyapps/zxing-android-embedded#118]
Hey,

really thank you making integrate the QR-scanner that easy. I really appreciate.

I am using a `Activity` with `Fragments`. The parent `Activity` has a `Toolbar`. There is a `CompoundBarcodeView` in the `Fragment` to do continuous scanning and adding the result elements to a `ListView`. 
When you start the Fragment and not activate the `CompoundBarcodeView` the Toolbar is visible. Now when I activate the `CompoundBarcodeView` it magically covers the `Toolbar` (see screenshot). You can still click on the navigate up button even if it is not visible.

Any thoughts on that?

__Version?__
``` 
zxingAndroid  : 'com.journeyapps:zxing-android-embedded:3.1.0@aar',
zxingCore     : 'com.google.zxing:core:3.2.0',
```
__Which phone/tablet are you using, and which Android version does it run?__
* Samsung XCover 3; Android 5.1
* Genymotion: Google Nexus 4 API 22 

__Does the same happen on other devices or an emulator?__
Yes.

__Can you reproduce the error in the sample project included with the library? If not, can you provide your own sample project or sample code that produces this error?__
Will try to add this later.

![device-2016-01-12-124457](https://cloud.githubusercontent.com/assets/3726563/12262967/d84c3246-b92b-11e5-8d33-890b0acd6945.png)
![device-2016-01-12-124508](https://cloud.githubusercontent.com/assets/3726563/12262970/db90dad8-b92b-11e5-91b0-6c04de8bb8dd.png)

**Comment by rkistner** [comment]
Please try this workaround: https://github.com/journeyapps/zxing-android-embedded/issues/90#issuecomment-151067426 (released in 3.1.0).

**Comment by meierjan** [comment]
Thanks, this works fine.

**Comment by rkistner** [comment]
There is better preview scaling logic in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0), and TextureView is now the default.

New instructions here:

[EMBEDDING.md](https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md)
