### ISSUE TITLE
Is version 3 not use on android studio with compileSdkVersion 22 ?

### ISSUE THREAD

**Issue by vampire1514** [journeyapps/zxing-android-embedded#124]
Hello ,

I get a NoSuchMethodError when I use compileSdkVersion 22 set up in build.gradle.

The message is shown below :
java.lang.NoSuchMethodError: No static method \checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/scanner.card.weypro.com.zxingapptesing-2/base.apk)
                                                                                            at com.journeyapps.barcodescanner.CaptureManager.openCameraWithPermission(CaptureManager.java:234)

My IDE is Android Studio.

Can you help me? Thanks a lot.

**Comment by rkistner** [comment]
For version 3.1.0 of the library, you need version 23.x of the support library.

If you want to stick to version 22 of the SDK and support library, you can use 3.0.3 of this library.

**Comment by vampire1514** [comment]
Thanks.

I am tried. 

But I get a compile error : 
Error:(6) No resource identifier found for attribute 'zxing_framing_rect_width' in package 'scanner.card.weypro.com.zxingapptesing'

Error:(6) No resource identifier found for attribute 'zxing_framing_rect_height' in package 'scanner.card.weypro.com.zxingapptesing'

**Comment by rkistner** [comment]
That's an issue with the newer build tools, that was solved in v3.1.0. In that case you'd have to either downgrade the build-tools version (can't remember which version worked - you'll have to try and see), or upgrade compileSdkVersion and support library to version 23+.

**Comment by rkistner** [comment]
Updated readme to mention the build-tools and support lib requirements.

Please open the issue again if you still have issues with this.

**Comment by luvnish19** [comment]
Not working on Android Marshmallow, giving exception

java.lang.NoSuchMethodError: No static method checkSelfPermission(Landroid/content/Context;Ljava/lang/String;)I in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.example.luvnish.scannerdemo-1/base.apk)

Can you please fix or tell. Why this issue is occuring.
