### ISSUE TITLE
How to enable beep with CompoundBarcodeView ?

### ISSUE THREAD

**Issue by alexandre-lefranc-ezeeworld** [journeyapps/zxing-android-embedded#126]
Hi,

How to enable beep with CompoundBarcodeView ?

Thanks.

**Comment by rkistner** [comment]
BeepManager can be used directly for this. No docs on that - you'll have to check the source.

**Comment by rkistner** [comment]
You can see how BeepManager is used here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/CaptureManager.java#L77-L86
