### ISSUE TITLE
Your value for request permissions is wrong

### ISSUE THREAD

**Issue by carlosnavarrete** [journeyapps/zxing-android-embedded#127]
the value in the library for requesting permissions in Android 23 is wrong with the value 
private static final int CAMERA_PERMISSION_REQUEST = 89433;

it exceeds the values for any limit in Android for requestCodes it should be lower than 16bits or for request permissions lower than 8 bits
16 bits, meaning the range is from 0 to 65535.
8 bits, meaning the range is from 0 to 255.

**Comment by rkistner** [comment]
This has been fixed in #123, will be in the next release.

**Comment by rkistner** [comment]
Fixed in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0).
