### ISSUE TITLE
onSetTorchOn()

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#128]
I have a button, and onClick it first time i call setTorchOn() and and second time i call onTorchOff() (like a toggle button).
But the issue is sometimes onSetTorchOn() method is unable to ON the torch, for to ON, i have to tap again torch button, i think its library issue.

My test is like this....
_i call setTorchOn() 100 times and in which 10 times torch was unable to ON._
i call setTorchOn() 10 times and in which 2 times torch was unable to ON
i call setTorchOn() 50 times and in which 3 times torch was unable to ON

Can you see this into, thanks in advance :-)

**Comment by Priyavrat-1** [comment]
Hello,
I am facing the same issue. Quick help will be appreciated here.

Thanks :)

**Comment by rkistner** [comment]
Will look into this before the next release.

**Comment by rkistner** [comment]
@Bajranghudda1 
Are you only getting the issue after rotating the device (or another pause and resume), or also in between?

It seems like one current issue is that the TorchListener is not called when e.g. after rotating the device, so you may be calling e.g. `onTorchOff()` when it is already off. I'll look into improving that for version 3.3.0.

**Comment by Bajranghudda1** [comment]
@rkistner 

My screen orientation is only portrait, and there is no such case of rotating the device and i am sure that there is no resume and pause like case. 

Actually on each bar code before to scan i need to turn on (setTorchOn()) and when barcode detected (in callback), i make it off (setTorchOff()) and i do all the time for all items scan.

**Comment by anhadmathur** [comment]
Hi,
I am using CompoundBarcodeView and doing the same like @Bajranghudda1 is doing,
After look into this issue #128 I checked it in my app and I found this issue, sometimes it doesn't turn on.
I am calling setTorchOn() and setTorchOff() on a toggle button.
Plese look into this.

Thanks (: Peace V

**Comment by Bajranghudda1** [comment]
@rkistner 

For auto flash light you doing isAutoFlashLightEnabled(boolean), and for this you using light sensor and if darkness density is 45.0f  (will turn of flash) and 450.0f will turn off flash, i think it is worst if instantly light sensor has been covered by user's shadow.

I think this torch auto On/Off can be improved by using logic like android's Camera app does, i tested Camera app not using Light sensor for detecting darkness.

**Comment by Bajranghudda1** [comment]
Hello @rkistner ,
 I made some more test and found that this issues is device specific.
My test is below -
**
Moto G, Samsung Dues (GT-I8262), Samgung S4**

_I/CameraConfiguration﹕ Requesting flash mode value from among: [torch, on]
I/CameraConfiguration﹕ Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration﹕ Can set flash mode to: torch
I/CameraConfiguration﹕ Setting flash mode to torch
I/CameraConfiguration﹕ Requesting flash mode value from among: [off]
I/CameraConfiguration﹕ Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration﹕ Can set flash mode to: off
I/CameraConfiguration﹕ Setting flash mode to off_

**Samsung Note 4 **

_D/ViewRootImpl﹕ ViewPostImeInputStage ACTION_DOWN
I/CameraConfiguration﹕ Requesting flash mode value from among: [torch, on]
I/CameraConfiguration﹕ Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration﹕ Can set flash mode to: torch
I/CameraConfiguration﹕ Setting flash mode to torch
D/dalvikvm﹕ GC_FOR_ALLOC freed 3740K, 28% free 47553K/65364K, paused 22ms, total 25ms
D/ViewRootImpl﹕ ViewPostImeInputStage ACTION_DOWN
I/CameraConfiguration﹕ Requesting flash mode value from among: [off]
I/CameraConfiguration﹕ Supported flash mode values: [off, auto, on, torch]
I/CameraConfiguration﹕ Can set flash mode to: off
I/CameraConfiguration﹕ Setting flash mode to off_

**Comment by rkistner** [comment]
Closing as a device-specific issue.
