### ISSUE TITLE
CompoundBarcodeView's layout strange behaviour.

### ISSUE THREAD

**Issue by HectorFGarcia** [journeyapps/zxing-android-embedded#129]
This is how layout looks on Nexys 5 (6.0.1).

![1](https://cloud.githubusercontent.com/assets/12731574/12776458/67597e2c-ca56-11e5-9060-2bda98a5865d.png)

And this is how looks on a HoneyWell E70 (4.0.3).

![2](https://cloud.githubusercontent.com/assets/12731574/12776461/6caf1152-ca56-11e5-95b1-2f1fb58ff750.png)

Apparently it looks fine... but it doesn't. In the second case, the system can't capture on a screenshot how the screen really looks like. Here is a photo:

![3](https://cloud.githubusercontent.com/assets/12731574/12776464/71360d98-ca56-11e5-812d-1f1e34f5610d.jpg) 

As you see, the layout "overflows", is out of margins, and also overlays (the part that overflows) the menu when you deploy it. 

I don't know what is causing this behaviour but only happens with the HoneyWell E70. I don't know if this is a library bug, Android bug or GPU bug. Never happened to me before.

Do you know how to fix it?

**Comment by HectorFGarcia** [comment]
I've tried the library in a new project only with this, using the code from the samples... and the bug persists, so is a problem with the device, the Android version or the library. 

I don't have another 4.0.3 decive to test the Android version :(

**Comment by rkistner** [comment]
Please try this workaround: https://github.com/journeyapps/zxing-android-embedded/issues/90#issuecomment-151067426 (released in 3.1.0).

Will make that option the default in the next release.

**Comment by HectorFGarcia** [comment]
It works!!! You saved my day, thank you!!

You should add this info to the Readme until the next release, it drove me nuts.
