### ISSUE TITLE
Custom view not working well

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#131]
Hi, 
If i do make any changes in height my barcode view get strached in whole window, but i want to fit in middle my phone like 300x300. i can't do.

 **<com.journeyapps.barcodescanner.CompoundBarcodeView
                android:id="@+id/barcode_scanners"
                android:layout_width="wrap_content"
                android:layout_height="300dp"
                android:foregroundGravity="center"
                app:zxing_scanner_layout="@layout/custom_barcode_scanner"
                >
            </com.journeyapps.barcodescanner.CompoundBarcodeView>
**
Please help me

**Comment by rkistner** [comment]
There are some fixes for this in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0).

New instructions here:

https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md

**Comment by Bajranghudda1** [comment]
Hi "rkistner",

A very big thanks to look into this, i think its too quick reply.
Thank you :-)
