### ISSUE TITLE
How to get the scan result when using CaptureManager

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [journeyapps/zxing-android-embedded#138]
I'm using the version 3.2 of this library to scan QR codes.

I know when using `IntentIntegrator`, I can get the scan result via the `onActivityResult` method. But how can I get it when I'm using `CaptureManager` with a `CompoundBarcodeView`? I looked in the example project but I can't seem to figure it out.

**Comment by rkistner** [comment]
You can still use IntentIntegrator, and get the results in the same way. See my response on #139.
