### ISSUE TITLE
Is "touch to scan" possible??

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#140]
Because sometimes scanner doesn't make focus on bar code, so in this case user able to focus manually.

**Comment by rkistner** [comment]
This would be a nice feature to add to the library (pull requests welcome).

**Comment by Bajranghudda1** [comment]
@rkistner 

Is there any idea form i start, please could you suggest me something, i am a new developer.

**Comment by TheGratefulDev** [comment]
I don't know if this is a work around or not.
I use continuous Capture, and set a onClickListener for DecoratedBarcodeView 
`
     barcodeView = (DecoratedBarcodeView) findViewById(R.id.barcode_scanner);
     barcodeView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                triggerScan(v);
            }
        });


   public void triggerScan(View view) {
        barcodeView.decodeSingle(callback);
    }
`

**Comment by AnJake** [comment]
@TheGratefulDev 
Will callback come from where?

**Comment by TheGratefulDev** [comment]
@AnJake Sorry for the late reply

Coming from import com.journeyapps.barcodescanner.BarcodeCallback;

 private BarcodeCallback callback = new BarcodeCallback() {
        @Override
        public void barcodeResult(BarcodeResult result) {

        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {}

}
