### ISSUE TITLE
PDF_417

### ISSUE THREAD

**Issue by wrdhat** [journeyapps/zxing-android-embedded#142]
Hi, with your library, i can scan pdf417??

I have this.

List<String> oDesiredFormats = Arrays.asList("PDF417_MODE");

integrator.setDesiredBarcodeFormats(oDesiredFormats);

But, only recognized UPC_E.

**Comment by rkistner** [comment]
Any format supported by the [zxing](https://github.com/zxing/zxing/) library is supported.

The format should be specified as `"PDF_417"`. For a complete list, see:

https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/BarcodeFormat.java

Note that PDF417 scanning in ZXing is not great. It will work for small barcodes, but may struggle on larger ones. For better support for PDF417, http://pdf417.mobi/ (commercial library) has worked well for me in the past, but even then it may be difficult to scan large barcodes with a phone's camera.
