### ISSUE TITLE
How can i get bitmap image or data from scanned results

### ISSUE THREAD

**Issue by shankar667** [journeyapps/zxing-android-embedded#143]
Hi,
Firstly, thanks for your library, it was super.

The requirement from my personal app is get the captured image from scan results, but I'm not getting from version 3.0.1, i know you are implemented in version >= 3.1.0,but the latest versions need Android (23), due to some causes I'n not ready to go for Android 23 (6.0).

Is there any option to get the image or bitmap data from scanned results?

And also i tried from bytes `result.getByteArrayExtra("SCAN_RESULT_BYTES")`, but it won't work for me, please see the code which is used for create bitmap.

```
byte[] rawBytes = result.getByteArrayExtra("SCAN_RESULT_BYTES");
Bitmap bm = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888); 
// tried RGB_565 also
bm.copyPixelsFromBuffer(ByteBuffer.wrap(rawBytes));
```

Please suggest me, if there are alternative methods or code to get the image or image data.

**Comment by Bajranghudda1** [comment]
Hello @shankar667 ,

there is two methods you can try any one...
           result.getBitmap()
           result.getBitmapWithResultPoints(Color.YELLOW)

**Comment by shankar667** [comment]
Thanks for reply, The method you mentioned that `result.getBitmap() `or `result.getBitmapWithResultPoints(Color.YELLOW)` didn't exist from Intent results.
I'm following the code as below.

```
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {

    IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);

    result.getBitmap() // doesn't exist
    result.getBitmapWithResultPoints(Color.YELLOW) // doesn't exist
}
```

Can you please tell me where can i get?

**Comment by Bajranghudda1** [comment]
@shankar667 

Set your intent like this...

IntentIntegrator integrator = new IntentIntegrator(this);
integrator.setBarcodeImageEnabled(true);
//do u set it "integrator.setBarcodeImageEnabled(true);"
integrator.initiateScan();


And then in onActivityResult()

 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
       result.getBitmap() 
       result.getBitmapWithResultPoints(Color.YELLOW) 
        }

otherwise you may update your library with a new version.

**Comment by shankar667** [comment]
Thank you for quick reply, Actually I'm using the verion  3.0.1 and also metioned in first comment.
In this version the method `integrator.setBarcodeImageEnabled(true)` is not avialable.

But now i tried v3.0.3, the method `setBarcodeImageEnabled(true)` existed and works on below Android 23, which is required for me.

Thank you so much.

**Comment by rkistner** [comment]
Great, glad you got it working. Thanks for the help @Bajranghudda1.
