### ISSUE TITLE
"capture.onResume()" not able to start camera preview.

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#144]
Hi @rkistner 

If first time i allowed the camera permission, and in between if i deny the camera permission from "App info", and if again i will start scanner and again allow the permission then the camera preview does not start immediately only red strip blinking; for camera preview i have to start my activity again (and i'm not finishing my activity on positive button click because i have manual barcode entry option too). 
Means user want it immediately start the camera preview as soon permission allowed, and there is a possibility that user may deny the camera permission anytime.

```
      @Override
public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults)
{
    if(requestCode == cameraPermissionReqCode)
    {
        if(grantResults.length > 0 && grantResults[0] == 0)
        {
            capture.onResume();
        }
        else
        {
           displayFrameworkBugMessageAndExit();
        }
    }

}


private void displayFrameworkBugMessageAndExit()
{
    Utils.displayInfoDialog(this, getString(R.string.scanner_error_title), getString(R.string.scanner_error_message), new DialogOnDoneCallback()
    {
        @Override
        public void OnDone(Object onDone)
        {
        }
    }, true);
}
```

Please look into this..Thanks in advance.

**Comment by rkistner** [comment]
Which version of the library are you using?

**Comment by Bajranghudda1** [comment]
this latest one...

  compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
    compile 'com.google.zxing:core:3.2.1'
    compile 'com.android.support:appcompat-v7:23.1.0'

**Comment by rkistner** [comment]
Sounds similar to #132, or is it something completely different? Can you reproduce it in an emulator? I don't have a device with Android 6, so I haven't been able to reproduce that issue myself.

**Comment by Bajranghudda1** [comment]
Yes this is exactly the same case #132 , and have reproduced many times, please look into this, and this is because of if user deny the permission in between.

And it works fine if user allow/deny the permission very first time (first time installation) .

**Comment by cnworks** [comment]
I was able to work around by recreating the activity after requesting the permission.

**Comment by rkistner** [comment]
I am still not able to reproduce this with the sample app, on neither the emulator nor an Android 6 device.

Does this happen with the sample app?
Does it happen on a specific device, or multiple different devices?
Are there any errors or other details in the app logs?

**Comment by meierjan** [comment]
I have the same thing here.

**Comment by meierjan** [comment]
The only error I can see is:
> 09-23 12:03:23.751 4265-4265/wtf.meier.realmrxtestapp W/CameraPreview: initCamera called twice

**Comment by meierjan** [comment]
any news on this?

**Comment by Bajranghudda1** [comment]
@rkistner @meierjan @cnworks 
Hi there i got its solution, 

Its because, what we were doing  **capture.onResume();** we were calling on onResume() of activity and if permission is granted, its okay for library to initialize all camera instance but if the camera instance is not created (if user deny the permission) and we are trying to call   **capture.onPause();** on our activity's onPause(). So that time there is nothing to pause.
Thats it.
So make sure before to call capture.onPause() that, Is camera is already initialized or not.

**Comment by meierjan** [comment]
Ah too stupid error. I guess this can be closed...

**Comment by Bajranghudda1** [comment]
@rkistner @meierjan @cnworks 
Hi there i got its solution, 

Its because, what we were doing  **capture.onResume();** we were calling on onResume() of activity and if permission is granted, its okay for library to initialize all camera instance but if the camera instance is not created (if user deny the permission) and we are trying to call   **capture.onPause();** on our activity's onPause(). So that time there is nothing to pause.
Thats it.
So make sure before to call capture.onPause() that, Is camera is already initialized or not.
