### ISSUE TITLE
Which focus mode will be best suitable if device support all four (auto, continous, macro, infinity)?

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#145]
Some device support all four mode (auto, continous, macro, infinity), so what focus mode should I set for the better and fast scanning. And by default if no one mode support there is auto available.

Please suggest me.

**Comment by rkistner** [comment]
The default should work well for most cases. For specific scenarios, other options may work better. See the discussion in #450.
