### ISSUE TITLE
What is the downside to a low AUTO_FOCUS_INTERVAL_MS?

### ISSUE THREAD

**Issue by carn1x** [journeyapps/zxing-android-embedded#146]
Trying to scan QR codes in underlit environments means that I am regularly adjusting distance, and therefore I would assume fast auto focus reaction would be very important. However I notice that the default value of `2000L` seems to me to be quite high for an app that would want to maintain best focus as often/quickly as possible, therefore my assumption is that I don't know what I'm talking about and there are likely some trade-offs I'm simply not understanding.

Please could you shed any light on the ramifications of this setting? Thanks!

**Comment by rkistner** [comment]
This was ported from the [Barcode Scanner](github.com/zxing/zxing) app, and I don't personally know all the reasons behind this. One potential issue with a shorter interval is that some devices lose focus for a short while when triggering the focus. This means that if the interval is too short, the device would continuously be focussing, but never actually be in focus.

Some devices may have built-in support for continuous focussing as a camera option (vs "manually" focussing every 2 seconds), but I haven't tried that yet.
