### ISSUE TITLE
CaptureManager not get result

### ISSUE THREAD

**Issue by wrdhat** [journeyapps/zxing-android-embedded#147]
Hi, i need capture result for scan, but i can't use onActivityResult from IntentIntegrator with if i use CaptureManager.

I review your examples but i doesn't work.

I need use custom BarcodeScannerView, but in IntentIntegrator i can't set my layout and CaptureManager i can't get result from scanning.

**Comment by Bajranghudda1** [comment]
@wrdhat  try this way !!

CompoundBarcodeView  barcodeView
CaptureManager capture;

         Initialize it in onCreate()
{
barcodeView = (CompoundBarcodeView)findViewById(R.id.barcode_scanner);
capture = new CaptureManager(this, barcodeView);
decodeContinuous(callback);
}

 and your callback (where you suppose to get result) goes here...
        
 private BarcodeCallback callback = new BarcodeCallback()
    {
        @Override
        public void barcodeResult(BarcodeResult result)
        {
                 if (result.getText() != null)
                {
                        beepManager.playBeepSoundAndVibrate();
                       //result.getBitmap()
                      //result.getBitmap......
               }     
     }
        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints)
        {
        }
    };


@Override
    protected void onResume() {
        super.onResume();
        capture.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        capture.onPause();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        capture.onDestroy();
    }

**Comment by wrdhat** [comment]
Thanks
I try and i'll tell you.

**Comment by wrdhat** [comment]
@Bajranghudda1 Thanks. This worked for me.

**Comment by rkistner** [comment]
Thanks @Bajranghudda1

**Comment by rose09091989** [comment]
I want add my custom scanner layout.Where have to add ? when i am adding the capture activty its showing block screen please suggest me
