### ISSUE TITLE
Problem in "autofocusing" when i set meteringMode to true.

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#148]
when i set this...
barcodeView.getBarcodeView().getCameraSettings().setMeteringEnabled(true);

Camera stop focusing at all.

**Comment by rkistner** [comment]
When metering is enabled, a fixed focus area is used:
https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/camera/CameraManager.java#L267-L273

This would explain the auto-focus not working anymore.

Personally I have no experience with the metering option, so I'm not sure if it's even useful at all.

**Comment by Bajranghudda1** [comment]
@rkistner 
Alright i will check it metering support and not supporting devices too.

**Comment by zsolt-racz** [comment]
Is there any way to customise the focus area? I would like to set it so it would exactly match the framing rectangle, but if I understand it correctly, it's hard-coded to a 400x400px square in the middle here: [CameraConfigurationUtils](https://github.com/journeyapps/zxing-android-embedded/blob/50e3acce091decc195f67e6079b86427ddc2ad60/zxing-android-embedded/src/com/google/zxing/client/android/camera/CameraConfigurationUtils.java#L178).

**Comment by rkistner** [comment]
See the discussion in #450

**Comment by russelg1** [comment]
Please take me off this mailing list

**Comment by rkistner** [comment]
@russelg1 This is not a mailing list. You can unwatch the repo if you do not want notifications.
