### ISSUE TITLE
Couldn't import IntentIntegrator and IntentResult

### ISSUE THREAD

**Issue by xkawi** [journeyapps/zxing-android-embedded#151]
Has anyone encounter this issue? or what am I doing wrong here? I am using Android Studio 1.5.1

After I sync the gradle file, and try to import ` com.google.zxing.integration.android.IntentResult` and `com.google.zxing.integration.android.IntentIntegrator` it stated that `cannot resolve symbol 'integration'` though it has the core library installed properly.

Do I miss something here? Appreciate any help. thanks.

Here is my build.gradle:

    buildscript {
        repositories {
            jcenter()
            maven { url 'https://maven.fabric.io/public' }
            maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
        }

        dependencies {
            classpath 'io.fabric.tools:gradle:1.+'
        }
    }

    apply plugin: 'com.android.application'
    apply plugin: 'io.fabric'

    android {
        compileSdkVersion 23
        buildToolsVersion '23.0.2'
        useLibrary 'org.apache.http.legacy'
        buildTypes {
            debug {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                debuggable true
                zipAlignEnabled false
                versionNameSuffix "-WIP"
            }
            internalRelease {
                minifyEnabled true
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                debuggable false
                zipAlignEnabled true
                versionNameSuffix "-UAT"
            }
            release {
                minifyEnabled true
                proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                debuggable false
                zipAlignEnabled true
            }
        }
    }

    repositories {
        maven { url "http://dl.bintray.com/populov/maven" }
        mavenCentral()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" } // Font in XML
        maven { url 'https://dl.bintray.com/intercom/intercom-maven' }
    }
    
    dependencies {
        testCompile 'junit:junit:4.12'
        testCompile 'org.mockito:mockito-core:1.10.19'
        androidTestCompile ('com.android.support.test:runner:0.4.1') {
            exclude module: 'support-annotations'
        }
        androidTestCompile ('com.android.support.test:rules:0.4.1') {
            exclude module: 'support-annotations'
        }

        compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
        compile 'com.google.zxing:core:3.2.1'

        compile project(':adjust')
        compile project(':cannon')
        compile project(':zoomingphotoview')
        compile project(':country-picker')
        compile 'com.android.support:support-v4:23.+@aar'
        compile 'com.android.support:support-v13:23.+@aar'
        compile 'com.android.support:appcompat-v7:23.+@aar'
        compile 'com.android.support:design:23.+@aar'
        compile 'com.android.support:multidex:1.0.1@aar'
        compile 'com.android.support:recyclerview-v7:23.+@aar'
        compile 'com.android.support:gridlayout-v7:23.+@aar'
        compile 'com.android.support:cardview-v7:23.+@aar'
        compile 'com.google.android.gms:play-services-analytics:8.4.0@aar'
        compile 'com.google.android.gms:play-services-gcm:8.4.0'
        compile 'com.google.android.gms:play-services-location:8.4.0@aar'
        compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
            transitive = true;
        }
        compile 'com.facebook.android:facebook-android-sdk:4.8.1@aar'
        compile 'uk.co.chrisjenx:calligraphy:2.1.0@aar'
        compile 'com.parse.bolts:bolts-android:1.+'
        compile files('libs/Parse-1.11.0.jar')
        compile 'io.branch.sdk.android:library:1.10.+@aar'
        compile 'com.googlecode.libphonenumber:libphonenumber:7.2.1'
        compile 'com.timehop.stickyheadersrecyclerview:library:0.4.2@aar'
        compile 'com.viewpagerindicator:library:2.4.1@aar'
        compile('io.intercom.android:intercom-sdk:1.+@aar') {
            transitive = true
        }
        compile 'com.cocosw:bottomsheet:1.+@aar'
        compile 'com.viewpagerindicator:library:2.4.1@aar'
    }
    apply plugin: 'com.google.gms.google-services'

**Comment by xkawi** [comment]
closing this as it auto-magically resolved when I manually build the gradle. if anyone encounter this, try clean build and re-build again. If not, try manually build the gradle. thanks.

**Comment by sraghudatta94** [comment]
Hi xkawi, Same problem for me here. I tried clean and build that did not help. I even tried running "gradlew tasks" command in terminal in android studio. Can u please help me how to get out of this issue. Thanks in advance!!

![image](https://user-images.githubusercontent.com/23648455/28993744-9dc0dd3a-79db-11e7-8f00-885ad0b5324b.png)

**Comment by Abhisheksingh12345** [comment]
hii i am facing same issue 
if you have solution then please tell..
