### ISSUE TITLE
Return empty data after successful scanning in galaxy note3 neo and htc device

### ISSUE THREAD

**Issue by anshadn** [journeyapps/zxing-android-embedded#153]
I have uses following code to start the scanning process

`IntentIntegrator integrator = IntentIntegrator.forFragment(this);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
        integrator.setPrompt("Scan a QR Code");
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.setBeepEnabled(true);
       // integrator.setBarcodeImageEnabled(true);
        integrator.initiateScan();`

But i get a null response after parsing this line
`IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data)`

Is this issue related to lauchconfiguration in android manifest?
`<activity
            android:name="com.deal.sgidubai.activities.ContainerActivity"
            android:label="@string/app_name"
            android:launchMode="singleInstance"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan" />`

Thank you for your feedback in advance.

**Comment by rkistner** [comment]
What is `requestCode`, `resultCode` and `data` in that case?
