### ISSUE TITLE
getting resut code from CaptureActivity

### ISSUE THREAD

**Issue by Dhker** [journeyapps/zxing-android-embedded#154]
Hi, How do i excatly get the result scanned code from CaptureActivity ? is there a method or a static field, or via the onActivityResult ?

**Comment by Hitong** [comment]
Your problem seems like #147 , look into this; hope this will work for you.

**Comment by rkistner** [comment]
When using `IntentIntegrator`, you get the results back via `onActivityResult`:

```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
    if(result != null) {
        if(result.getContents() == null) {
            Toast.makeText(this, "Cancelled", Toast.LENGTH_LONG).show();
        } else {
            Toast.makeText(this, "Scanned: " + result.getContents(), Toast.LENGTH_LONG).show();
        }
    } else {
        super.onActivityResult(requestCode, resultCode, data);
    }
}
```

See the [Sample](https://github.com/journeyapps/zxing-android-embedded/blob/v3.2.0/sample/src/main/java/example/zxing/MainActivity.java) for more details.
