### ISSUE TITLE
Scan barcode become very small (after v3.1.0 update, have picture and ccde)

### ISSUE THREAD

**Issue by wingsum93** [journeyapps/zxing-android-embedded#157]
after i upgrade the library from libary 3.0.3@arr to 3.2

the problem raise when i use the below code in a lenovo pad 
[code base](https://gist.github.com/anonymous/44a1bdf2adbf559c66ff80941a10452c)

![device-2016-04-21-140926](https://cloud.githubusercontent.com/assets/13871554/14699529/1a56887e-07cb-11e6-8da9-f33a08046472.png)

the problem is that i can use the scan function as the view do not inflate correctly.

**Comment by rkistner** [comment]
There are a few different scaling options you can try, details here: https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md#notes-on-scaling
