### ISSUE TITLE
How can I gain access to a camera of the camera manager to set an android.hardware.camera.PreviewCallback to it?

### ISSUE THREAD

**Issue by DaleJulian** [journeyapps/zxing-android-embedded#158]
I need to take a picture of the whole image and not the cropped version of BarcodeResult.getBitmap(). The only way I see is too attach a PreviewCallback on a camera so I can use that to do camera.takePicture(previewCallback) but all of the camera instances in the CameraManager class is private. How do I do this? Thanks in advance

**Comment by rkistner** [comment]
I'm busy with a refactor to expose more internals like the Camera instance, but it may take a while before it's ready for release.

**Comment by DaleJulian** [comment]
Can you let me know once it's done? Thank you, and very nice plugin!

**Comment by rkistner** [comment]
`BarcodeResult#getBitmap()` now returns the entire image (instead of the cropped version) in v4.0.2.
