### ISSUE TITLE
Should work for Kindle Fire HD 6 ?

### ISSUE THREAD

**Issue by Rockvole** [journeyapps/zxing-android-embedded#159]
Nice work on this library contributors.

I have the sample examples working fine on my Nexus 5.
When I also install it on my Kindle Fire HD 6 it never seems to find any barcodes.

I tried the Barcode Scanner app by zxing team on my Kindle and it works well.

**Comment by rkistner** [comment]
I'm not aware of any reason it shouldn't work, but I don't have a Kindle Fire device to test it myself. In general, if the barcode preview works, the scanning should also work.

Are you seeing any errors in the adb logs?

**Comment by rkistner** [comment]
Need more info to debug.
