### ISSUE TITLE
Keep focus on continuous scanning

### ISSUE THREAD

**Issue by yelnar** [journeyapps/zxing-android-embedded#160]
Hi guys.

I am using your Continuous scanner sample app and I have following problem. Every time when qr code is being scanned camera auto focuses. I am wondering why it happens. I want it to scan very fast without auto focusing after each iteration. So my question is how can I achieve that?

Thanks.

**Comment by Bajranghudda1** [comment]
Hi @yelnar 
Your question seems confusing for me, do you want to disable auto focusing??

**Comment by yelnar** [comment]
Hello @Bajranghudda1 
Now I get it. The problem is that if when use this sample application (Continuous Scan), sometimes when the QR code is scanned the camera tries to refocus. For example, the qr code is scanned four times in a row very fast, then camera refocuses and again three-four times fast scanning and so on. So my question is that how can I avoid this refocus action.

P.S. I do not move the camera while it is scanning, so actually there is no reason to change the focus.

**Comment by Bajranghudda1** [comment]
Hello @yelnar 
I got it now, Ok lets see what you can do, make a flag variable (isThisDialogWindow = false) and if you successfully read bar code make it true, thats all.

      private final BarcodeCallback callback = new BarcodeCallback()
    {
        @Override
        public void barcodeResult(BarcodeResult result)
        {
            if (!isThisDialogWindow)
            {
                if (result.getText() != "" || result.getText() != null)
                {
                   beepManager.playBeepSoundAndVibrate();
                    staffId = result.getText();
                    Log.d(LOG," Scanned_staffId- "+ staffId);
                    isThidDialogWindow = true;
                  }
            }
            //Added preview of scanned barcode
            /*ImageView imageView = (ImageView) findViewById(R.id.barcodePreview);
            imageView.setImageBitmap(result.getBitmapWithResultPoints(Color.YELLOW));*/
        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints)
        {
        }
    };

**Comment by yelnar** [comment]
Thanks @Bajranghudda1 

I tried your solution but unfortunately it didn't help.
Actually why it should make sense? I mean, when the scanner first time scans some QR code it sees that the flag is false so it runs this code:
```
if (result.getText() != "" || result.getText() != null)
{
    beepManager.playBeepSoundAndVibrate();
    staffId = result.getText();
    Log.d(LOG," Scanned_staffId- "+ staffId);
    isThidDialogWindow = true;
}
```
And when it scans another time it just ignores that code. So what is the reason of this solution. I didn't get it.

Thank you

**Comment by rkistner** [comment]
@yelnar The default is to focus around every two seconds or so. Is this what you're seeing?

**Comment by yelnar** [comment]
@rkistner yes it is. But sometimes it becomes blurry and tries to focus very long time ~ 5-8 sec. So I can not figure why does it happen.

**Comment by swaby** [comment]
I hope to subscribe to this thread as I am seeing this issue in our production app. I installed and reproduced the issue on the sample app. I've attached a screen recording converted to GIF:

![ezgif com-resize](https://cloud.githubusercontent.com/assets/1260946/16702357/726e9ad8-4533-11e6-989e-6b167a69d1bb.gif)

**Comment by sergiobr** [comment]
Hello, I am having the same issue. 
Can please anyone give some help on this?

**Comment by eligiobz** [comment]
@yelnar @rkistner Is this somehow related to #304 ? I'm getting high scan times (several seconds) for a single code and it has to do with the camera autofocus. Using a Samsung J7 with 6.0.

**Comment by yelnar** [comment]
@eligiobz it is kinda same, but I am not sure. Actually I do not work on this now and all I can say that the issue was related to autofocusing. When I tried to scan QR code, after each successful attempt the app tried to autofocus again, which lead to big delay between each successful scans. But I wanted this app to scan very fast, and wondered why even autofocusing did happen.

**Comment by eligiobz** [comment]
@yelnar Are you still working on your project? I found that if I made the scan window a little smaller and set the focus mode to ```MACRO``` I get faster scans, it helps if what you're scanning is still. 
```java

// Camera settings
settings = new CameraSettings();
settings.setFocusMode(CameraSettings.FocusMode.MACRO);

//Barcode settings
barcodeView = (DecoratedBarcodeView) findViewById(R.id.barcodePreview);
barcodeView.getBarcodeView().setCameraSettings(settings);
barcodeView.decodeContinuous(callback);

beepManager = new BeepManager(this);
```

**Comment by rkistner** [comment]
See the discussion in #450.
