### ISSUE TITLE
选取不到合适的预览尺寸

### ISSUE THREAD

**Issue by tinybright** [journeyapps/zxing-android-embedded#163]
手机竖屏的时候 使用一块1080 * 600的区域做为预览区域 。结果似乎使用600*1080选的。
```
05-12 15:19:57.195 20182-20182/com.airi.kouan I/LegacyPreviewScalingStrategy: Preview: 768x1024; Scaled: 1152x1536; Want: 1080x600
05-12 15:21:35.941 20182-25864/com.airi.kouan I/LegacyPreviewScalingStrategy: Viewfinder size: 600x1080
05-12 15:21:35.957 20182-25864/com.airi.kouan I/LegacyPreviewScalingStrategy: Preview in order of preference: [1024x768, 960x720, 1024x576, 720x576, 704x576, 800x448, 720x480, 768x432, 640x480, 720x408, 480x480, 352x288, 320x240, 176x144]
```

**Comment by rkistner** [comment]
Please use English for issues here.

Preview sizes in `Viewfinder size: ` and `Preview in order of preference` are listed in their natural camera orientation, which is typically landscape. In this case, "Viewfinder size" is reported as `600x1080`, which either seems to indicate that either the viewfinder is not sized correctly in it's layout (1080x600 in portrait mode), or that the device is not reporting the current orientation correctly.
