### ISSUE TITLE
How to start another decodeSingle after callback?

### ISSUE THREAD

**Issue by 2fours** [journeyapps/zxing-android-embedded#164]
Have code as below. After capturing a barcode once in single mode I want to start another single mode capture but calling decodeSingle does not "restart" the capture. Nothing happens when I scan the code, no barcodes are found and the callback does not get executed again.

Looks like the second time around that cameraInstance.isOpen() is false on [line 117 of DecoderThread](https://github.com/journeyapps/zxing-android-embedded/blob/706c4073516cfeb76e17fda300f878380413ec10/zxing-android-embedded/src/com/journeyapps/barcodescanner/DecoderThread.java#L117). Is this by design? One would think calling decodeSingle again would re-initiate the process. I'm using the CompoundBarcodeView. Thanks for a great project.

```

 private BarcodeCallback callback = new BarcodeCallback() {
        @Override
        public void barcodeResult(BarcodeResult result) {
            if (result.getText() != null) {
                TextView tvMessage = (TextView) findViewById(R.id.tvMessage);

                 i  f (tvMessage != null) {
                        tvMessage.setText(R.string.registered_yay);
                   }
                   barcodeView.decodeSingle(callback);

                }
                else {
                    if (tvMessage != null) {
                        tvMessage.setText(R.string.error_registering);

                    }
                    barcodeView.decodeSingle(callback);
                }
            }
        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
        }
    };
```

**Comment by Bajranghudda1** [comment]
Hi @2fours 
Why not you are calling barcodeView.decodeContinous(callback);
so that it will always be ready to scan your all the barcodes....
because at the initialize time all the camera settings are set.

**Comment by 2fours** [comment]
I can make that work. Probably makes more sense I guess. Why even have decodeSingle?

**Comment by rkistner** [comment]
@2fours I'm not sure why the your sample is not working. `isOpen()` should only be false if `barcodeView.pause()` is called.

That said, `decodeContinous(callback)` is probably better for this use case, as @Bajranghudda1 mentioned. `decodeSingle` is mostly for cases where you want to scan and return a single barcode.

**Comment by Lintom** [comment]
@2fours 
Hi. You make it work using `decodeSingle(callback)?`

**Comment by angelnmara** [comment]
hola alguien lo pudo resolver???? tengo el mismo problema, agrege un Handler pero no creo que sea lo correcto.
hello someone could solve ???? I have the same problem, add a Handler but do not think it's right.
angelnmara@hotmail.com

**Comment by vidyajejurkar** [comment]
@rkistner can we stop decodeContinous(callback) after 2 scanning bacode and again start for next 2?
I want to do barcode scanning like below image.
Need help
![image](https://cloud.githubusercontent.com/assets/6360660/26141013/56212d72-3af7-11e7-9c65-2f7451521928.png)

**Comment by rkistner** [comment]
This can be done with `decodeContinous()` and `stopDecoding()`. The rest is up to you application.
