### ISSUE TITLE
How to set white balance parameters to Camera

### ISSUE THREAD

**Issue by yelnar** [journeyapps/zxing-android-embedded#165]
Hello

I am using this sample app [ContinuousCaptureActivity](https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java)

How can I set white balance of the Camera. As I understand I should access Camera settings and use [setWhiteBalance](http://developer.android.com/intl/ru/reference/android/hardware/Camera.Parameters.html#setWhiteBalance(java.lang.String)) method
But I can not understand how can I access the Camera from this Activity?

Thanks

**Comment by rkistner** [comment]
I'm working on some restructuring to expose the Camera instance, but currently you'll need to fork & modify the library for this.

**Comment by yelnar** [comment]
Ok, thanks. Then I will close this issue.
