### ISSUE TITLE
Code types (formats)

### ISSUE THREAD

**Issue by yelnar** [journeyapps/zxing-android-embedded#166]
Is it possible to choose code types (formats) like scan only qr codes. Because I do not need to scan bar codes.

**Comment by rkistner** [comment]
Yes - see the sample here: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L32

**Comment by yelnar** [comment]
@rkistner what about ContinuousScan case: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L47

How should I tell intent that it should scan only QR codes?

**Comment by yelnar** [comment]
@rkistner I have done as you said:

         `IntentIntegrator integrator = new IntentIntegrator(this);`
         `integrator.setCaptureActivity(ScanActivity.class);`
         `integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);`
         `integrator.addExtra("TARGET_COLOR", TARGET_COLOR);`
         `integrator.addExtra("WHITE_BALANCE", WHITE_BALANCE);`
         `integrator.setPrompt("Scan something");`
         `Intent intent = integrator.createScanIntent();`
         `startActivityForResult(intent, SCAN_WATCH);`

But it scans not only QR Codes, but also bar codes.  [This] (https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/UPC-A-036000291452.png/220px-UPC-A-036000291452.png) for example.

Can you tell me what I am doing wrong?
