### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by DaleJulian** [journeyapps/zxing-android-embedded#167]
I imported the zxing library together with this library like this:
```
`build.gradle

dependencies {
    compile 'com.google.zxing:core:3.2.1'
    compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
}`
```

Though I have implemented these following classes with my additional implementations as reference to the code provided by the libraries stated above(I copied parts of the code and added my own implementation) to meet the project specs:

- CameraInstance.java
- CameraManager.java
- CameraPreview.java
- CameraSurface.java
- CameraThread.java
- BarcodeView.java

Am I to put the Apache 2.0 licenses inside these classes?

**Comment by rkistner** [comment]
Yes - either the Apache license, or just a link to this project. This can be in the files themselves or in some overview document.
