### ISSUE TITLE
Cannot scan a specific barcode

### ISSUE THREAD

**Issue by gitterchris** [journeyapps/zxing-android-embedded#169]
Cannot scan the attached barcode: 

<img width="314" alt="barcode" src="https://cloud.githubusercontent.com/assets/5746149/15491120/92de08c4-213b-11e6-8e0d-4af1d88db50c.png">

It can be easily scanned by the Quick Mark app. Any idea why?

**Comment by rkistner** [comment]
There are two potential issues here:

1. The container is rounded, which makes the lines on the sides appear thinner than in the middle.
2. The label seems fairly reflective, which may make it difficult in certain light conditions (especially when the flash is used).

Commercial barcode scanning projects often use more advanced barcodes (and proprietary) scanning algorithms than what is available in an open source project like [zxing](https://github.com/zxing/zxing), which may help to overcome these issues. You may be able to get more help asking in the [zxing](https://github.com/zxing/zxing) project directly, but without someone actually contributing improvements to the algorithm you're unlikely to get improvements soon.
