### ISSUE TITLE
Scan only QR codes

### ISSUE THREAD

**Issue by yelnar** [journeyapps/zxing-android-embedded#172]
I want to scan only QR codes so I wrote:

     IntentIntegrator integrator = new IntentIntegrator(this);
     integrator.setCaptureActivity(ScanActivity.class);
     integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
     integrator.addExtra("TARGET_COLOR", TARGET_COLOR);
     integrator.addExtra("WHITE_BALANCE", WHITE_BALANCE);
     integrator.setPrompt("Scan something");
     Intent intent = integrator.createScanIntent();
     startActivityForResult(intent, MY_RESULT_CODE);

But it scans also bar codes, [this](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/UPC-A-036000291452.png/220px-UPC-A-036000291452.png) for example.

Can you tell me what is wrong here?

**Comment by rkistner** [comment]
I don't see any issue in that code - that is supposed to only scan QR codes. I'll do more testing later to confirm.

**Comment by rkistner** [comment]
I see now that you are using your own Activity (`ScanActivity`). You need to make sure that it handles the Intent properly. This is done in [CompoundBarcodeView#initializeFromIntent](https://github.com/journeyapps/zxing-android-embedded/blob/905e4a33d69d4e989cfc925e21f51fb15042c1d3/zxing-android-embedded/src/com/journeyapps/barcodescanner/CompoundBarcodeView.java#L132), which is done automatically if you use `CaptureManager`.
