### ISSUE TITLE
IntentIntegrator setTimeout not available in :zxing-android-embedded:3.2.0

### ISSUE THREAD

**Issue by rodent129** [journeyapps/zxing-android-embedded#174]
compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
compile 'com.google.zxing:core:3.2.1'

Using above in my gradle, but this release not yet include setTimeout. 

I would like to know how/when to get a next stable version which include setTimeAPI. 

Thanks a lot.

**Comment by rkistner** [comment]
You may be able to use pre-release builds from jitpack.io: https://jitpack.io/#journeyapps/zxing-android-embedded/e7fce1f563, but I haven't tried it myself yet.

I should have the 3.3.0 release ready later today.

**Comment by rkistner** [comment]
[v3.3.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.3.0) is released and available in the repository now.
