### ISSUE TITLE
How to use CompoundBarCodeView in fragment in android 6.0?

### ISSUE THREAD

**Issue by thitoo** [journeyapps/zxing-android-embedded#175]
I make request run time permission in fragment. Where can i call .resume() method?

**Comment by rkistner** [comment]
You should call resume as soon as the permission has been granted. See [CaptureManager](https://github.com/journeyapps/zxing-android-embedded/blob/905e4a33d69d4e989cfc925e21f51fb15042c1d3/zxing-android-embedded/src/com/journeyapps/barcodescanner/CaptureManager.java#L263) for an example of how this is done.
