### ISSUE TITLE
camera preview corruption 

### ISSUE THREAD

**Issue by devkumar2486** [journeyapps/zxing-android-embedded#176]
#### Description of the problem:

Camera shows corrupted preview immediately after starting the scan as shown in attached screenshots. Issue replicated on S7 Edge and Galaxy S4. Force stop/reinstall/change camera settings have no effect.

**Which library version are you using?** 
3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Samsung Galaxy S4 Android 4.4.2 and 5.0.1

**Does the same happen on other devices or an emulator?**
App working fine on other devices

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Not tried with sample project yet. 

**In the case of an error do you have a stack trace or adb logs?**
NO

**Comment by devkumar2486** [comment]
![img_0110](https://cloud.githubusercontent.com/assets/19388960/15822380/13140b2e-2c13-11e6-8921-0159f9523e8d.JPG)
![screen shot 2016-06-02 at 7 21 53 am](https://cloud.githubusercontent.com/assets/19388960/15822381/1319adfe-2c13-11e6-93df-938878b12bb4.jpg)
![img_0109](https://cloud.githubusercontent.com/assets/19388960/15822382/131b861a-2c13-11e6-9002-f6ea03ae619f.JPG)

**Comment by rkistner** [comment]
This typically happens when the device's camera does not support a specific configuration. Sometimes it can be solved by changing some camera parameters (e.g. FPS), but usually it's the easiest to use a different preview resolution.

You can start by experimentation with the scaling strategies listed here: https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md#notes-on-scaling

It may also be helpful to check the adb logs - it shows which preview size is selected.

**Comment by devkumar2486** [comment]
Hi Rkistner, Thanks for your support, I tried to change the scaling combination but it didn't made any difference. 
At the same time I do Have some more detail to share. 

I have found that the scanner could not scan some QR-code with poor print quality, also it takes longer time scanning good quality QR codes also, however I am able to scan same QR-code with Zxing app very quickly.
I found that the reason was that the decoder fires exception if the captured image size is larger. 
Finally I fixed the issue by adding below code to the CameraManager.java-> setDesiredParameters method

......
List<Size> previewSizes = getPreviewSizes(parameters);
        if (previewSizes.size() == 0) {
            requestedPreviewSize = null;
        } else {
            requestedPreviewSize = displayConfiguration.getBestPreviewSize(previewSizes, isCameraRotated());
            ////////////////////////////
            //code added by devendra to fix scan performance issue
            if(!requestedPreviewSize.fitsIn(new Size(1200,675))){
                //Log.e(TAG,"scaling the size");
                requestedPreviewSize = requestedPreviewSize.scaleFit(new Size(1200,675));
            }
            /////////////////////////////////////////
            parameters.setPreviewSize(requestedPreviewSize.width, requestedPreviewSize.height);
        }
......

This does fixed the issue and the app was able to scan QR codes very quickly.
But this fix brought the Preview corruption issue on some of the devices. 
Can you advice how to overcome this.

**Comment by rkistner** [comment]
Just to clarify, do you only get that preview corruption issues when you use the changes in the `setDesiredParameters` method?

You mentioned you got an exception - do you have a stack trace for this?

So to summarize:
1. The default method picks preview size that is too large, which degrades QR scanning performance.
2. Changing the chosen preview size makes the scanning faster / better, but breaks the preview on some devices.

Point (2) is likely to happen when the chosen preview size is not one of the sizes that the camera specifically supports. We can solve this by instead just rejecting any previews that are too large, by changing the scoring function, e.g. here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/camera/FitXYStrategy.java#L40

**Comment by devkumar2486** [comment]
Yes the preview corruption only occurs when I apply changes in setDesiredParameters().

the exception occurs in  com.journeyapps.barcodescanner.Decoder.java class in 
```
protected Result decode(BinaryBitmap bitmap) {
        possibleResultPoints.clear();
        try {
            if (reader instanceof MultiFormatReader) {
                // Optimization - MultiFormatReader's normal decode() method is slow.
                return ((MultiFormatReader) reader).decodeWithState(bitmap);
            } else {
                return reader.decode(bitmap);
            }
        } catch (Exception e) {
            e.printStackTrace();
            // Decode error, try again next frame
            return null;
        } finally {
            reader.reset();
        }
    }
```
stackTrace result is : com.google.zxing.NotFoundException

I found some idea about size of QR code from http://stackoverflow.com/a/14935871/1302592 however it looks to me that I should reduce size of captured Image not the preview itself.

**Comment by rkistner** [comment]
Reducing the size of the preview should work, as long as you use one of the "supported" preview sizes.

Take a look at this branch:
https://github.com/journeyapps/zxing-android-embedded/compare/limit-preview-size

It's quite a bit behind master, and may require some effort to merge, but you can use that a starting point to limit the preview size.

**Comment by devkumar2486** [comment]
Hi Rikistner,
Just want to update you that the solution provided to limit the preview size worked and solved the preview corruption issue, however the scan performance is a bit slower but acceptable. 
Thank you very much for your support.

**Comment by rkistner** [comment]
Closing as a device-specific issue.
