### ISSUE TITLE
How can i change prompt message below the scanner "Place a barcode inside the viewfinder rectangle to scan it"?

### ISSUE THREAD

**Issue by thitoo** [journeyapps/zxing-android-embedded#179]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by thitoo** [comment]
version is 3.2

**Comment by rkistner** [comment]
Yes, it's `setStatusText()` on `DecoratedBarcodeView`, or `setPrompt()` on `IntentIntegrator`.

**Comment by Erasmojf** [comment]
Thanks it work for me!
