### ISSUE TITLE
Scan Barcode Custom Layout and Fragment Scanning

### ISSUE THREAD

**Issue by Nguyenjimmy101** [journeyapps/zxing-android-embedded#180]
#### Description of the problem:

I wanted to do a scan like the 1D any orientation in the Sample project but in a fragment. So i tried IntentIntegrator integrator = new IntentIntegrator.forSupportFragment(this); with the rest of the 1D any orientation in the fragment class but it doesnt seem to work. Does Fragment support customize options? Thanks

**Which library version are you using?** E.g. 3.2.0.
3.2.1
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Samsung Galaxy Note 5
**Does the same happen on other devices or an emulator?**
Yes
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
What was the specific issue here?
