### ISSUE TITLE
Can't enable vibrate.

### ISSUE THREAD

**Issue by dmitrikudrenko** [journeyapps/zxing-android-embedded#182]
com.google.zxing.client.android.BeepManager#vibrateEnabled is always false, and it can't be changed

**Comment by Bajranghudda1** [comment]
BeepManager beepManager = new BeepManager(getActivity());
 beepManager.setVibrateEnabled(true);
and play vibrate in result callback
 beepManager.playBeepSoundAndVibrate();

and close on onPause()
beepManager.close();

**Comment by EmeraldWolfram** [comment]
You need to add permission to VIBRATE in the AndroidManifest also
