### ISSUE TITLE
sound depends on ringer mode

### ISSUE THREAD

**Issue by Servus7** [journeyapps/zxing-android-embedded#186]
Beep manager plays sound depending on the ringer mode. But the device only plays a sound if the media sounds are not muted. So ringtone and mediatone must not be muted to play the beep.
It would be better to just play the beep if enabled and let the system take the decision whether or not to play on the speakers.

**Comment by rkistner** [comment]
I agree, this should just be connected to the media volume, and not the ringer volume. So just removing the ringer mode check should fix this?

**Comment by Servus7** [comment]
Their are two options.

1. Remove every check and let the system manage the sound
2. Or check for media volume on devices with Lolipop or newer

**Comment by rkistner** [comment]
Fixed in e3d3950d - now only depends on the media volume.
