### ISSUE TITLE
OnActivityResault isn't being called properly.

### ISSUE THREAD

**Issue by Pesof** [journeyapps/zxing-android-embedded#189]
#### Description of the problem:
I am calling a fragment from a Navigation drawer activity, In that fragment i have a button which launches the customScannerActivity.
I am facing a problem with the onActivityResault, I override the onActivityResault in the Navigation Drawer Activity and in the fragment.
in the Activity :
 ```
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }
```
in the fragment :

```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            if(result.getContents() == null) {
                toast = "Cancelled from fragment";
            } else {
                toast = "Scanned from fragment: " + result.getContents();
            }

            // At this point we may or may not have a reference to the activity
            displayToast();
        }
    }
```

what is happening is that the onActivityResault is only being called in the activity and not in the fragment( that contains the button to launch the CustomScanner).
So the toast isn't being launched.

I know this might be a noob question but i have tried every thing and it isn't working

**Which library version are you using?** E.g. 3.2.0.
Library 3.3.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Android 5.0 galaxy s5
**Does the same happen on other devices or an emulator?**
yes.

**Comment by rkistner** [comment]
How are you starting the barcode scanner from the button press?

**Comment by Pesof** [comment]
Thanks for your reply :)
I am calling it from the onClick in that fragment (just like in your demo project)

public void scanCustomScanner(View view) {
        IntentIntegrator.forSupportFragment(this).initiateScan();
    }

**Comment by rkistner** [comment]
Instead of `new IntentIntegrator(getActivity())`, use `IntentIntegrator.forSupportFragment(this)`. See https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L121 

Otherwise it thinks it's the Activity that's launching the scanner, and passes the result back to the Activity instead of the Fragment.

**Comment by Pesof** [comment]
That solved it I appriciate your help :)
the problem was sending (getActivity) instead of (this)
thanks for your help and time :)
