### ISSUE TITLE
No decode the qr-code when loading from a file

### ISSUE THREAD

**Issue by Aazamandius** [journeyapps/zxing-android-embedded#190]
I have attached the file. Library can not recognize the code shown on it on any device when loading from storage. 
Important condition - the presence of text in the image

![img_1407](https://cloud.githubusercontent.com/assets/4215125/17061449/38e9fe88-5037-11e6-83fc-f416d0601076.jpg)

**Comment by rkistner** [comment]
What do you mean by loading from storage? How are you reading the barcode?

**Comment by Aazamandius** [comment]
I use the following code

InputStream inputStream = getContentResolver().openInputStream(selectedImageUri);//Load image stream
Result parseResult = parseQr(inputStream);
if (parseResult != null && parseResult.getBarcodeFormat() == BarcodeFormat.QR_CODE){

} else {
  new DummyEventTask(null, "QROpenError").execute();
}


Where
    public static Result parseQr(InputStream inputStream){
        Bitmap bitmap = BitmapFactory.decodeStream(inputStream);
        if (bitmap == null)
        {
            return null;
        }
        int width = bitmap.getWidth(), height = bitmap.getHeight();
        int[] pixels = new int[width * height];
        bitmap.getPixels(pixels, 0, width, 0, 0, width, height);
        bitmap.recycle();
        bitmap = null;
        RGBLuminanceSource source = new RGBLuminanceSource(width, height, pixels);
        BinaryBitmap bBitmap = new BinaryBitmap(new HybridBinarizer(source));
        MultiFormatReader reader = new MultiFormatReader();
        try
        {
            Result result = reader.decode(bBitmap);
            return result;
        }
        catch (NotFoundException e)
        {
            return null;
        }
    }

**Comment by rkistner** [comment]
This seems to be an issue with the underlying decoding library, so you should report it directly at https://github.com/zxing/zxing/issues.
