### ISSUE TITLE
onActivityResult calling before result back from the captureactivity.

### ISSUE THREAD

**Issue by changulpaye** [journeyapps/zxing-android-embedded#193]
#### Description of the problem:

I am calling <code>  new IntentIntegrator(this).initiateScan(); </code> from activity. It's work fine on 5.0 and above Android os version but on old version 4.2 onactivityresult callback immediately when initiate scan. 

**Which library version are you using?** E.g. 3.2.0.
   compile 'com.journeyapps:zxing-android-embedded:3.3.0'

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Android 4.2

**Does the same happen on other devices or an emulator?**
Device

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by elf-zwolf** [comment]
I face this on Android 7.0 and Android 5.1. So camera activity isn't closed after result is provided

**Comment by rkistner** [comment]
Some bugs around this has been fixed since this issue was opened. Please create a new issue with a stack trace if the issue persists in 3.5.0.
