### ISSUE TITLE
Camera not opening on Android 4.0.3

### ISSUE THREAD

**Issue by marwan-magpie** [journeyapps/zxing-android-embedded#194]
#### Description of the problem:
Using the sample project, the camera is not opening on "CONTINUES SCANNING", "ACTIVITY WITH TOOLBAR" and "CUSTOM SCANNER ACTIVITY'.
However, the scanner is working on the rest of the options. As I need to use the continues scanning, I couldn't find the reason why the camera is not opening on these particular activities.

**Which library version are you using? 
3.3.0

**Which phone/tablet are you using, and which Android version does it run?
 Samsung Galaxy S II GT-I9100
  Android: 4.0.3

**Does the same happen on other devices or an emulator? 
No

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes, this issue produced using the sample project.

**In the case of an error do you have a stack trace or adb logs?**
Not showing any error.

Thanks.

**Comment by rkistner** [comment]
Seems like a problem with that specific device - see the workaround in #188.
