### ISSUE TITLE
Front Camera is Mirrored and not Scan Barcode

### ISSUE THREAD

**Issue by pliska87** [journeyapps/zxing-android-embedded#197]
Hi,

I'm trying to use you project for an app that i'm developing.
I must scan barcode with front camera, but the image is mirrored and i cant read the barcode....there is a method to overcome this problem? 
I try to integrate your code with the "TextureView mode" for mirroring the camera, but without any success....

Can you help me?

Thank's a lot!

**Comment by rkistner** [comment]
As far as I know only the preview is mirrored, and the image used for scanning is fine. This does mean that the result points do not match up on the ViewfinderView, but that doesn't impact the scanning itself.

Also see #34.
