### ISSUE TITLE
java.lang.RuntimeException: Failed to open camera in Kitkat and lower

### ISSUE THREAD

**Issue by hasanarmsys** [journeyapps/zxing-android-embedded#198]
#### Description of the problem:
I have integrated the same barcode scanner into my app. It is working fine only in android Marshmallow and Lollipop. But when i run it on Kitkat it shows
java.lang.RuntimeException: Failed to open camera 
could you please help me out to solve this?

I am using  compile 'com.journeyapps:zxing-android-embedded:3.3.0'

This is my MainActivity where i am using the scanner

public class MainActivity extends AppCompatActivity {
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    Button button = (Button) findViewById(R.id.button_scan);
    button.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            new IntentIntegrator(MainActivity.this).initiateScan();
        }
    });
}

@Override
protected void onActivityResult(int requestCode, int resultCode,Intent data) {
    IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
    if(result != null) {
        if(result.getContents() == null) {
            Toast.makeText(this, "Cancelled",   Toast.LENGTH_LONG).show();
        } else {
            Toast.makeText(this, "Scanned: " + result.getContents(), Toast.LENGTH_LONG).show();

    } else {
        super.onActivityResult(requestCode, resultCode, data);
    }
}

**Comment by rkistner** [comment]
Which specific device does it crash on?

Can you post the full stack trace please?

**Comment by hasanarmsys** [comment]
Hello thank you so much for your email,

I have tested it on Android M and L its woeking fine,

But when i run it on Kitkat the app is crashing due java.lang.RuntimeException:
Failed to open camera,

Please help me to fix it soon its urgently needed.

Thank you,

This is my stack trace

08-13 14:44:04.626 1564-1719/system_process V/WindowManager:   #4:
Window{9d490240 u0
com.example.geelani.zscanner/com.example.geelani.zscanner.MainActivity}
08-13 14:44:04.626 1564-1719/system_process V/WindowManager:   #5:
Window{9d432c98 u0 com.android.launcher/com.android.launcher2.Launcher}
08-13 14:44:04.626 1564-1719/system_process V/WindowManager:   #6:
Window{9d463fc8 u0 com.android.systemui.ImageWallpaper}
08-13 14:44:04.656 3654-3654/com.example.geelani.zscanner D/CameraPreview:
resume()
08-13 14:44:04.656 3654-4166/com.example.geelani.zscanner D/CameraInstance:
Opening camera
08-13 14:44:04.656 3654-4166/com.example.geelani.zscanner
W/com.google.zxing.client.android.camera.open.OpenCameraInterface: No
cameras!
08-13 14:44:04.656 3654-4166/com.example.geelani.zscanner E/CameraInstance:
Failed to open camera

java.lang.RuntimeException: Failed to open camera

    at
com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:129)

    at
com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:185)

    at android.os.Handler.handleCallback(Handler.java:733)

    at android.os.Handler.dispatchMessage(Handler.java:95)

    at android.os.Looper.loop(Looper.java:136)

    at android.os.HandlerThread.run(HandlerThread.java:61)
08-13 14:44:04.676 3654-4166/com.example.geelani.zscanner D/CameraInstance:
Configuring camera
08-13 14:44:04.676 3654-4166/com.example.geelani.zscanner E/CameraInstance:
Failed to configure camera

java.lang.RuntimeException: Camera not open

    at
com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:146)

    at
com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:198)

    at android.os.Handler.handleCallback(Handler.java:733)

    at android.os.Handler.dispatchMessage(Handler.java:95)

    at android.os.Looper.loop(Looper.java:136)

    at android.os.HandlerThread.run(HandlerThread.java:61)
08-13 14:44:04.686 3654-3654/com.example.geelani.zscanner E/MediaPlayer:
Should have subtitle controller already set
08-13 14:44:04.686 3654-3654/com.example.geelani.zscanner D/CameraPreview:
pause()
08-13 14:44:04.686 3654-4166/com.example.geelani.zscanner D/CameraInstance:
Closing camera
08-13 14:44:04.706 1564-1578/system_process I/WindowManager: Screen frozen
for +128ms due to Window{9d3f9768 u0
com.example.geelani.zscanner/com.journeyapps.barcodescanner.CaptureActivity}
08-13 14:44:04.756 1564-1578/system_process I/ActivityManager: Displayed
com.example.geelani.zscanner/com.journeyapps.barcodescanner.CaptureActivity:
+179ms
08-13 14:44:06.736 1564-1578/system_process D/dalvikvm: GC_EXPLICIT freed
168K, 30% free 8770K/12480

**Comment by rkistner** [comment]
Which device is this? From the logs it seems like it can't find any camera.

**Comment by hasanarmsys** [comment]
I am testing it on Kitkat  4.1.1 it is showing  Failed to open camera
error. Can you please fix this

**Comment by rkistner** [comment]
Which device is that? For example an Samsung Galaxy S3, or an emulator?

**Comment by hasanarmsys** [comment]
It is micromax canvas A88. It was my camera fault, now its working
absolutely fine.Thank you so much

**Comment by rkistner** [comment]
Thanks, good to hear it's solved.
