### ISSUE TITLE
How can I make the ViewFinderView invalidate faster

### ISSUE THREAD

**Issue by XanthusL** [journeyapps/zxing-android-embedded#200]
#### I need a moving line in the rectangle :

I override the onDraw() method of ViewFinderView. 
But it's not fast enough to be smooth. And I failed to find out how to change the frequency of previewSized() method of "CameraPreview.StateListener".

**Comment by rkistner** [comment]
Are you drawing something based on results from the barcode scanner, or based on something else (e.g. a timer)?

There is currently a 80ms delay between draws for the laser animation. The barcode result points will typically be less frequent than that.

If you're doing significant customizations to the `ViewfinderView`, it may be the easiest to just copy the entire class. You'll then also need your own verssion of `DecoratedBarcodeView`, but that is essentially just a `FrameLayout` that overlays the `ViewfinderView` on top of the `BarcodeView`.
