### ISSUE TITLE
Camera error in Android 6.0 version if we deny the permission request.

### ISSUE THREAD

**Issue by mohitauappface** [journeyapps/zxing-android-embedded#201]
#### Description of the problem:

I am using ZXing library in my app.For android version below 6.0,its working fine.But for Marshmallow if we deny the permission request it is giving an error alert dialog saying "Sorry,the Android camera encountered a problem.You may need to restart the device." When we "Allow" the permission it is working properly,but when we denied it is giving above error till we got to that app settings and grant the permission manually.My requirement is instead if that error alert i want to show a custom alert that can take the user to app settings.I have tried all the possible ways that I know,but nothing helped me.

**Which library version are you using?** E.g. 3.2.0.
3.2.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Moto G3, Android 6.0
**Does the same happen on other devices or an emulator?**
No. Only in Marshmallow devices.
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
I have checked this issue in Barcode scanner app from ZXing. I am getting the same issue when I deny the permission.I think in that ZXing barcode scanner app,the targetSdkVersion they used is 21,as it is asking for permission at the time of installing Barcode Scanner ZXing from play store.
**In the case of an error do you have a stack trace or adb logs?**
Yes.

**Comment by rkistner** [comment]
Best way to do this currently is to request the permission yourself before opening the barcode scanner.

**Comment by nguyenquocchinhdev** [comment]
You must request the permission camera before opening the barcode scanner. Because beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app.

**Comment by rkistner** [comment]
Some issues around permission handling has been fixed since this was opened. Please open an issue again if the issue persists.

**Comment by asifali9145** [comment]
How to Add permission for All android set? Did any one have any about this?

**Comment by nguyenquocchinhdev** [comment]
@asifali9145 You can reference Android Developer site
https://developer.android.com/training/permissions/requesting.html
