### ISSUE TITLE
CameraPreview not fully initialized as the textureview is already available at the time that the surface texture listener is added

### ISSUE THREAD

**Issue by jstemberger** [journeyapps/zxing-android-embedded#202]
#### Description of the problem:

There seems to be a race condition that I have encountered on when dealing with permissions and the TextView used in the CameraPreview view. Specifically in in CameraPreview.resume the surface texture listener is added after the textureview is already available. Because of this the listener is never triggered and the currentSurfaceSize is never set. This causes the preview view never to be fully initialized and thus never displayed.

The problem happens if you delay on the grant permission screen after it have been requested. 

**Which library version are you using?**
3.3.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Google Nexus 6p,  Nexus 5X 6.0

**Comment by rkistner** [comment]
Thanks - I see sent a PR in #204. May be related to an issue reported a few times that I haven't been able to reproduce myself yet.

**Comment by rkistner** [comment]
PR has been merged and released in 3.4.0.
