### ISSUE TITLE
While scanning a pdf417 format i received a UPC_E  format

### ISSUE THREAD

**Issue by rmanacmol** [journeyapps/zxing-android-embedded#205]
While scanning a pdf417 format i received a UPC_E  format (sometimes)

compile 'com.journeyapps:zxing-android-embedded:3.3.0'

Asus K010  -  Android 4.4.2

**Comment by rkistner** [comment]
Some of the 1D barcodes has lots of false positives unfortunately. Limiting the scanner to specific barcode types (as in #206) should solve the problem.

**Comment by alphanumericaracters** [comment]
I made that, one button for PDF417 and other for QR. but im in troubles with PDF417, the scan it's so fast that doesn't read well.
