### ISSUE TITLE
BarcodeView Usage

### ISSUE THREAD

**Issue by rmanacmol** [journeyapps/zxing-android-embedded#206]
Can i set barcode view to scan specific barcode format such as pdf417?

**Comment by rkistner** [comment]
Via Intent: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L34 

Or directly on the BarcodeView: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/DecoratedBarcodeView.java#L155

**Comment by erKaranjeet** [comment]
I am facing one problem. I have missing a file "com.journeyapps.barcodescanner.DecoratedBarcodeView". Can any one guide me how to add this file in my project.
