### ISSUE TITLE
Zxing not working with Tabs

### ISSUE THREAD

**Issue by flynnben123** [journeyapps/zxing-android-embedded#208]
I just have a basic continious scan activity but when i tried to implement a tabbed view with the app, the zxing barcodeview no longer worked and it just is a black box with the text on the bottom.  PLEASE HELP with this problem....???

**Comment by rkistner** [comment]
Are the `resume()` and `pause()` calls made when the BarcodeView is displayed / hidden?

Are there any errors showing up in the logs?

A small sample app demonstrating the issue would help.

**Comment by flynnben123** [comment]
There are no errors that come up in the logs, and yes both the resume() and pause() methods are called, here is the scan activity code:

public class ScanActivity extends AppCompatActivity {


    private static final String TAG = ScanActivity.class.getSimpleName();
    private DecoratedBarcodeView barcodeView;

    private BarcodeCallback callback = new BarcodeCallback() {
        @Override
        public void barcodeResult(BarcodeResult result) {
            if (result.getText() != null) {
                barcodeView.setStatusText(result.getText());
            }

        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_scan);

        barcodeView = (DecoratedBarcodeView) findViewById(R.id.zxing_barcode_scanner);
        barcodeView.decodeContinuous(callback);
    }

    @Override
    protected void onResume() {
        super.onResume();

        barcodeView.resume();
    }

    @Override
    protected void onPause() {
        super.onPause();

        barcodeView.pause();
    }

    public void pause(View view) {
        barcodeView.pause();
    }

    public void resume(View view) {
        barcodeView.resume();
    }

    public void triggerScan(View view) {
        barcodeView.decodeSingle(callback);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        return barcodeView.onKeyDown(keyCode, event) || super.onKeyDown(keyCode, event);
    }}

**Comment by rkistner** [comment]
Added an example with tabs here: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/TabbedScanning.java

**Comment by n-mam** [comment]
tabbed scanning option doesn't seem to be working.. is there anything else that needs to be done here ?

**Comment by rkistner** [comment]
@n-mam What specific issue do you get?

Note that the "Tabs" example doesn't do actual scanning - it just demonstrates the camera handling.

**Comment by n-mam** [comment]
oh okay.. just like all other options, I was expecting the scan to be operational. 

Thanks for the clarification

**Comment by Nonononoki** [comment]
@rkistner Sorry to bother you, but how can I enable actual scanning in the tabbed example?

**Comment by sravanthiRaju** [comment]
Hi @rkistner .I am also trying scan using tabbed example but it is not working.
Please explain how to enable scanning in fragment in particuler tab.

Thanking You.

**Comment by Nonononoki** [comment]
@sravanthiRaju I got it working. 

Add this to the ScanFragment:

`CaptureManager capture;`


And add this code in your onCreateView()

`capture = new CaptureManager(getActivity(), barcodeView);`
`capture.initializeFromIntent(getActivity().getIntent(), savedInstanceState);`
`capture.decode();`

**Comment by sravanthiRaju** [comment]
@Nonononoki Thank you for your answer.
But how we can get the QR code content result.

Thanking You.

**Comment by Nonononoki** [comment]
@sravanthiRaju

Add this in your Main Activity: 

`new IntentIntegrator(this).setCaptureActivity(TabbedScanning.class).initiateScan();`

**Comment by sravanthiRaju** [comment]
@Nonononoki Thank You,
But i want display this result value in ScanFragment above scanning screen.I do not want to go back to Main activity

**Comment by sravanthiRaju** [comment]
@Nonononoki Thank you for your replay. And solved my issue.

**Comment by natsirasrafi** [comment]
> @sravanthiRaju
> 
> Add this in your Main Activity:
> 
> `new IntentIntegrator(this).setCaptureActivity(TabbedScanning.class).initiateScan();`

where is the location to add in mainactivity?
