### ISSUE TITLE
Enable frontal lighting

### ISSUE THREAD

**Issue by rafaelpivetta** [journeyapps/zxing-android-embedded#212]
How I can enable frontal lighting in zxing-android-embedded for more effective reading of the barcode?

Using 3.3.0.

**Comment by Zyphlex** [comment]
In the samples look at the CustomScannerActivity.java, it shows how you can use the phones flashlight

**Comment by meierjan** [comment]
@Zyphlex Ain't that the led on the back?

**Comment by Zyphlex** [comment]
No, I have implemented it myself a few months ago and it turns the
flashlight on/off

**Comment by rafaelpivetta** [comment]
Would be possible to include setTorch(true) like others methods in IntentIntegrator?

**Comment by rkistner** [comment]
By default the volume up/down buttons can be used to turn the flash on or off.

It's not currently possible to control this directly via IntentIntegrator.
