### ISSUE TITLE
Remove Transparent Background

### ISSUE THREAD

**Issue by Vandam** [journeyapps/zxing-android-embedded#213]
#### Description of the problem: Transparent Background Removal.

I am not using the Source per say, just the Compile:

```
compile 'com.journeyapps:zxing-android-embedded:3.3.0'
```

When you setup the scan view, it has the Red Line (Which i want to keep), but has a Black Border, How would I set the Bar Line Directly in center of Frame, and remove the Transparent black border around the red line?

**Comment by Bajranghudda1** [comment]
@Vandam 
Try this
barcodeView.getViewFinder().setVisibility(View.GONE);
