### ISSUE TITLE
verlay in zxing scanner

### ISSUE THREAD

**Issue by louis8663** [journeyapps/zxing-android-embedded#215]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Need more details.
