### ISSUE TITLE
Provide Hints

### ISSUE THREAD

**Issue by tcarrington** [journeyapps/zxing-android-embedded#216]
#### Description of the problem:

**Which library version are you using?**
3.3.0

Hi, is there a way to provide hints? I assume this could be done in the IntentIntegrator, any suggestions?

**Comment by rkistner** [comment]
What do you mean by hints?

**Comment by tcarrington** [comment]
Here is the best summarized description and example (using zxing) I could find.

http://developer.blackberry.com/bbos/java/documentation/barcode_scanning_1970231_11.html

I think the hints need to be set before scanning.

here is another example: http://stackoverflow.com/questions/23156399/how-to-decode-a-barcode-from-camera-preview-using-zxing-library-in-android

**Comment by rkistner** [comment]
The formats are set with `IntentIntegrator#setDesiredBarcodeFormats()`:
https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/google/zxing/integration/android/IntentIntegrator.java#L193

Other hints can be set with `IntentIntegrator#addExtra()`: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/google/zxing/integration/android/IntentIntegrator.java#L125
