### ISSUE TITLE
Motorola XT1068 (Marshmallow 6.1) camera is not working

### ISSUE THREAD

**Issue by Mehul-Gajjar** [journeyapps/zxing-android-embedded#217]
my problem is whenever i trying to scan QR it only display blank screen with footer info text (**Place a barcode inside the viewfinder rectangle to scan it**.) but camera is not working there is only black screen are there....

------ i am using Zxing 3.0 and my gradle is **compile 'com.google.zxing:core:3.0.1'**

------ i am using Motorola XT1086, and Android version is 6.1

------ i am getting problem in this device only in other working perfect.

------ i am not getting any error during scanning just screen goes blank with footer text.

**Comment by rkistner** [comment]
Does the standard Barcode Scanner app work on the device? https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en

Does the sample app work on the device? https://github.com/journeyapps/zxing-android-embedded/releases/download/v3.3.0/sample-release-3.3.0.apk

Can you post the adb logs you get when you have the black screen?

**Comment by Mehul-Gajjar** [comment]
hey thanks for reply i got solution, i found that i have not implemented run-time permission above 23, it is working fine... thanks....

**Reason and Solution Did:**
when my target SDK was 22 then it was not working above 23 SDK android version but below it was working fine.. but when i changed it to 23 SDK and implemented run-time permission then it is working fine in 23 SDK and below android version.... 

it must have to run without run-time permission but don't know why.. may i know reason?.

**Comment by aibeke** [comment]
Hello.
I have same problem, but device is LG X Cam, Android version is 6.0.
How to implement run-time permission?
Can you show some sample code?

**Comment by skolarianer** [comment]
@aibeke http://lmgtfy.com/?q=android+runtime+permissions

**Comment by aibeke** [comment]
@skolarianer Thank you. We solved the problem. :) 
Just when installing forgot to give the right of the camera.

**Comment by revrkk** [comment]
I faced the same issue. But in my case, I got the following from the logs
> W/TextureView: A TextureView or a subclass can only be used with hardware acceleration enabled.

So I just set the hardware acceleration for the activity in the manifest file. and It worked.!
> android:hardwareAccelerated="true"
