### ISSUE TITLE
Start and Stop Explicitly

### ISSUE THREAD

**Issue by maduperera** [journeyapps/zxing-android-embedded#219]
Hi,
I use 

`barcodeScannerView.decodeContinuous(callback);`

for my app and want to start and stop the camera view By a toggle button. Is there a predefined method for such.

**Comment by rkistner** [comment]
You can use `barcodeScannerView.pause()` and `barcodeScannerView.resume()`.

If you just want to pause the decoding and keep the camera preview active, you can use `barcodeScannerView.stopDecoding()`, then call `barcodeScannerView.decodeContinuous(callback)` again later.

**Comment by maduperera** [comment]
Cool!  Thanks.
it was quick. I wanted the pause and resume it seems. 
When I paused surely the camera view stoped but the red line still blinks.

**Comment by maduperera** [comment]
Got it. 
I used  barcodeScannerView.getViewFinder().setVisibility(View.INVISIBLE);
Thank you guys for the wonderfully enhanced library.

**Comment by romaopedro** [comment]
I combined 
`barcodeScannerView.pause()`, `barcodeScannerView.resume()` and `barcodeScannerView.visibility = View.INVISIBLE` or View.VISIBLE to hide the freezed camera image.
