### ISSUE TITLE
How can I import this module to my project locally in android studio?

### ISSUE THREAD

**Issue by william2772** [journeyapps/zxing-android-embedded#220]
Hello everyone, I am new to this module and I would like to embed this module in my application for creating a decode-scanner activity without installing the third-party barcode scanner APP provided by the original ZXing library. 

I noticed that I can do it by adding dependency to build.gradle in android studio but it is more preferable if I can embed this locally (as a module or android library) in my android studio project so that I can make some modification to the code when needed. 

I tried importing this directly to my project (File --> import module), but it ends up with some errors, such as "project.androidTargetSdk not found" or "Plugin with id 'com.jfrog.bintray' not found"

Therefore, can I have the steps of how to import this module locally in android studio?

Thanks for noticing this issue and appreciate for any help.

**Comment by rkistner** [comment]
The code is not structured with that use case in mind, but you should be able to get it to work. You may have to make some modifications in the library gradle files though.

I can't help out with the specifics, but if you do figure it out, please post any changes you had to make here, to help others in the future.

**Comment by winnerawan** [comment]
@william2772 just change dependencies in build gradle, if you still need it, i'll write more detail
```gradle
//    api project.zxingCore
    implementation 'com.google.zxing:core:3.3.2'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation "com.android.support:support-annotations:28.0.0"
    testImplementation 'junit:junit:4.12'
    testImplementation "org.mockito:mockito-core:2.15.0"
```
