### ISSUE TITLE
How to override 'ViewfinderView' file ?

### ISSUE THREAD

**Issue by rhettor** [journeyapps/zxing-android-embedded#222]
i want to modify ViewfinderView.java sourcecode to change barcode scanner view, how can i do it?

**Comment by rkistner** [comment]
The easiest is currently to copy the source for `ViewfinderView` and `DecoratedBarcodeView`, and use the modified versions directly.

**Comment by rhettor** [comment]
Thanks, i just extends ViewfinderView, it working for me!
