### ISSUE TITLE
capture bar codes always in full screen mode (with any screen orientation)

### ISSUE THREAD

**Issue by cafc3** [journeyapps/zxing-android-embedded#223]
Hi, 

When I'm using in my code **setCaptureActivity** (to capture bar codes in any screen orientation) the  android notification bar remains visible but I want the camera always on full mode (without the notification bar)... if I don't use this method (setCaptureActivity) it doesn't show the notification bar at all. Has anyone have passed by any situation like this one? Can anyone help me please?
thanks in advance
cafc

i'm follwing this manual here: 

https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md

Here is my activity_main.xml complete file:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:id="@+id/activity_main"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context="com.example.ccapela.leitorcb.MainActivity">

    <Button
        android:id="@+id/scan_btn"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:text="@string/scan" />

    <TextView
        android:id="@+id/scan_content_tv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_above="@+id/scan_format_tv"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="10dp"
        android:gravity="center"
        android:text="@string/content"
        android:textAppearance="?android:attr/textAppearanceLarge" />

    <TextView
        android:id="@+id/scan_format_tv"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="20dp"
        android:gravity="center"
        android:text="@string/format"
        android:textAppearance="?android:attr/textAppearanceLarge" />

</RelativeLayout>

my MainActivity.java file (some of code):

               IntentIntegrator scanIntegrator = new IntentIntegrator(this);
                scanIntegrator.setCaptureActivity(AnyOrientationCaptureActivity.class); // without this line of code, the notification bar is invisible - landscape mode | with this line of code the notification bar is visible - portrait mode (I want always on fullscreen mode without bars..)
                scanIntegrator.setBeepEnabled(false);
                scanIntegrator.setOrientationLocked(false);
                scanIntegrator.initiateScan();

notes:
I'm using samsung galaxy s6 with android 6.01 to test... and the last zxing files.. v3.3.0.
Is this a bug? Is something wrong in my code? Is a my phone issue? Again is very welcome some help.

thanks in advance.

![20161012_002239](https://cloud.githubusercontent.com/assets/8027169/19292224/7c47ad4a-9012-11e6-9008-b79a4ff7d964.png)

**Comment by rkistner** [comment]
You can try adding this to the `<activity>` section of the manifest file: 

`android:theme="@android:style/Theme.NoTitleBar.Fullscreen"`

**Comment by cafc3** [comment]
thank you very much!! it works! :-)

but to capture in any orientation isn't only necessary to do this:

on the manifest file:

<activity
        android:name="com.journeyapps.barcodescanner.CaptureActivity"
        android:screenOrientation="fullSensor"
        tools:replace="screenOrientation" />

and in main activity:

IntentIntegrator integrator = new IntentIntegrator(this);
integrator.setOrientationLocked(false);
integrator.initiateScan();

if I put only this code in always capture in landscape mode, could you please help? I need to work in any orientation mode and in continuos mode.. is it possivel?
thanks in advance,

cafc

**Comment by rkistner** [comment]
This example does continuous capture in any orientation:

https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

**Comment by cafc3** [comment]
ok. so, I'm trying to test the sample app to see that working, but now I'm facing a very strange problem... 
When I click in Continuous Scan button it gives me the foollwing error:

 **Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {example.zxing/example.zxing.ContinuousCaptureActivity}; have you declared this activity in your AndroidManifest.xml?**

Have all files from sample folder in my studio.. (include this dependecy on build.gradle file:  compile 'com.journeyapps:zxing-android-embedded:3.4.0' )

but in my manifest file I have declared the activity:

    <activity android:name=".ContinuousCaptureActivity"></activity> 

and I also have tried to put  

    <activity android:name="example.zxing.ContinuousCaptureActivity"></activity>

but it doesn't work at all.. only the first button works (scan barcode) the other buttons gives me the same error... 

What I'm doing wrong? could you please help me?

thanks in advance,

cafc

**Comment by rkistner** [comment]
That probably means there is some build issue - either it cannot find the class file, it cannot find it in the manifest, or there is some mismatch between the names.

**Comment by cafc3** [comment]
yes, you are right. :-) it was a mismatch between some of my app names. thank you very much.

now by the way, I would like to embedded zxing project in my application instead of use link com.journey... in build.gradle, so I have firstly commented this line 

    //compile 'com.journeyapps:zxing-android-embedded:3.4.0'
 
then and I have placed these two folders on my project:
   google
   journeyapps

and finally I made some adjustments in res folder, and in some paths... but only these libraries are not recognized:

    import com.google.zxing.BarcodeFormat;
    import com.google.zxing.DecodeHintType;
    import com.google.zxing.MultiFormatReader;
    import com.google.zxing.ResultPoint;

and 

    import com.google.zxing.client.android.R;

Am I missing something? Could you please, tell me what I need to put this on track... :-)

thanks is advance

cafc

**Comment by rkistner** [comment]
You also need zxing-core. As a gradle dependency, it's `com.google.zxing:core:3.2.1`. For including it directly, look at https://github.com/zxing/zxing.

The `import com.google.zxing.client.android.R` file is automatically generated by the Android build process. If that's not found, it probably means somewhere a package name was changed incorrectly.

In general I recommend just using the gradle dependencies, as the build process is much simpler.

**Comment by cafc3** [comment]
ok. but if I using the gradle dependencies in my app, will it work always on future? or will it be dependent of third party code changes? 

what does this line of code? 

compile 'com.journeyapps:zxing-android-embedded:3.4.0' 

Sorry to bother you. I'm newbie on these matters :-) 

thanks

**Comment by rkistner** [comment]
As long as you include a version number (e.g. 3.4.0), it will stay on that version, and keep on working in the future.

**Comment by cafc3** [comment]
ok. thank you very much for your help!
