### ISSUE TITLE
get the list of barcodes from scan continuous on main activity

### ISSUE THREAD

**Issue by cafc3** [journeyapps/zxing-android-embedded#227]
Hi,

I'm trying get the list of results (barcodes) from scan continuous, but I don't know how I can perform that from the main activity :

in my main activity I have this code:

    public void scanContinuous(View view) {
        Intent intent = new Intent(this, ContinuousCaptureActivity.class);
        startActivity(intent);
    }

So, from here how can I get the list of barcodes scanned? is there some example that I can see to make this? could someone help me please?

thanks in advance,

cafc

**Comment by rkistner** [comment]
See http://stackoverflow.com/a/947560/214837

**Comment by cafc3** [comment]
thanks
