### ISSUE TITLE
make scan area full screen

### ISSUE THREAD

**Issue by riten7** [journeyapps/zxing-android-embedded#228]
#### Description of the problem:
 I want to show full screen for scanning barcode. I mean I dont want to show rectangle box appearing in the middle while scanning..

I am using compile 'com.journeyapps:zxing-android-embedded:3.3.0' in gradle file

in my activity , 
        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureActivity(AnyOrientationCaptureActivity.class);
        //integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
        integrator.setOrientationLocked(false);
        integrator.setBeepEnabled(true);
        integrator.initiateScan();

in AnyOrientationCaptureActivity, 

public class AnyOrientationCaptureActivity extends CaptureActivity {

   @Override
    protected void onCreate(Bundle savedInstanceState) {
       super.onCreate(savedInstanceState);
   }
}

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
You'll need to create a custom Activity to do this. See the options in #152.

**Comment by riten7** [comment]
@rkistner  Is there any other alternatives than you provided ? I mean doing some customization in current code ..

**Comment by riten7** [comment]
@rkistner How can I specify rectangular framing width and height as of device screen dynamically in  code below or or is there any method to do it programatically ?

<com.journeyapps.barcodescanner.BarcodeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_barcode_surface"
        app:zxing_framing_rect_width="250dp"
        app:zxing_framing_rect_height="100dp" />

**Comment by riten7** [comment]
I just did some quick customisation in xml and its working ..

**Comment by shiprasinghal1** [comment]
@riten7 Hey Riten, 
I have seen your post regarding full screen zxing barcode scanner. I as well want to implement same. So can you please help me of customization u made which work for you.

**Comment by oduconge** [comment]
Just set #00000000 as value of app:zxing_viewfinder_mask

    app:zxing_viewfinder_mask="#00000000"

**Comment by chanjungkim** [comment]
Just give 999dp, 999dp

**Comment by gowtham0752** [comment]
@riten7 can u share how to achieve the full scan screen

**Comment by gowtham0752** [comment]
@oduconge @chanjungkim i tried both but not working

**Comment by chanjungkim** [comment]
Just give it big size.
