### ISSUE TITLE
Unable to read HIBC 

### ISSUE THREAD

**Issue by riten7** [journeyapps/zxing-android-embedded#229]
![img_20161027_124827](https://cloud.githubusercontent.com/assets/19606007/19758086/4bb0c4d8-9c46-11e6-9d05-337adb4bb4bb.jpg)
#### Description of the problem:

I m trying to read barcode (HIBC) but its not just not happening. 
I m using library version 3.3.0
Tested on sony xperia z2 and samsung tabs2.
I downloaded latest sample apk and tested but it is also unable to scan HIBC.

Barcode scanner application on play store as u have provided link detects the HIBC.

I have uploaded the image of barcode that i m trying to scan.

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
I'm unable to scan HIBC barcodes with the Barcode Scanner application on the Play Store. It's also not listed in the supported formats here: https://github.com/zxing/zxing#supported-formats. We're only able to scan barcodes that the underlying zxing library supports.

**Comment by riten7** [comment]
i think code 39 includes HIBC bar codes.. code 39 is supported by Barcode scanner application on play store..

**Comment by rkistner** [comment]
If it's Code 39 it should be possible to scan it. The size of the barcode may be an issue in that case - larger 1D barcodes (more stripes) are difficult to scan with a phone's camera, and the scanning can depend a lot on configuration such as the preview resolution, which may be different from the Barcode Scanner application.

**Comment by rkistner** [comment]
Closing this issue for now. If it works in the Barcode Scanner application, we can add support here.
