### ISSUE TITLE
Logcat shows unexplained error (copyAndPost)

### ISSUE THREAD

**Issue by pablokvitca** [journeyapps/zxing-android-embedded#232]
I'm using a DecoratedBarcodeView and continousDecode.

The library send the following error to the app's logcat, on each frame:

E/Camera-JNI: copyAndPost: off=0, size=3110400 msg=10

But everything works correctly. Can this error message be disabled/hidden?

Thank you!

**Comment by rkistner** [comment]
This seems like an issue with the camera drivers on the device, and you will likely see it with other apps using the camera as well. Nothing we can do from the library side.
