### ISSUE TITLE
PNG format image

### ISSUE THREAD

**Issue by jojonarte** [journeyapps/zxing-android-embedded#236]
I hope there is a way to get the image as png instead of jpg

**Comment by rkistner** [comment]
Are you referring to the photo of the barcode as it was captured, or an image generated from the barcode data?

For the photo PNG is a bad choice.

For generating an image from a barcode, you can use this to generate a Bitmap, then convert that to PNG:  https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/BarcodeEncoder.java
