### ISSUE TITLE
How to use ERROR_CORRECTION help me

### ISSUE THREAD

**Issue by xesun** [journeyapps/zxing-android-embedded#237]
**How to use ERROR_CORRECTION help me**

        Intent intent = new Intent();
        intent.putExtra(Intents.Scan.FORMATS, BarcodeFormat.QR_CODE.name());
        intent.putExtra(DecodeHintType.ASSUME_CODE_39_CHECK_DIGIT.name(), true);
        zxing_barcode_scanner.initializeFromIntent(intent);
        zxing_barcode_scanner.getStatusView().setGravity(Gravity.CENTER);

**Comment by rkistner** [comment]
What is the specific issue here?
