### ISSUE TITLE
 Turn on the flash

### ISSUE THREAD

**Issue by guillebalmacedaonline** [journeyapps/zxing-android-embedded#238]
Is there any simple code to turn on the flash using this library?

**Comment by skolarianer** [comment]
I took and modified the code from here:

https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java

**Comment by HazemEngMuh** [comment]
how to applicate this activity please could you explain it

**Comment by guimax** [comment]
You can use key vol + and -. It is a solution i finded.

**Comment by HazemEngMuh** [comment]
@guimax thank you very much
