### ISSUE TITLE
Using an embedded barcode decoder is slower than using an IntentIntegrator.

### ISSUE THREAD

**Issue by rafaeladel** [journeyapps/zxing-android-embedded#239]
Using an embedded scanner like in this [sample code ](https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java) is a little slower than using `IntentIntegrator` so start scanning. By "a little slower" I mean, it takes it more time to detect a QR code for example. May I know what causes the intent way to be faster than using an embedded scanner ?

**Comment by rkistner** [comment]
There are many factors that could influence this, so it's hard to tell exactly.

The most likely factor is the preview resolution used for decoding, which may be larger in the library, which could slow down the process. There is a PR (#245) that adds an option to limit the preview size, but it needs a little more work before it can be merged.
