### ISSUE TITLE
getContent() is null on Samsungs

### ISSUE THREAD

**Issue by devilasd93** [journeyapps/zxing-android-embedded#24]
Hello.
I've big problem, on Samsung getContent() always return null, but when I try on Nexus 4, Nexus 5 all is ok!

This is my call part:

<pre>
IntentIntegrator integrator = new IntentIntegrator(childActiv);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES);
        integrator.setPrompt("Scan a barcode");
        integrator.setResultDisplayDuration(0);
        integrator.setCameraId(0);
        integrator.initiateScan();
</pre>

and in onActivityResult

<pre>
 IntentResult scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent);

                if (scanResult.getContents()!= null){
                    qrCodeValue  =scanResult.getContents();
                    showInfoByQRcode(activity, scanResult.getContents());
                }else{
                   //code...
                }
</pre>

This part always retuns null in scanResult.getContents() on Samsung.
Please help.

**Comment by rkistner** [comment]
Which specific Samsung is this? I've tested on many Samsung devices without any problem.

Do you see any errors in the ADB logs? If the contents are null, it's possible that the scan activity had an error. What is the resultCode that you receive?

Also try without the `integrator.setCameraId(0)` part - it should not be required in most cases.

**Comment by devilasd93** [comment]
In The ADB logs no errors.
I try without integrator.setCameraId(0)
Result code is:0
Request code is:code is:49374.

I test on S3 and S5.

**Comment by rkistner** [comment]
Is this after successfully scanning a barcode? Does it display the result if you use something like `integrator.setResultDisplayDuration(3000)`? I can't remember if that option is actually supported in the library, but it may work.

**Comment by devilasd93** [comment]
Yes this is after successfully scanning.
I tried your way, but it wasn't changed.

**Comment by rkistner** [comment]
Ok, in that case it's quite difficult to debug. Does this same happen with different barcode types, e.g. QR codes and CODE 128?

**Comment by devilasd93** [comment]
Hi.
I've found the problem.
In My manifest file I put android:launchMode="singleInstance" on Activity which calls Bar code Scanner.
When I removed it - Scanner works fine.
Thank you for help.
