### ISSUE TITLE
What are the new features in version 3.4?

### ISSUE THREAD

**Issue by Bajranghudda1** [journeyapps/zxing-android-embedded#242]
I didn't see any new features related topic there, so its good for developers that you provide a list of newly added features, so that any interested can upgrade to newer version.

**Comment by skolarianer** [comment]
https://github.com/journeyapps/zxing-android-embedded/releases

Or what are you looking for?

**Comment by Bajranghudda1** [comment]
Thanks @skolarianer , now i can see them at one place.

**Comment by rkistner** [comment]
Thanks @skolarianer. I also keep a list in [CHANGES.md](https://github.com/journeyapps/zxing-android-embedded/blob/master/CHANGES.md) (should be the same).
