### ISSUE TITLE
Vertical scanner in portrait screen mode

### ISSUE THREAD

**Issue by micsha123** [journeyapps/zxing-android-embedded#243]
I'm using custom scanner through `DecoratedBarcodeView` in my `Fragment `(like in example of Activity Custom Scanner).

Everything works perfect, but if phone in portrait mode - scanner line and detection are horizontal.

Could you help me please, how can I make it vertical (just for giving scanner mode data to scan), if phone will be only in portrait mode (it's locked to portrait mode)?

Like this:
![image](https://cloud.githubusercontent.com/assets/7187364/20642326/ba30b12e-b43e-11e6-92f2-d6436e151f83.png)

Thanks in advance!

**Comment by rkistner** [comment]
There is no built-in way to do this, so you'll have to dig into the source.

There are two parts to this:

1. The UI. This means changing / overriding ViewfinderView.

2. The decoding. For some barcodes (e.g. QR codes), the orientation doesn't matter. For others such as 1D barcodes, the [TRY_HARDER](https://zxing.github.io/zxing/apidocs/com/google/zxing/DecodeHintType.html#TRY_HARDER) hint may cause it to scan in both directions. Alternatively, you can rotate the image before decoding (may require changing the library source). You can do this by creating a custom Decoder and DecoderFactory.

**Comment by micsha123** [comment]
Well, I'm ready to deal with diggin' into source, but I need some help with that.

1) ViewfinderView - which parameters depends on screen orienation (like with and height which we can swap, for example)?

2) I want to decode QR-codes and 1D also, you're right. Thanks for the hint - I'll try it. But I want to rotate scanner because my 1D also vertical - sounds strange but its special product barcode. And I want to give user more comfortable experience - avoid rotation of screen just to read code.
I thought that libraries decoder and viewfinder are connected with camera orientation, isn't it?

**Comment by rkistner** [comment]
For ViewfinderView it's mostly just the red line that will have to be changed to vertical: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/ViewfinderView.java#L160

The result points may also be displayed in the incorrect location if the image is rotated for decoding.

The library always rotates the camera preview to match the current screen orientation. The easiest way to get it to work in vertical is to just rotate it by 90 degrees again, or to use the TRY_HARDER hint to make it decode in both directions.

**Comment by micsha123** [comment]
Well, if I want to rotate camera just to make it scan vertical - which instance should I rotate by 90 degrees?
I tried to work with CameraInstance through the DisplayConfiguration (I swapped width and height counted in previewSized() of StateListener) - but it didn't get any result.

Could you help me, please? Which instance should I rotate? And how (like just rotation(int degrees) or smth else)?

**Comment by rkistner** [comment]
You should not change the camera preview itself - that has to match the current screen orientation. You should rotate the image data just before decoding. If you are modifying the library directly, the easiest will be to change it here:

https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/SourceData.java#L101

Alternatively you can create a custom Decoder and rotate it at this point: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/Decoder.java#L61

**Comment by micsha123** [comment]
Am I right when thinking that if I try to rotate in SourceData perfomance will decrease very much? Or user won't match that?
And I need just to hardcode rotation in constructor, am I right?

Sorry for the silly as f*ck questions))

**Comment by rkistner** [comment]
SourceData normally does the rotation anyway, so it won't make a significant difference.

**Comment by micsha123** [comment]
And one more question. If I rotate sourceData will scanning area increase?
For example - in horizontal mode scanning area has width equal to width of screen. But in landscape mope it equals to screen height.
This is one more realon why I want to set it landscape - get more data for scanner (tested, that in landscape it scans better).

So, will scanning area increase or not?

**Comment by rkistner** [comment]
That's up to you. Rotating will of course swap the width and height, but you can change the crop rectangle however you want.

**Comment by micsha123** [comment]
Well, seems to be the best way - but which lib-classes I need to remake in my project for rotation SourceData? Try to find link between SourceData and BarcodeView

**Comment by dharmita1990** [comment]
I used ` <com.journeyapps.barcodescanner.DecoratedBarcodeView
        android:id="@+id/zxing_barcode_scanner"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_alignParentBottom="true"
        android:layout_below="@+id/txt_scan"
        app:zxing_preview_scaling_strategy="centerCrop"
        app:zxing_use_texture_view="true" />`

In java 
 `barcodeScannerView.decodeContinuous(callback);`
And got it working.

**Comment by rkistner** [comment]
Moving discussion to #211.
