### ISSUE TITLE
QR Code with logo inside it

### ISSUE THREAD

**Issue by dharmita1990** [journeyapps/zxing-android-embedded#247]
I want logo inside qr code and found way  here [https://www.wombatsoftware.de/howto_embed_a_logo_into_a_qr_code_using_zxing_library/](url)
But on  MatrixToImageConfig it is showing "cannot resolve symbol" same with BufferedImage(available in awt).

I solved it using [http://stackoverflow.com/questions/13247701/how-to-add-a-logo-to-qr-code-in-android](url).
Still Is there any other way to put logo using zxing-android-embedded.

**Comment by dharmita1990** [comment]
Done using [http://stackoverflow.com/questions/13247701/how-to-add-a-logo-to-qr-code-in-android](url)

**Comment by rkistner** [comment]
This library is mostly designed for scanning barcodes, not generating them. The stackoverflow post you linked to seems to solve the issue.

**Comment by mustafaberk1996** [comment]
Hi @dharmita1990 
I didn't reach the link that you wrote above. Could you share it with me? Thanks.
