### ISSUE TITLE
Start new activity in continuous scan callback

### ISSUE THREAD

**Issue by kienntk** [journeyapps/zxing-android-embedded#248]
Your library is awesome. But I got a problem when start new activity. My code is following:
```
private BarcodeCallback callback = new BarcodeCallback() {
            Bundle extras = new Bundle();
            extras.putParcelable("CODE", result.getBitmapWithResultPoints(Color.YELLOW));
            Intent i = new Intent(MainActivity.this, DataActivity.class);
            i.putExtras(extras);
            i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            startActivity(i);
}
```
But the app is closed without any error!
Is it possible to start new activity in callback method?

Thank you very much!

**Comment by rkistner** [comment]
It should be possible. Did you check the adb logs for errors?

It will probably be better to not use continuous scanning though. Just scan a single barcode and open the new activity. When you return, you can start scanning another barcode (e.g. in `onResume`).

**Comment by kienntk** [comment]
I checked adb logs and got no error for this. I will change it to single barcode. 
After debugging, I see that when running this code `i.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`, application closed.
