### ISSUE TITLE
Allow setting zxing_use_texture_view & zxing_preview_scaling_strategy values via code

### ISSUE THREAD

**Issue by renatosc** [journeyapps/zxing-android-embedded#249]
First, thanks for creating and sharing the library. It is the most complete and easy to use that I found.

It would be nice if we couldset zxing_use_texture_view and zxing_preview_scaling_strategy values via code also instead of only in the xml.

I can make those changes and create a PR if you think it is valid.

**Comment by rkistner** [comment]
While not documented, you can set it with `BarcodeView#setPreviewScalingStrategy` and `BarcodeView#setUseTextureView` (both defined on the `CameraView` superclass).

**Comment by renatosc** [comment]
Perfect. I missed those functions when looking thru the code. Thanks.
