### ISSUE TITLE
Which gradle  to use ?

### ISSUE THREAD

**Issue by dharmita1990** [journeyapps/zxing-android-embedded#250]
compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'
  compile 'com.google.zxing:core:3.2.1'
OR
compile 'com.journeyapps:zxing-android-embedded:3.4.0'

What is the difference?

**Comment by rkistner** [comment]
Both will have the same effect (if you use the same version for `com.journeyapps:zxing-android-embedded`). The second form automatically adds `com.google.zxing:core:3.2.1` as a transitive dependency, and is recommended.

Is the first form still mentioned somewhere?

**Comment by dharmita1990** [comment]
First form mentioned here :  [https://libraries.io/github/journeyapps/zxing-android-embedded](url)

**Comment by rkistner** [comment]
I'm not sure how libraries.io works, but it seems to contain an outdated copy of the readme.
