### ISSUE TITLE
Make the image height and width larger than the original?

### ISSUE THREAD

**Issue by jojonarte** [journeyapps/zxing-android-embedded#251]
Is there an option to do this? The image returned after taking a code scan is clipped in most occassions.

**Comment by rkistner** [comment]
The returned image is the same one that is used for scanning (edges cropped). There is no option to change the result image currently - pull requests welcome.

**Comment by rkistner** [comment]
In v4.0.2, `BarcodeResult#getBitmap()` returns the entire image instead of the cropped one.
