### ISSUE TITLE
Is is possible to open scanner on fragment, not Activity?

### ISSUE THREAD

**Issue by chanisrunnin** [journeyapps/zxing-android-embedded#252]
#### Description of the problem:
Nice to meet you, I'm Lee Chan from south korea.
Now I'm making App for Barcode Scanner using your wonderful library, thank you very much.

I imported this library's source as a module in our app.
But there are some difficulties when adapting this 'zxing_android_embedded'.

Our app has designed as "One Activity - Many Fragment" structure for many reason. 
But this library works on a Activity base, 
That's the difficulty i had...
First, I have to call scanner at fragment, 
and Second, the called scanner screen has to be a fragment.

Calling CaptureActivity in a fragment has successfully working as you mentioned at other issues, 
but i can't find second question anywhere.

Is it possible to change CaptureActivity to Fragment base?

i'm trying but i stucked at when making under codes.

 IntentIntegrator.forFragment(this)
                    .setCaptureActivity(xxxActivity.class)   <-- this one.
                    .setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES)
                    .setCameraId(0)
                    .setBeepEnabled(false)
                    .setBarcodeImageEnabled(true)
                    .initiateScan();

If i want to change Activity to Fragment, 
then i think i need to modify IntentIntegrator, CaptureManager and so on..
but this way is not easy and can make side effect because i didn't fully understanding this library.

Also, inflate view which has merge tag was impossible, they need to be modify..

Is it possible?
If possible then Could you give me some idea or possible way to make CaptureActivity as a Fragment?

Thank you.

**Which library version are you using?** 3.4.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)** Samsung Galaxy S 3 ~ Samsung Galaxy S 7   (APK 18~23)

**Does the same happen on other devices or an emulator?**
not problem

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
-

**In the case of an error do you have a stack trace or adb logs?**
not error

**Comment by chanisrunnin** [comment]
oh i solved the problem.

.setCaptureActivity() i put my currentActivity of this

**Comment by chanisrunnin** [comment]
I solved problem, so i closed this.
Thank you.

**Comment by ttaraczuk** [comment]
How did you solve it?

**Comment by Taewan-P** [comment]
@chanisrunnin You should at least leave a comment about how you solved it, for the community.
