### ISSUE TITLE
Scan QR code in portraits  mode

### ISSUE THREAD

**Issue by dharmita1990** [journeyapps/zxing-android-embedded#253]
I need to scan QR Code in portraits mode. I used DecoratedBarcodeView for portraits mode but it scans all types of barcode. Is it possible to scan only QR Code.
I tried `Intent intent = new Intent();
        intent.putExtra("SCAN_MODE", "QR_CODE_MODE");
      barcodeScannerView.initializeFromIntent(intent);
  barcodeScannerView.decodeContinuous(callback);`
where barcodeScannerView is object of DecoratedBarcodeView. Is this the correct way to do it?

**Comment by RanjitPati** [comment]
If your are using the same zxing embedded library then you can scan both bar and qr code in potrait mode.
Same code I am using for both👍 

       ```
 IntentIntegrator integrator = new IntentIntegrator(getActivity());
        integrator.setOrientationLocked(false);
        integrator.initiateScan();
```

**Comment by dharmita1990** [comment]
I want custom layout,  Scan preview  should not take entire screen.

**Comment by RanjitPati** [comment]
Then you can customized capture layout by changing inside the library little bit.

**Comment by TheGratefulDev** [comment]
@dharmita1990 I happen to have the steps to use custom capture layout. take a look see if its help

https://github.com/journeyapps/zxing-android-embedded/issues/278#issuecomment-283796911

**Comment by rkistner** [comment]
There are a few examples doing similar things here: https://github.com/journeyapps/zxing-android-embedded/tree/master/sample/src/main/java/example/zxing

**Comment by PassionateDeveloper** [comment]
Please provide this function to scan only QRcode / Barcode / Qr-Barcode both. Thanks

**Comment by Aks-4125** [comment]
`implementation 'com.journeyapps:zxing-android-embedded:3.6.0'`


Add following in AndroidManifest.xml

`  <activity
        android:name="com.journeyapps.barcodescanner.CaptureActivity"
        android:screenOrientation="portrait"
        tools:replace="screenOrientation" />`
