### ISSUE TITLE
Is it Possible to Scan an Existing QR Code Image?

### ISSUE THREAD

**Issue by kocuroglu** [journeyapps/zxing-android-embedded#254]
I want to scan a previously saved qr code image by choosing it from the gallery.

Is there any way to do it with your library? Can you give me some points?

**Comment by rkistner** [comment]
You can use the [zxing:core](https://github.com/zxing/zxing/) Java library directly for this. You just need to convert the source image into a `LuminanceSource` object (e.g. `PlanarYUVLuminanceSource`).

Sample here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/SourceData.java

Then create a `MultiFormatReader`, and decode such as done here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/Decoder.java#L75

**Comment by kocuroglu** [comment]
I have already used this library for scanning with the camera and wanted to use this functionality if possible.

Thank you very much for your response, I'll give it a try.

**Comment by rkistner** [comment]
Note that zxing:core is a dependency of this library, so it's already included. It's what we're using under the hood to do the decoding.
