### ISSUE TITLE
App crashes after returning from scanning

### ISSUE THREAD

**Issue by aaabidunique** [journeyapps/zxing-android-embedded#256]
I don't know what happens but when i create a signed apk and do scanning it crashes after returning from captured screen.It only happens in signed apk not while doing developement (debug apk).

Since it is signed apk i can't get logs.

Please suggest me something.

**Comment by rkistner** [comment]
You can get logs even with a signed APK, just use `adb logcat` directly.

**Comment by aaabidunique** [comment]
Silly me.
Btw problem was with sugar orm.
still solving though.
