### ISSUE TITLE
CustomScannerActivity fo QRCode

### ISSUE THREAD

**Issue by mahermeg17** [journeyapps/zxing-android-embedded#258]
Hi,

I need to make a custom view for my qr code scanner, with some EditText, Button and TextView.
I use the CustomScannerActivity, and adapted the layout as I need.
Now the missing point is to handle QR Code and not Bar code. What I have to change ?

for now, my code is like this : 
`capture = new CaptureManager(this, barcodeScannerView);
capture.initializeFromIntent(getIntent(), `savedInstanceState);`
 
//  capture.decode();
`barcodeScannerView.decodeContinuous(callback);`
  

Thanks,

**Comment by mahermeg17** [comment]
found.
just make bigger zxing_framing_rect

**Comment by rubenwardy** [comment]
How did you archive this in the end? I can't find any documentation for zxing_framing_rect

**Comment by rubenwardy** [comment]
in onCreate:

```java
barcodeView = (BarcodeView) findViewById(R.id.zxing_barcode_surface);
barcodeView.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
        @Override
        public void onLayoutChange(View view, int i, int i1, int i2, int i3, int i4, int i5, int i6, int i7) {
            resizeBarcodeViewer();
        }
});
resizeBarcodeViewer();
```

in same activity:

```java
private void resizeBarcodeViewer() {
    int x = (int)((float)barcodeView.getWidth() * 0.7f);
    int y = (int)((float)barcodeView.getHeight() * 0.7f);
    if (y < x) {
        x = y;
    }
    barcodeView.setFramingRectSize(new Size(x, x));
}
```

hope this helps someone
