### ISSUE TITLE
setZoom and Laser animation

### ISSUE THREAD

**Issue by Charles808** [journeyapps/zxing-android-embedded#259]
Hi, actually this is not an issue.
I'm just confuse in how to use or modify some features.

Curently I'm using  :
com.journeyapps:zxing-android-embedded:3.4.0
tested by LG G3 with marshmallow  
from my gradle app.

I'm using Barcode Callback from ContinuousScan Example to run the scan.

Now, I'm struggling in how to make the camera from ZXing can be zoom in or out.

I'm trying using this code :
        `mCamera=getCameraInstance();`
        `Camera.Parameters` `parameter=mCamera.getParameters();`
        `displayToastShort(getApplicationContext());`
        `int` `zoom=parameter.getMaxZoom();`
       ` if (parameter.isZoomSupported()) {
`            `parameter.setZoom(zoom);
`        } 
        `mCamera.setParameters(parameter);`

The getCamerainstance getting the id of the back camera and open it.

But the code is not working, I suspect maybe the it's not working because the camera already being used by zxing. Weird things is I'm still able to open it using open(int).
Although this is digital zoom, and may not increase accuracy, I'm still want to try it.

The second is, how can I modify/change the laser animation ?

I appreciate any suggestion/idea.

Thank you

Warm regards.

**Comment by Charles808** [comment]
I think the Laser animation can be solved by overriding the onDraw method.
But, I wonder how to do that in ContinuousCaptureActivity example ?

**Comment by Charles808** [comment]
Okay, I found this 
How to set white balance parameters to Camera issue #165 
Which actually almost the same purpose with mine.

Their answer 

> I'm working on some restructuring to expose the Camera instance, but currently you'll need to fork & modify the library for this.

So, any restructuring happening ? It's already since May.

**Comment by Charles808** [comment]
Ok.
I will close this one myself.
 
The solution :
- Fork the source
- Modify the CameraInstance class, change the getCameraManager method to public
- Get the Camera object from getCamera method in CameraManager class
- Voila... freely set the parameter of the camera used by ZXing.

NOTE : 
I don't know what will be the after effect making it public.
But after searching it through the library source. It never used.
At least that is what I found.

Happy stressing !!!

**Comment by baonq-2356** [comment]
@Charles808 Respect, warrior!!
