### ISSUE TITLE
Not able to scan "EAN 13", "CODE 93" and "CODABAR" format correctly

### ISSUE THREAD

**Issue by shwetasingh2117** [journeyapps/zxing-android-embedded#260]
#### Description of the problem:
As per the document provided it should support the "EAN 13", "CODE 93" and "CODABAR" format, but from my app I am not able to scan it properly. Attaching Image for reference.

**EAN 13:**
![image](https://cloud.githubusercontent.com/assets/15977592/21610375/9412304a-d1ed-11e6-9988-8c864fbc9bab.png)

**CODE 93**
![image](https://cloud.githubusercontent.com/assets/15977592/21610399/ba644a44-d1ed-11e6-8e56-e740930cef06.png)

**CODABAR**
![image](https://cloud.githubusercontent.com/assets/15977592/21610408/c9a28822-d1ed-11e6-8710-98a2e5be4f91.png)

**Which library version are you using?** E.g. 3.2.0.
3.2.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
All Phones
**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes this issue also exist in sample project.

**In the case of an error do you have a stack trace or adb logs?**
No

**Comment by rkistner** [comment]
The EAN 13 sample works for me.

I'm also not able to scan the CODE 93 and CODABAR barcodes. Also tested with the [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) app, and getting the same results. You can report the issue on https://github.com/zxing/zxing/issues (the decoder library we're using).

**Comment by khanshahil** [comment]
@rkistner Why was this issue closed? did you get any fix for this issue?

**Comment by rkistner** [comment]
@khanshahil See my last comment on the issue.
