### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by kundanSingh11** [journeyapps/zxing-android-embedded#261]
Scanning not working in front camera how to solve it

**Comment by rkistner** [comment]
It works for me.

Please use the issue template and provide more details on the issue.

**Comment by Ornolfr** [comment]
@rkistner this problems affects me too. The front camera scans barcodes very poorly, almost next to impossible. I'm using the `CameraSettings` class to set the camera to frontal one:
```
CameraSettings cameraSettings = new CameraSettings();
        cameraSettings.setRequestedCameraId(1);
        barcodeView.getBarcodeView().setCameraSettings(cameraSettings);
```
Could you explain what's happening?

**Comment by rkistner** [comment]
@Ornolfr Which types of barcodes are you trying to scan? Front cameras typically have lower resolution, often making it impossible to scan 1D barcodes. QR codes should work in most cases.

**Comment by Ornolfr** [comment]
@rkistner EAN_13 barcodes are my goal. Well, I have a phone with frontal camera 5MP, and it also has this issue.

**Comment by rkistner** [comment]
The other issue with frontal cameras is the focal distance. While most rear cameras have auto-focus, frontal cameras typically have fixed-focus. This means it can't focus on the barcode at a short distance, making scanning very difficult.

**Comment by farislivemaker** [comment]
@rkistner So bar code doesn't work well with front cam, Is there any other library that you can suggest for scanning bar code using front cam.

**Comment by rkistner** [comment]
@farislivemaker It depends a lot on what types of barcodes you are scanning, and what the resolution and focus abilities the camera has. In some cases another lib may help, but in most cases it's simply not feasible to scan the barcode with that camera.

**Comment by farislivemaker** [comment]
@rkistner thank you for your time.

**Comment by hardslk** [comment]
Hello,
I am facing same issue any one find solution?

Thanks in Advance
