### ISSUE TITLE
Unable to close scanner after setting particular time.

### ISSUE THREAD

**Issue by Marcostar** [journeyapps/zxing-android-embedded#262]
#### Description of the problem:

I tried to close scanner like this. But it is not closing the scanner. How can I close the scanner with desired time?

I tried below code but it is not working.

**new IntentIntegrator(MyActivity.this).setTimeout(10).initiateScan();**

**Comment by rkistner** [comment]
The timeout parameter is specified in milliseconds. Try `setTimeout(10000)`.

**Comment by Marcostar** [comment]
@rkistner thanks for replying. But it is not closing scanner yet even after setTimeout(10000)

**Comment by rkistner** [comment]
It works for me in the sample app - see https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L76

**Comment by Marcostar** [comment]
It is not working in my case.

**Comment by Marcostar** [comment]
I used this in my code:

```
                 IntentIntegrator integrator = new IntentIntegrator(QRcodeReadingActivity.this);
                integrator.setOrientationLocked(true);
                integrator.setBeepEnabled(true);
                integrator.setTimeout(8000);
                integrator.initiateScan();
```

**Comment by Marcostar** [comment]
@rkistner my bad. It worked. I was handling timer only at onActivityResult() for M permissions.

**Comment by asifali9145** [comment]
IntentIntegrator is not closed after scaning is completed.
I got  QR result in onActivityResult() butit still shows the QRScaningScreen.

I'm calling initiateScan() method from onCreate()

private void initiateScan() {
         IntentIntegrator integrator = new IntentIntegrator(ScanQRActivity.this);
        //integrator = new IntentIntegrator(this);
        //  IntentIntegrator integrator = new IntentIntegrator();
        //integrator.setPrompt(getResources().getString(R.string.msg_scan_prompt));
        integrator.setPrompt("Scan QR Code");
        integrator.setBarcodeImageEnabled(true);
        integrator.addExtra("SCAN_WIDTH", 200);
        integrator.addExtra("SCAN_HEIGHT", 200);
       // integrator.setTimeout(2000);
        integrator.setBeepEnabled(true);
        integrator.setOrientationLocked(false);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE);
        integrator.initiateScan();
    }

Kindly help me to sort out this problem 
I'm using
  implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
