### ISSUE TITLE
Remove shading from the scanner

### ISSUE THREAD

**Issue by sake1** [journeyapps/zxing-android-embedded#267]
Hi! I'm still new to android programming and I would like to ask:
I want to make a custom scanner that have no "shade" around the middle box of the barcode scanner
What I want my scanner look like this

￼
![22222_scan_small](https://cloud.githubusercontent.com/assets/23013760/22008387/651098e8-dcad-11e6-8aad-40c4ae76ad2a.png)

instad of a shade surrounding the box in the middle, I would like it to be a square surrounding my scanner

Thanks

**Comment by renatosc** [comment]
Just use the BarcodeView class instead of the DecoratedBarcodeView.

**Comment by sake1** [comment]
Is there is any demo source code for this?
I search this project sample source code and I only find 1 way to make a custom scanner by extending CaptureActivity and override method initializeContent which require me to return a DecoratedBarcodeView
(like this one: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/SmallCaptureActivity.java)

Thanks before :)

**Comment by renatosc** [comment]
This is the one I used (just replacing DecoratedBarcodeView with BarcodeView:
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

**Comment by sake1** [comment]
okay, thanks! it finally works :)
