### ISSUE TITLE
why it must destory my activity to start CaptureActivity?

### ISSUE THREAD

**Issue by kuwork** [journeyapps/zxing-android-embedded#269]
#### Description of the problem:
```java
  IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureActivity(CustomCaptureActivity.class);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt("Scan something");
        integrator.setOrientationLocked(true);
        integrator.setBeepEnabled(true);
        integrator.initiateScan();
```
I want to get a code , why it must destory my activity to start CustomCaptureActivity??

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
vivo x5 p , zte nubia z11 min 

**Does the same happen on other devices or an emulator?**
It will happen on the other phones.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**
no special

**Comment by renatosc** [comment]
IntentIntegrator was made to make it easier for use to have a scanner with very few lines of codes. It creates its own Activity and when finds a qr/barcode, it will return back to your Activity.

If you want to just add the scanner in your current Activity, take a look on the [Continuos Scanner example](https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java) and copy the required code to your Activity.

**Comment by kuwork** [comment]
I find it's not your problem in this project , because I put it int the  [Small](https://github.com/wequick/Small) frame, it can't deal with the Flags for now.
