### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method

### ISSUE THREAD

**Issue by pnevalle** [journeyapps/zxing-android-embedded#273]
#### Description of the problem:
NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.a.e.a(com.journeyapps.barcodescanner.a.n)' on a null object reference
  Module "com.journeyapps.barcodescanner.g", line 179, in handleMessage
  Module "com.journeyapps.barcodescanner.d", line 53, in b
  Module "com.journeyapps.barcodescanner.d", line 387, in b
  Module "com.journeyapps.barcodescanner.d", line 436, in k
  Module "com.journeyapps.barcodescanner.d", line 649, in a
...
(6 additional frame(s) were not displayed)

**Which library version are you using?** E.g. 3.2.0.
3.1.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.a.e.a(com.journeyapps.barcodescanner.a.n)' on a null object reference
  Module "com.journeyapps.barcodescanner.g", line 179, in handleMessage
  Module "com.journeyapps.barcodescanner.d", line 53, in b
  Module "com.journeyapps.barcodescanner.d", line 387, in b
  Module "com.journeyapps.barcodescanner.d", line 436, in k
  Module "com.journeyapps.barcodescanner.d", line 649, in a
...
(6 additional frame(s) were not displayed)

**Comment by rkistner** [comment]
@pnevalle I'll need a non-obfuscated stack trace to debug this.
