### ISSUE TITLE
Returning to the incorrect caller activity

### ISSUE THREAD

**Issue by hatpick** [journeyapps/zxing-android-embedded#275]
Lib version I'm using **3.4.0**
On an actual device **Pixel API 25 7.0.2**, **Galaxy S5 API 19**, **Moto X API 21**

The user is in Activity A, then s/he goes to Activity B, where s/he may initiate the barcode scanner. When it finds the barcode and gets back to the app, it goes to Activity A instead of B, is there any particular reason you have added the following flags to the intent inside ```createScanIntent``` method:

```
intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
intentScan.addFlags(Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET);
```

and in Manifest:
```android:clearTaskOnLaunch```

Although, I tried to call ```createScanIntent``` and clear the flags using ```setFlags(0)```, it still returns to Activity A and not B who is waiting for the result.
(Obviously, Activity B is not the root if its task, but I don't want it to be cleared from the back stack)

**Comment by rkistner** [comment]
Those flags are legacy from the initial port from the Barcode Scanner app. That said, I haven't seen that issue in any other apps. Could there be something in your app that closes Activity A? Otherwise I'll need a small sample project that reproduces the issue to help debugging.

**Comment by rkistner** [comment]
Needs more info to debug.

**Comment by gamengamenut** [comment]
I have the same issue.

Activity A runs Zxing A to scan a code.
code is used for processing and then app goes to Activity B.
Activity B runs Zxing B to read another code.
Zxing B returns to Activity A (which i have closed, thus app crashes being unable to find Activity A)

Implementation 

    public void scanOne() {
        // get the login details for checking

        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureActivity(CaptureActivity.class);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(" ");
        integrator.addExtra("CONTINEUOUS_SCAN", true);
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.initiateScan();
    }

Also, i have onActvityResult for both.
    
     public void onActivityResult(int requestCode, int resultCode, Intent intent) {
        //retrieve scan result
        IntentResult scanningResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent);

        // if we have a result, content is the serial number itself
        // name is the type of barcode
        String codeContent = scanningResult.getContents();
            //UID = codeContent;
        // Process the barcode here
        // below code assumes the role is in the QR code
        if (scanningResult != null) {

            RLOPath();


                //Intent intentito = new Intent(MainActivity.this,MainActivityAlt.class);
                //intentito.putExtra("parent","main");
                //startActivity(intentito);
                //this.finish();


        } else {
        // here when no scan intel
    }
}

Ignore any syntax errors as i copied it here and deleted some. I don't understand why it doesnt return to return to it's original calling activity.
