### ISSUE TITLE
Error:Execution failed for task ':test1:transformClassesWithDexForDebug'. Multiple dex files define Lcom/google/zxing/client/android/camera/CameraConfigurationUtils;

### ISSUE THREAD

**Issue by withgogo** [journeyapps/zxing-android-embedded#276]
#### Description of the problem:
I just updated my AS to 2.2.3. However, when I was building an apk, this error came out:

> Error:Execution failed for task ':test1:transformClassesWithDexForDebug'. Multiple dex files define Lcom/google/zxing/client/android/camera/CameraConfigurationUtils;

I've checked my dependencies and libraries. There is no duplicate dependencies and libs. This is what in gradle:

> dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    testCompile 'junit:junit:4.12'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.journeyapps:zxing-android-embedded:3.4.0'
}

How can I fix this problem?
 

**Which library version are you using?** E.g. 3.2.0.
com.journeyapps:zxing-android-embedded:3.4.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Android SDK is above 5.0,(API 21).

**Comment by rkistner** [comment]
This is an issue somewhere in the build system. Try doing a `./gradlew clean` and then build again. If that doesn't solve the issue there's probably a configuration issue somewhere.
