### ISSUE TITLE
[Fragment] - Good Initialization, then close...

### ISSUE THREAD

**Issue by MayeuldP** [journeyapps/zxing-android-embedded#277]
Alright, good evening every one :) ,

**Which library version are you using?** E.g. 3.4.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)** Huawei Honor 5C

**Does the same happen on other devices or an emulator?** Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?** No

**In the case of an error do you have a stack trace or adb logs?** Yes

--------------------------------

I'm using `    compile 'com.android.support:appcompat-v7:25.0.0'`

I'm currrently trying to using your app, I'm using it inside a fragment, I kind of copied pasted your sample code in "Sample of scanning from a Fragment". 
And so I tried at first the sample project on my phone, it works well, but now if I want to integrate it on my app, it doesn't work anymore, maybe you can tell me if I forget something... 

So build works well, and when I'm trying to scan something, the windows of the scan show up during few miliseconds and then the app close/crash.

If we look about the log, the initialization looks good because I get all this, like with your sample code : 
`E/Camera: Camera new cameraInitNormal:0
I/CameraManager: Camera Display Orientation: 0
[...]
I/CenterCropStrategy: Preview: 1920x1080; Scaled: 1920x1080; Want: 1794x1080
I/CameraPreview: Starting preview
I/AutoFocusManager: Current focus mode 'auto'; use auto focus? true`

and it finish with this `Sending signal. PID: 12484 SIG: 9 Application terminated.` (app is close at this moment). I don't get any message of work  crash like "has stop to works", just the app close and show the first view of the app, like if it was relaunching the app. But the log stopped in Android Studio, so well it kind of crashed... 

---------------------------------------

Here is my .java file : 

`public class ScanFragment extends Fragment implements IScanView, View.OnClickListener, TabLayout.OnTabSelectedListener {

    private String toast;
    private ViewPager viewPager;
    IScanPresenter ScanPresenter;

    public ScanFragment()
    {}

    @Override
    public void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        ScanPresenter = new ScanPresenter(getActivity(), this);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_scanner, container, false);
        TextView scan = (TextView) view.findViewById(R.id.scannez);
        scan.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                scanFromFragment();
            }
        });
        return view;
    }

    public void scanFromFragment() {
        IntentIntegrator.forSupportFragment(this).initiateScan();
    }

    private void displayToast() {
        if(getActivity() != null && toast != null) {
            Toast.makeText(getActivity(), toast, Toast.LENGTH_LONG).show();
            toast = null;
        }
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            if(result.getContents() == null) {
                toast = "Cancelled from fragment";
            } else {
                toast = "Scanned from fragment: " + result.getContents();
            }

            // At this point we may or may not have a reference to the activity
            displayToast();
        }
    }

    @Override
    public void onClick(View view) {
        Log.d("Click", "Click");}

    @Override
    public void onSetProgressBarVisibility(int Visibility) {}

    @Override
    public void onTabSelected(TabLayout.Tab tab) {
        viewPager.setCurrentItem(tab.getPosition());
    }
    @Override
    public void onTabUnselected(TabLayout.Tab tab) {

    }
    @Override
    public void onTabReselected(TabLayout.Tab tab) {

    }
}`

--------------------------------

Well so I don't really know from where it can come from... The only difference with your sample code, is that your Fragment's class is inside a basic class MainActivity which's extending `AppCompatActivity` ... Does the crash can come from there ? If you need any more informations just tell me, I tried to be as much clear as possible :/

**Comment by rkistner** [comment]
I don't see any obvious issues here. Perhaps there's something in the containing Activity that could cause a crash?

**Comment by MayeuldP** [comment]
Hm I can't say what, I tried to use the scanner on an activity on the same app, and it worked well, so it's definitly a problem of fragment. I'm launching my fragment from the MainActivity using this method `fragment = (Fragment) fragmentClass.newInstance();` compare to you...  
I have no idea why the activity could make it crash... :/

**Comment by MayeuldP** [comment]
Hey,
finally I found the error. Thank's for help !
