### ISSUE TITLE
[Layout] How can set scan barcode area align top not center?

### ISSUE THREAD

**Issue by ChouCC** [journeyapps/zxing-android-embedded#278]
#### Description of the problem:
I want to set scan barcode area on top not center, how can I do?
thanks.

**Which library version are you using?** E.g. 3.4.0

**Which phone/tablet are you using, and which Android version does it run? Zenfone 6 
  Android 5.0)**

**Comment by TheGratefulDev** [comment]
you may want to create your own **captureActivity**

first 
when you initiateScan, you do something like this
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L65

andt then you create your own captureActivity like this example, 
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java

this is where the custom part happen
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java#L26

**Comment by ChouCC** [comment]
@TheGratefulDev 
Thanks for your reply.
But what I mean is like picture.
I change scan barcode area is center to top.
I find where I can do is in function calculateFramingRect of CameraPreview.
Thanks again for your reply.

![screenshot](https://cloud.githubusercontent.com/assets/15353385/23536116/cd7dc6a8-fffd-11e6-940a-89cc3890e1c3.jpg)

**Comment by ninhkobietnau** [comment]
> @TheGratefulDev Thanks for your response. But what I mean is like picture. I change scan barcode area is center to top. I find where I can do is in function calculateFramingRect of CameraPreview. Thanks again for your response.
> 
> ![screenshot](https://cloud.githubusercontent.com/assets/15353385/23536116/cd7dc6a8-fffd-11e6-940a-89cc3890e1c3.jpg)

Hello ChouCC, I just wanna know what have u change in calculateFramingRect function to have scan area like this
