### ISSUE TITLE
I cant change the RequestCode

### ISSUE THREAD

**Issue by Nibot1** [journeyapps/zxing-android-embedded#280]
I defined the libary in build.gradle and imported it in my application and when i try to change the requestcode androidstudio says that it is final and can't be changed.
Pls help me.
I am using the libary 3.2.0

**Comment by renatosc** [comment]
Yes, that is expected. The versions available via gradle don't allow the REQUEST_CODE to be changed. The latest version here on github allows you to change it, so I would suggest you to download and import the library manually.

**Comment by Nibot1** [comment]
How do i do that ?

**Comment by rkistner** [comment]
Since v3.5.0, REQUEST_CODE is not final anymore.
