### ISSUE TITLE
Gradle 3.3. issue 

### ISSUE THREAD

**Issue by oskar9** [journeyapps/zxing-android-embedded#282]
When I update Android Gradle plugin to version 2.3.0 and Gradle to version 3.3, gives me this:
Error:The "android" command is no longer included in the SDK. Any references to it (e.g. by third-party plugins) should be removed.

![gradle](https://cloud.githubusercontent.com/assets/5046473/23797517/8bd8aada-05a0-11e7-99e6-0aa1e9e804e9.JPG)

**Comment by rkistner** [comment]
Most likely an issue with the android-sdk-manager plugin that was used. This has been removed now (on master), and the tests pass with Gradle 3.4.1. So it should be fixed with the next release.

**Comment by rkistner** [comment]
Fix released in v3.5.0.
