### ISSUE TITLE
how to define different request in same activity?

### ISSUE THREAD

**Issue by mawenge** [journeyapps/zxing-android-embedded#284]
In one activity, I have to scan two or more different image using a same scan activity,  but I cannot distinguish those results returned, could I send request with requestCode so I can get the results by request code?

**Comment by rkistner** [comment]
Yes, you can do it with some workarounds.

1. Instead of using `integrator.initiateScan()`, use `activity.startActivityForResult(integrator.createScanIntent(), YOUR_REQUEST_CODE)`.

2. Use an `onActivityResult` method looking something like this:

```java
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if(requestCode == FIRST_REQUEST_CODE) {
        IntentResult result = IntentIntegrator.parseActivityResult(IntentIntegrator.REQUEST_CODE, resultCode, data);
        // Do something with the result
    } else if(requestCode == SECOND_REQUEST_CODE) {
        IntentResult result = IntentIntegrator.parseActivityResult(IntentIntegrator.REQUEST_CODE, resultCode, data);
        // Do something with the result
    } else {
        super.onActivityResult(requestCode, resultCode, data);
    }
}
```

**Comment by mawenge** [comment]
thanks a lot, the solution is great

**Comment by Betul06** [comment]
Hello I am trying to take a picture from camera and show them in the file. OnActivityResult part is I am writing does take the picture but doesnot load to camera device and cant show it in the file, and application close down. Could anyone help?
Thanks

            mButtonChooseImage=findViewById(R.id.button_choose_image);
            mButtonUpload=findViewById(R.id.button_upload);
            mTextViewShowUploads=findViewById(R.id.text_view_show_uploads);
            mEditTextFileName=findViewById(R.id.edit_text_file_name);
            mImageView=findViewById(R.id.image_view);
            mProgressBar=findViewById(R.id.progress_bar);
            mButtonChooseImage.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    openFileChooser();
                }
            });
            mButtonUpload.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {

                }
            });
            mTextViewShowUploads.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {

                }
            });

        }
        private void openFileChooser(){
            Intent intent=new Intent();
            intent.setType("image/*");
            intent.setAction(Intent.ACTION_GET_CONTENT);
            startActivityForResult(intent,PICK_IMAGE_REQUEST);

        }
        protected void onActivityResult (int requestCode,int resultCode,Intent data){
            super.onActivityResult(requestCode,resultCode,data);
            if(requestCode==PICK_IMAGE_REQUEST&&resultCode==RESULT_OK&&data!=null&&data.getData()!=null){
                mImageUri=data.getData();
                Picasso.with(this).load(mImageUri).into(mImageView);
            }
        }

    }


      private void openFileChooser(){
            Intent intent=new Intent();
            intent.setType("image/*");
            intent.setAction(Intent.ACTION_GET_CONTENT);
            startActivityForResult(intent,PICK_IMAGE_REQUEST);

        }
        protected void onActivityResult (int requestCode,int resultCode,Intent data){
            super.onActivityResult(requestCode,resultCode,data);

            if (requestCode==CAMERA_REQUEST_CODE&&resultCode == RESULT_OK && data != null)

            {
                Bitmap bitmap=(Bitmap)data.getExtras().get("data");
                mImageView.setImageBitmap(bitmap);
            }
            else if (requestCode==PICK_IMAGE_REQUEST&&resultCode==RESULT_OK&&data!=null &&data.getData()!=null){
                mImageUri=data.getData();
                Picasso.with(this).load(mImageUri).into(mImageView);
            }
        }

**Comment by rkistner** [comment]
@Betul06 Your question seems unrelated to this project - StackOverflow may be a better place to ask for help.

**Comment by starclock** [comment]
Hello, I am having problems with the result of this function, I want to select three photos in the same window, for each photo you select, one thing they share is "onActivityResult", I can't point the individual request to differentiate who called the function.
