### ISSUE TITLE
Getting different results from the same barcode

### ISSUE THREAD

**Issue by kayace** [journeyapps/zxing-android-embedded#285]
#### Description of the problem:
I'm getting different results from scanning in CustomScannerActivity and ContinuousCaptureActivity on one barcode.
Here is the result photo 
![fotograf](https://cloud.githubusercontent.com/assets/11633075/24323707/a8ea18e6-1182-11e7-8613-1acf81dd081a.JPG)

**Which library version are you using?** E.g. 3.2.0.
 'com.journeyapps:zxing-android-embedded:3.4.0'
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
 Lenovo P70-A , Android 5.1
**Does the same happen on other devices or an emulator?**
I have only 1 device
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
I used the "sample" project
**In the case of an error do you have a stack trace or adb logs?**
no

**Comment by rkistner** [comment]
This is unfortunately a common problem with EAN barcodes. I'm not sure how much can be improved in the algorithm, and how much is an inherent issue with the barcode type. Either way, if you can reproduce the issue with the standard [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) application, you can report the issue directly in the decoding library: https://github.com/zxing/zxing/issues
