### ISSUE TITLE
Limit only PDF417 and QR in ContinuousCaptureActivity

### ISSUE THREAD

**Issue by TheGratefulDev** [journeyapps/zxing-android-embedded#286]
I am trying to limit the Continuous Capture Activity to scan only PDF417 and QR.

I know how to set it up with Custom IntentIntegrator.

But I don't know how to do it in Continuous Capture Activity

**Comment by rkistner** [comment]
You need to create a new `MultiFormatReader`, and set it as is done here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/DecoratedBarcodeView.java#L154
