### ISSUE TITLE
Stopped reading barcodes after updating to API 23

### ISSUE THREAD

**Issue by lennycode** [journeyapps/zxing-android-embedded#289]
#### Description of the problem:

I am testing this library for an app. Originally it was working fine under API 19 and 21, then after updating for my phone (Android M - 23 I believe - because I wanted quick run), the scanner will now "stare" and "blink" at barcodes and not return back to the  `onActivityResult()` callback. Barcodes are nice and clear on the display. Again, everything worked fine prior. There are no errors but I am attaching the log, if it can be helpful. The zx barcode scanner app works. I have other zx apps and they work fine, wanted to try something more lightweight.

04-06 18:07:30.825 15990-20199/com.example.lenny.testapp D/CameraInstance: Opening camera
04-06 18:07:30.827 15990-15990/com.example.lenny.testapp I/SensorManager: registerListenerImpl() [Sensor: LGE Accelerometer, Rate: 200000, SensorEventListener: android.view.OrientationEventListener$SensorEventListenerImpl@75ae631] by android.view.OrientationEventListener.enable():93
04-06 18:07:30.838 15990-15990/com.example.lenny.testapp D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@141e484
04-06 18:07:30.857 15990-16495/com.example.lenny.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9749dd30
04-06 18:07:30.857 15990-16495/com.example.lenny.testapp D/OpenGLRenderer: endAllActiveAnimators on 0x98c3c480 (RippleDrawable) with handle 0x8e13fb80
04-06 18:07:30.920 15990-15990/com.example.lenny.testapp V/ViewRootImpl: Contents drawing finished : com.example.lenny.testapp/com.journeyapps.barcodescanner.CaptureActivity
04-06 18:07:30.931 15990-15990/com.example.lenny.testapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@8e53dbb time:69072966
04-06 18:07:31.254 15990-20199/com.example.lenny.testapp D/CameraInstance: Configuring camera
04-06 18:07:31.254 15990-20199/com.example.lenny.testapp I/CameraManager: Camera Display Orientation: 0
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraManager: Initial camera parameters: ae-bracket-hdr=Off;ae-bracket-hdr-values=Off,AE-Bracket;af-bracket=af-bracket-off;af-bracket-values=af-bracket-off,af-bracket-on;antibanding=auto;antibanding-values=off,60hz,50hz,auto;auto-exposure=center-weighted;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-exposure-values=frame-average,center-weighted,spot-metering,smart-metering,center-weighted,spot-metering-adv,center-weighted-adv;auto-hdr-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;avtimer=disable;backlight-condition=low;brightness-step=1;camera-mode=0;capture-burst-exposures=0,10,-9;contrast=5;contrast-step=1;cto-face-detection=on;cto-face-detection-height=480;cto-face-detection-illuminance=0;cto-face-detection-multidirection=0;cto-face-detection-width=640;denoise=denoise-off;denoise-values=denoise-off,denoise-on;dis=disable;dis-values=enable,disable;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon;exposure-compensation=0;exposure-compensation-step=0.166667;f-number=2.4;face-detection=off;face-detection-values=off,on;flash-mode=off;flash-mode-values=off,auto,on,torch;flash-status=off;flip-mode-values=off,flip-v,flip-h,flip-vh;focal-length=3.97;focus-areas=(0, 0, 0, 0, 0);focus-distances=0.100000,0.150000,0.170000;focus-mode=auto;focus-mode-values=auto,infinity,macro,continuous-video,continuous-picture,mw_continuous-picture;hfr-size-values=;histogram=disable;histogram-values=enable,disable;horizontal-view-angle=60.8;internal-restart=true;iso=auto;iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,auto;jpeg-quality=97;jpeg-thumbnail-height=288;jpeg-thumbnail-quality=85;jpeg-thumbnail-size-values=512x288,480x288,256x154,432x288,384x240,320x320,320x240,176x144,0x0;jpeg-thumbnail-width=512;lensshade=enable;lensshade-values=enable,disable;lge-camera=0;long-shot=off;longshot-supported=true;luma-adaptation=3;luminance-condition=high;luminance-condition-for-video=high;max-brightness=6;max-contrast=10;max-exposure-compensation=12;max-exposure-time=2000000;max-focus-pos-index=60;max-num-detected-faces-hw=5;max-num-detected-faces-sw=5;max-num-focus-areas=1;max-num-metering-areas=5;max-saturation=10;max-sce-factor=100;max-sharpness=36;max-wb-cct=8000;max-zoom=90;mce=enable;mce-values=enable,disable;metering-areas=(0, 0, 0, 0, 0);min-brightness=0;min-contrast=0;min-exposure-compensation=-12;min-exposure-time=200;min-focus-pos-dac=1023;min-focus-pos-index=40;min-saturation=0;min-sce-factor=-100;min-sharpness=0;min-wb-cct=2000;multi-window-focus-area=(-280,-280,0,0,1),(-140,-420,140,-140,1),(0,-280,280,0,1),(-420,-140,-140,140,1),(-140,-140,140,140,1),(140,-140,420,140,1),(-280,0,0,280,1),(-140,140,140,420,1),(0,0,280,280,1),(-220,-220,220,220,1);multi-window-focus-zone-touch=(720,720,1000,1000,1),(860,580,1140,860,1),(1000,720,1280,1000,1),(580,860,860,1140,1),(860,860,1140,1140,1),(1140,860,1420,1140,1),(720,1000,1000,1420,1),(860,1140,1140,1420,1),(1000,1000,1280,1280,1);num-snaps-per-shutter=1;picture-format=jpeg;picture-format-values=jpeg,bayer-mipi-10bggr,bayer-ideal-qcom-10bggr,bayer-qcom-10bggr,yuv422sp;picture-size=1280x960;picture-size-values=4160x3120,4160x2340,4000x3000,3264x2448,3264x1840,3200x2400,2592x1944,2560x1920,2560x1600,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x768,1280x720,1024x768,800x600,800x480,720x480,640x480,352x288,320x240,176x144;preferred-preview-size-for-video=1920x1080;preview-flip=off;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,nv12-venus;preview-fps-range=5000,30000;preview-fps-range-values=(15000,15000),(5000,30000),(10000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-off=0;preview-size=1280x960;preview-size-values=2560x1440,1920x1440,1920x1080,1776x1080,1600x1200,1440x1080,1280x960,1280x800,1280x720,960x720,864x480,880x720,848x480,800x480,768x432,720x480,640x480,576x432,480x320,384x288,352x288,320x240,240x160,176x144;psv
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Requesting focus mode value from among: [auto]
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Supported focus mode values: [auto, infinity, macro, continuous-video, continuous-picture, mw_continuous-picture]
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Can set focus mode to: auto
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Focus mode already set to auto
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Requesting flash mode value from among: [off]
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Supported flash mode values: [off, auto, on, torch]
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Can set flash mode to: off
04-06 18:07:31.258 15990-20199/com.example.lenny.testapp I/CameraConfiguration: Flash mode already set to off
04-06 18:07:31.265 15990-20199/com.example.lenny.testapp I/PreviewScalingStrategy: Viewfinder size: 2392x1440
04-06 18:07:31.266 15990-20199/com.example.lenny.testapp I/PreviewScalingStrategy: Preview in order of preference: [2560x1440, 1776x1080, 1920x1080, 1920x1440, 1600x1200, 1280x800, 1440x1080, 1280x720, 1280x960, 800x480, 960x720, 848x480, 864x480, 768x432, 720x480, 880x720, 640x480, 576x432, 480x320, 384x288, 352x288, 320x240, 240x160, 176x144]
04-06 18:07:31.266 15990-20199/com.example.lenny.testapp I/CameraManager: Final camera parameters: ae-bracket-hdr=Off;ae-bracket-hdr-values=Off,AE-Bracket;af-bracket=af-bracket-off;af-bracket-values=af-bracket-off,af-bracket-on;antibanding=auto;antibanding-values=off,60hz,50hz,auto;auto-exposure=center-weighted;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-exposure-values=frame-average,center-weighted,spot-metering,smart-metering,center-weighted,spot-metering-adv,center-weighted-adv;auto-hdr-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;avtimer=disable;backlight-condition=low;brightness-step=1;camera-mode=0;capture-burst-exposures=0,10,-9;contrast=5;contrast-step=1;cto-face-detection=on;cto-face-detection-height=480;cto-face-detection-illuminance=0;cto-face-detection-multidirection=0;cto-face-detection-width=640;denoise=denoise-off;denoise-values=denoise-off,denoise-on;dis=disable;dis-values=enable,disable;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon;exposure-compensation=0;exposure-compensation-step=0.166667;f-number=2.4;face-detection=off;face-detection-values=off,on;flash-mode=off;flash-mode-values=off,auto,on,torch;flash-status=off;flip-mode-values=off,flip-v,flip-h,flip-vh;focal-length=3.97;focus-areas=(0, 0, 0, 0, 0);focus-distances=0.100000,0.150000,0.170000;focus-mode=auto;focus-mode-values=auto,infinity,macro,continuous-video,continuous-picture,mw_continuous-picture;hfr-size-values=;histogram=disable;histogram-values=enable,disable;horizontal-view-angle=60.8;internal-restart=true;iso=auto;iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,auto;jpeg-quality=97;jpeg-thumbnail-height=288;jpeg-thumbnail-quality=85;jpeg-thumbnail-size-values=512x288,480x288,256x154,432x288,384x240,320x320,320x240,176x144,0x0;jpeg-thumbnail-width=512;lensshade=enable;lensshade-values=enable,disable;lge-camera=0;long-shot=off;longshot-supported=true;luma-adaptation=3;luminance-condition=high;luminance-condition-for-video=high;max-brightness=6;max-contrast=10;max-exposure-compensation=12;max-exposure-time=2000000;max-focus-pos-index=60;max-num-detected-faces-hw=5;max-num-detected-faces-sw=5;max-num-focus-areas=1;max-num-metering-areas=5;max-saturation=10;max-sce-factor=100;max-sharpness=36;max-wb-cct=8000;max-zoom=90;mce=enable;mce-values=enable,disable;metering-areas=(0, 0, 0, 0, 0);min-brightness=0;min-contrast=0;min-exposure-compensation=-12;min-exposure-time=200;min-focus-pos-dac=1023;min-focus-pos-index=40;min-saturation=0;min-sce-factor=-100;min-sharpness=0;min-wb-cct=2000;multi-window-focus-area=(-280,-280,0,0,1),(-140,-420,140,-140,1),(0,-280,280,0,1),(-420,-140,-140,140,1),(-140,-140,140,140,1),(140,-140,420,140,1),(-280,0,0,280,1),(-140,140,140,420,1),(0,0,280,280,1),(-220,-220,220,220,1);multi-window-focus-zone-touch=(720,720,1000,1000,1),(860,580,1140,860,1),(1000,720,1280,1000,1),(580,860,860,1140,1),(860,860,1140,1140,1),(1140,860,1420,1140,1),(720,1000,1000,1420,1),(860,1140,1140,1420,1),(1000,1000,1280,1280,1);num-snaps-per-shutter=1;picture-format=jpeg;picture-format-values=jpeg,bayer-mipi-10bggr,bayer-ideal-qcom-10bggr,bayer-qcom-10bggr,yuv422sp;picture-size=1280x960;picture-size-values=4160x3120,4160x2340,4000x3000,3264x2448,3264x1840,3200x2400,2592x1944,2560x1920,2560x1600,2048x1536,1920x1080,1600x1200,1440x1080,1280x960,1280x768,1280x720,1024x768,800x600,800x480,720x480,640x480,352x288,320x240,176x144;preferred-preview-size-for-video=1920x1080;preview-flip=off;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,nv12-venus;preview-fps-range=5000,30000;preview-fps-range-values=(15000,15000),(5000,30000),(10000,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-off=0;preview-size-values=2560x1440,1920x1440,1920x1080,1776x1080,1600x1200,1440x1080,1280x960,1280x800,1280x720,960x720,864x480,880x720,848x480,800x480,768x432,720x480,640x480,576x432,480x320,384x288,352x288,320x240,240x160,176x144;psvt-mode=0;qc-camera-featu
04-06 18:07:31.273 15990-15990/com.example.lenny.testapp I/CenterCropStrategy: Preview: 2560x1440; Scaled: 2560x1440; Want: 2392x1440
04-06 18:07:31.298 15990-15990/com.example.lenny.testapp I/CameraPreview: Starting preview
04-06 18:07:31.298 15990-20199/com.example.lenny.testapp D/CameraInstance: Starting preview
04-06 18:07:31.367 15990-20199/com.example.lenny.testapp I/AutoFocusManager: Current focus mode 'auto'; use auto focus? true
04-06 18:08:20.388 15990-15998/com.example.lenny.testapp W/art: Suspending all threads took: 5.564ms
04-06 18:08:35.024 15990-15990/com.example.lenny.testapp I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=69137049, downTime=69137049, deviceId=-1, source=0x101 } to com.android.internal.policy.PhoneWindow$DecorView{ee238a2 V.E...... R....... 0,0-2392,1440}
04-06 18:08:35.035 15990-15990/com.example.lenny.testapp I/AudioManagerEx: AudioManagerEx created
04-06 18:08:35.161 15990-15990/com.example.lenny.testapp I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=69137188, downTime=69137049, deviceId=-1, source=0x101 } to com.android.internal.policy.PhoneWindow$DecorView{ee238a2 V.E...... R....... 0,0-2392,1440}
04-06 18:08:35.173 15990-15990/com.example.lenny.testapp D/CameraPreview: pause()
04-06 18:08:35.173 15990-20199/com.example.lenny.testapp D/CameraInstance: Closing camera
04-06 18:08:35.174 15990-15990/com.example.lenny.testapp I/SensorManager: removeAllSensors() [Sensor: LGE Accelerometer] by android.view.OrientationEventListener.disable():108
04-06 18:08:35.531 15990-15990/com.example.lenny.testapp D/ViewAO: isWindowSplit called.. by aspectj
04-06 18:08:35.692 15990-16495/com.example.lenny.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9749c1b0
04-06 18:08:35.702 15990-15990/com.example.lenny.testapp V/ViewRootImpl: Contents drawing finished : Toast

**Which library version are you using?** E.g. 3.2.0.
com.journeyapps:zxing-android-embedded:3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
LG G3/ Android M

**Does the same happen on other devices or an emulator?**
Didn't test.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
I am using the sample code as pn the github page . I may try a fresh app.
```
 public void onClick(View v) {
                new IntentIntegrator(MainActivity.this).initiateScan();
            }
```

**In the case of an error do you have a stack trace or adb logs?**
See above

Barcodes work fine with that app.

**Comment by akiller** [comment]
I've also been having this problem both on an LG G2 and Motorola G3. Sometimes the app works fine and sometimes it just sits there forever trying to scan barcodes whilst scanning in continuous mode.

The ZXing barcode scanner works fine.

**Comment by lennycode** [comment]
I did some more testing and the scanning is very unpredictable. I've also tried the dm77 library and in that case it just freezes (you can set a breakpoint in the the result, but otherwise unusable). 

What works for me is:
1 -Google Vision, works perfectly in any direction, scans in milliseconds. Con is a large library is needed and if you are low on space it may not install. They also had some bad issues in the past, but the library seems stable.


2 -A pure port of ZXing - I believe this brings the intent into the app so they don't need to download barcode. 
an example is:
https://github.com/tarun0/ZXing-Standalone-library
compile 'com.tarun0.zxing-standalone:zxing-standalone:1.0.0'
You can use that as is or follow directions to build yourself. You can also customize the scan activity to your liking.

**Comment by akiller** [comment]
Interesting, I wasn't aware of those alternatives.

Earlier I tried downloading and compiling this project myself and running the sample app it comes with. Everything works fine in continuous mode there but not in my app using the same library version. There is a chance I broke my app of course, I'm still investigating :).

**Comment by lennycode** [comment]
I found some issues related to portrait mode with these libraries. Not 100% sure but that could be it. My client is in love with Google Vision though after trying both. It is pretty amazing, he claims better and faster than some 800$ data display scanners.

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this.
