### ISSUE TITLE
How to get com.google.zxing .Result in callback method

### ISSUE THREAD

**Issue by santimendon** [journeyapps/zxing-android-embedded#297]
#### Description of the problem:
I need to find the type of Result obtained in callback. I intend to use below method for the same.

`ParsedResult m=ResultParser.parseResult(result);`

But this method needs a com.google.zxing.Result.
As of now I have used a DecoratedBarcodeView and BarcodeCallback.

`private DecoratedBarcodeView barcodeView;`
`
barcodeView = (DecoratedBarcodeView) findViewById(R.id.view_scanner);
barcodeView.setStatusText("");
barcodeView.decodeContinuous(callback);
`

private BarcodeCallback callback = new BarcodeCallback() {

        @Override
        public void barcodeResult(BarcodeResult result) {
            processScanResult(result);
           //Here I want to use below line of code
           ParsedResult m=ResultParser.parseResult(result);
        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
        }
    };

**Library version:** 
com.journeyapps:zxing-android-embedded:3.5.0

**Comment by rkistner** [comment]
There is no `ParsedResult` class in this library anymore - `BarcodeResult` contains the text and type of barcode.
