### ISSUE TITLE
How to show number of scanned barcode

### ISSUE THREAD

**Issue by vidyajejurkar** [journeyapps/zxing-android-embedded#298]
I am try to use ContinousCaptureActivity.

I want to show number of scanned Barcode in table view. How to do it?any idea?
I need result in following manner.
![image](https://cloud.githubusercontent.com/assets/6360660/26101142/c1e4d39c-3a4d-11e7-919a-1247f61c750d.png)

**Comment by rkistner** [comment]
That is a general Android UI issue, nothing specific to this project.
