### ISSUE TITLE
Provide an option to set decoder hints without IntentIntegrator.

### ISSUE THREAD

**Issue by mzgreen** [journeyapps/zxing-android-embedded#300]
I'm using 3.5.0 version of the library. I'm embedding it directly in my layout using `DecoratedBarcodeView` so I'm not using `IntentIntegrator`. I would like to change decoder hints, like for example set `tryHarder` flag to true. It's possible to set a custom decoder factory:
https://github.com/journeyapps/zxing-android-embedded/blob/6f73f470c95731bc06c70d05ced903b563e9fa0c/zxing-android-embedded/src/com/journeyapps/barcodescanner/BarcodeView.java#L103

But this doesn't change anything since hints are always provided by the library like:
https://github.com/journeyapps/zxing-android-embedded/blob/6f73f470c95731bc06c70d05ced903b563e9fa0c/zxing-android-embedded/src/com/journeyapps/barcodescanner/BarcodeView.java#L117

Could you please add more configuration options?

**Comment by Dancovich** [comment]
The line you highlighted are just the base hints.

On line 119 of the same code you have:
` Decoder decoder = this.decoderFactory.createDecoder(hints);`

If you see the code for createDecoder(hints) on the DefaultDecoderFactory you'll see it merges the base hints with the hints passed to the factory, like this:

https://github.com/journeyapps/zxing-android-embedded/blob/6f73f470c95731bc06c70d05ced903b563e9fa0c/zxing-android-embedded/src/com/journeyapps/barcodescanner/DefaultDecoderFactory.java#L34

So in theory all you have to do is provide your own instance of DefaultDecoderFactory with your own hints.
