### ISSUE TITLE
Android Camera Access failed

### ISSUE THREAD

**Issue by kayjoekahmann** [journeyapps/zxing-android-embedded#302]
#### Description of the problem:
The problem is, when I want to instantiate a ZXing-Scanner Scannerpage.
The Android Stacktrace throws the following exeption:

 

> Setup Error: Java.Lang.RuntimeException: Fail to connect to camera service
> 06-02 10:45:51.978 E/ZXING   ( 3773):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <d18287e1d683419a8ec3216fd78947b9>:0 
> 06-02 10:45:51.978 E/ZXING   ( 3773):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <5716a943049b49ca928a3a1c8d2386f4>:0 
> 06-02 10:45:51.978 E/ZXING   ( 3773):   at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <5716a943049b49ca928a3a1c8d2386f4>:0 
> 06-02 10:45:51.978 E/ZXING   ( 3773):   at Android.Hardware.Camera.Open (System.Int32 cameraId) [0x00022] in <33e6e739ac344166b157e323586f11a1>:0 
> 06-02 10:45:51.978 E/ZXING   ( 3773):   at ZXing.Mobile.CameraAccess.CameraController.OpenCamera () [0x0012b] in <7c7c485bd9034360a95deed1c4c824b8>:0 
> 06-02 10:45:51.978 E/ZXING   ( 3773):   --- End of managed Java.Lang.RuntimeException stack trace ---
> 06-02 10:45:51.978 E/ZXING   ( 3773): java.lang.RuntimeException: Fail to connect to camera service
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.hardware.Camera.<init>(Camera.java:495)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.hardware.Camera.open(Camera.java:341)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at md5e2ed3c6b13fcfff19371c0219cb2ee1f.ZXingSurfaceView.n_surfaceCreated(Native Method)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at md5e2ed3c6b13fcfff19371c0219cb2ee1f.ZXingSurfaceView.surfaceCreated(ZXingSurfaceView.java:73)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:582)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.os.Handler.handleCallback(Handler.java:739)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.os.Looper.loop(Looper.java:148)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at java.lang.reflect.Method.invoke(Native Method)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 06-02 10:45:51.978 E/ZXING   ( 3773): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

If I am right on it, and I think I am, here ist a problem with the Permissions of Android.

I give permissions like that:
`		public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
		{
			ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}`

and also tryed:
```

ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);

global::ZXing.Net.Mobile.Forms.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);

global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
```

**Which library version are you using?**
Library-Version: 2.2.9

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
I tested it on the VS2017 emulator with Android 6.0 running as OS

**Does the same happen on other devices or an emulator?**
All devices act the same.

**Comment by rkistner** [comment]
The 2.x version of this library is ancient - related issues have been fixed in 3.5.0.
