### ISSUE TITLE
Unable to gradle sync

### ISSUE THREAD

**Issue by zkrige** [journeyapps/zxing-android-embedded#303]
#### Description of the problem:
Gradle error on syncing

**Which library version are you using?** E.g. 3.2.0.
3.5.0

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Occurs on sample library project

**In the case of an error do you have a stack trace or adb logs?**
Gradle 'zxing-android-embedded-3.5.0' project refresh failed
Error:Connection reset

**Comment by rkistner** [comment]
That points to a network error, not likely an issue with this project.
