### ISSUE TITLE
It takes lots of time and sometimes QRCode is not getting scanned

### ISSUE THREAD

**Issue by sana080** [journeyapps/zxing-android-embedded#304]
#### Description of the problem:

I am using for scanning QRCode but it is not getting scanned and when it is then it takes lots of time 

**Which library version are you using?** 3.5.2

**Which phone/tablet are you using, and which Android version does it run? 
. Moto G, Android 5.1

**Does the same happen on other devices or an emulator?**
Tested in MotoG and Samsung J2

**Comment by Adikso** [comment]
I am also having this problem on Nexus 5, Android 6.0

**Comment by deathnopool** [comment]
having the same problem  on android n

**Comment by Nerkritus** [comment]
Also experiencing this on Motorola G Play, Android 6.0.1

**Comment by aitbaali** [comment]
any solution @journeyapps?

**Comment by rkistner** [comment]
@aitbaali No solution yet. Could be related to the target SDK version of the app, but haven't confirmed yet.

**Comment by Nerkritus** [comment]
@rkistner I'm targeting Marshmallow in my app with minimum SDK set to Kit Kat.

I also recently installed the Feb 2017 security patches if that helps.

**Comment by pawelantczak** [comment]
Same with ```        targetSdkVersion 25```.

**Comment by eligiobz** [comment]
Same problems on Samsung J7 and ```targetSdkVersion 23```

**Comment by Nerkritus** [comment]
I've noticed this is only affecting my app in debug. When I run the release from the play store on the problem device, QR code scanning works fine.

So perhaps it's not such a big deal.

**Comment by letitfly** [comment]
+1 same here. Android 5.1, HTC One.

**Comment by sana080** [comment]
@Nerkrotus : Agree
Working comparatively better and fast when not running in debug mode

**Comment by aitbaali** [comment]
It worked fast and better for me when I change the size of the barcodeview and turn the torch on
`barcodeScanner` is an instance if DecoratedBarcodeView
`barcodeScanner.getBarcodeView().setFramingRectSize(new Size(width, height));`

```
if (hasFlash()) {
            barcodeScannerFid.setTorchOn();
}

 /**
     * Check if the device's camera has a Flashlight.
     *
     * @return true if there is Flashlight, otherwise false.
     */
    private boolean hasFlash() {
        return getApplicationContext().getPackageManager()
                .hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH);
    }
```
see [https://github.com/journeyapps/zxing-android-embedded/blob/50e3acce091decc195f67e6079b86427ddc2ad60/sample/src/main/java/example/zxing/CustomScannerActivity.java](https://github.com/journeyapps/zxing-android-embedded/blob/50e3acce091decc195f67e6079b86427ddc2ad60/sample/src/main/java/example/zxing/CustomScannerActivity.java)

**Comment by ismdcf** [comment]
Had the same issue when trying to give a custom random size and then figured out the aspect ratio plays a major role in the qr code readability.

Following size worked for me 
240dp height
320dp width 

and if setting the value to a larger screen size multiplying the value by integer gave good readability.
 480dp height
640dp width

**Comment by xxss0903** [comment]
before Detector to detect the QRCode bitmatrix, i found if bitmatrix.rotate180() can improve the scan effective.

**Comment by rkistner** [comment]
Debugger mode will make scanning slower - always test performance without a debugger connected.

For the other reports here there is not enough info to debug.
