### ISSUE TITLE
takes lots of time to scan also sometimes not working

### ISSUE THREAD

**Issue by devaks3** [journeyapps/zxing-android-embedded#305]
#### Description of the problem:
it takes too much of time to scan the bar code also sometimes it is not working.

**Which library version are you using?
-3.5.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
-google glass

**Comment by rkistner** [comment]
Google Glass is not supported, as we do not have access to the hardware. That said, pull requests with fixes are welcome.
