### ISSUE TITLE
Failed to reslove: com.journeyapps:zxing-android-embedded:3.5.0

### ISSUE THREAD

**Issue by Shygin** [journeyapps/zxing-android-embedded#307]
Unable to add ZXing to new project in Android Studio:

Hi,

I'm completely new to android development and have been trying unsuccessfully to use Zxing in a new project.

The latest error I'm getting is: 'Failed to reslove: com.journeyapps:zxing-android-embedded:3.5.0'
I got the embedded version of ZXing from here: [https://github.com/journeyapps/zxing-android-embedded](url)
But I don't know how to tell my project to use this.

Below is my build.gradle (Module: app):

`apply plugin: 'com.android.application'
repositories {
    maven { url 'http://repo1.maven.org/maven2' }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "com.sjc.code.qrcodescanner"
        minSdkVersion 9
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha7'
    testCompile 'junit:junit:4.12'
    compile 'com.google.zxing:core:3.3.0'
    compile 'com.journeyapps:zxing-android-embedded:3.5.0@aar'
    compile 'com.android.support:appcompat-v7:25.1.0'
}

android {
    buildToolsVersion '25.0.0' // Older versions may give compile errors
}
`

I cannot use 'repositories { Jcenter() }', because then my build hangs.

There is a lot of documentation on how to integrate Zxing, but I haven't been able to implement any of these without getting stuck with some error.

Can you please help?

Thanks,
Shyama

**Comment by rkistner** [comment]
You need to add `jcenter()` to your `repositories` section:

```
repositories {
    jcenter()
}
```

**Comment by Shygin** [comment]
As I have mentioned on my original ticket, I cannot use 'repositories { Jcenter() }', because then my build hangs.

**Comment by rkistner** [comment]
I missed that in the original ticket. It is required to resolve this library - it is not published on Maven central. I'm not sure what would cause the hanging, but you can try upgrading or downgrading Gradle versions. You may also be able to get more info by running Gradle in verbose mode.

**Comment by rkistner** [comment]
Also note that `jcenter()` should be lower-case.
