### ISSUE TITLE
1d any orientation not doing any orientation

### ISSUE THREAD

**Issue by iamdarkes** [journeyapps/zxing-android-embedded#308]
#### Description of the problem:
trying out the demo app 1d does not scan vertically.

**Which library version are you using?** E.g. 3.2.0.
using the sample apk
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
nexus 5x android 7.1.2
If you have an issue scanning specific barcodes, please test with the Barcode Scanner application,
available on the Play Store: https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en

If you are also not able to scan the barcode there, the issue may be with the underlying zxing library,
in which case you should report the issue here: https://github.com/zxing/zxing/issues
-->

**Comment by rkistner** [comment]
Duplicate of #211.
