### ISSUE TITLE
I am unable to build the app

### ISSUE THREAD

**Issue by fineanmol** [journeyapps/zxing-android-embedded#309]
Error:Execution failed for task ':galgotiasuniversitymsim:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --multi-dex --main-dex-list E:\MyApplication3\GalgotiasUniversity-mSim\galgotiasuniversitymsim\build\intermediates\multi-dex\debug\maindexlist.txt --output E:\MyApplication3\GalgotiasUniversity-mSim\galgotiasuniversitymsim\build\intermediates\transforms\dex\debug\folders\1000\1f\main E:\MyApplication3\GalgotiasUniversity-mSim\galgotiasuniversitymsim\build\intermediates\transforms\jarMerging\debug\jars\1\1f\combined.jar}

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this.
