### ISSUE TITLE
Use auto Focus | in embedded mode switch on But HOW ?

### ISSUE THREAD

**Issue by Control-C** [journeyapps/zxing-android-embedded#310]
Hi,

(* yes working in weekend )

I want to embedded the Zxing lib into my App for an Android 5.0 device. 

Problem I have is I tested the Sample App named "Barcode Scanner" APK and I needed to switch on in setting  the "Use auto focus" checkbox to scan my Bar,matrix and QR code.... (* this works like charm )

Now I have running code and I see that the focus is not working so I want to switch on the focus but I don't get it to work I also don't know how to set this...  Maybe in update, you can add this in LIB like setBeep ect...

.setPrompt(getString(R.string.zxing_scan_user))
.setBeepEnabled(true)

// Need something like
.setAutoFocus(true)

**Comment by caroaguilar** [comment]
Check the examples in here https://github.com/journeyapps/zxing-android-embedded/tree/master/sample/src/main/java/example/zxing

you can control the beep 
```private BeepManager beepManager;
private DecoratedBarcodeView barcodeView;
...
beepManager.playBeepSoundAndVibrate();
barcodeView.getBarcodeView().getCameraSettings().setAutoFocusEnabled(true);

```

**Comment by freaksgit** [comment]
I did like this:
```
ToggleButton switchCameraFocusButton = findViewById(R.id.switch_autofocus);
switchCameraFocusButton.setChecked(barcodeScannerView.getBarcodeView().getCameraSettings().isAutoFocusEnabled());
switchCameraFocusButton.setOnCheckedChangeListener((buttonView, isChecked) -> {
            barcodeScannerView.pause();
            if (isChecked) {
                barcodeScannerView.getBarcodeView().getCameraSettings().setAutoFocusEnabled(true);
            } else {
                barcodeScannerView.getBarcodeView().getCameraSettings().setAutoFocusEnabled(false);
            }
            barcodeScannerView.resume();
        });
```
