### ISSUE TITLE
Crop rectangle does not fit within image data.

### ISSUE THREAD

**Issue by huaminghui** [journeyapps/zxing-android-embedded#314]
Crop rectangle does not fit within image data

**Comment by natronite** [comment]
Here the stack trace we have:

java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
	at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
	at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:102)
	at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:126)
	at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:134)
	at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
	at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:135)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by yashasvigirdhar** [comment]
Facing the same issue. Can someone please pointers on how to prevent this?

**Comment by cfm1120** [comment]
Same issue.. crash on  SamsungGT-I9152 and Huawei PE-TL20

**Comment by artharyoung** [comment]
```
public class SendMsgBarcodeView extends BarcodeView {

    private int with = 0;
    public SendMsgBarcodeView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public SendMsgBarcodeView(Context context) {
        super(context);
    }

    public SendMsgBarcodeView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    public Rect getPreviewFramingRect() {
        //return the preview data size width
        if (with == 0) {
            CameraInstance cameraInstance = getCameraInstance();
            try {
                if (cameraInstance != null) {
                    Class<?> forName = cameraInstance.getClass();
                    Method method = forName.getDeclaredMethod("getCameraManager");
                    method.setAccessible(true);
                    CameraManager cameraManager = (CameraManager) method.invoke(cameraInstance);
                    if (cameraManager != null && cameraManager.getPreviewSize() != null) {
                        with = cameraManager.getPreviewSize().width;
                    }
                }
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
        }

        int left = 0;
        int top = (getHeight() - getContext().getResources().getDimensionPixelSize(R.dimen.dp_150)) / 2;
        int right = Math.min(with, getWidth());
        int bottom = top +  getContext().getResources().getDimensionPixelSize(R.dimen.dp_150);

        return new Rect(
                left,
                top - DensityUtil.dip2px(mContext,80),
                right,
                bottom - DensityUtil.dip2px(mContext,80));
    }

}
```
@yashasvigirdhar  try

**Comment by soenkegissel** [comment]
I had this issue when using Zxing > 3.3.0 like this:

implementation 'com.journeyapps:zxing-android-embedded:3.6.0'

before I used Zxing 3.3.0 without a problem like this:

dependencies {
    implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'
}
This is now the compatible implementation for API >= 14. See the readme for details.

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.

**Comment by maheshgelani** [comment]
implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'

after using this i am still getting the same issue mentioned above in My LG device API => 6.0.1

**Comment by yanneck-blg** [comment]
I am also facing this issue on some devices of my users, any new updates to this problem?
