### ISSUE TITLE
Help, how to present the scanned result to a new activity?

### ISSUE THREAD

**Issue by biger666** [journeyapps/zxing-android-embedded#316]
Hi, I am new to Android studio. 

Currently, I am doing a project to transfer the scanned result  from one mobile phone to another. How can I make the scanned result be presented in a new activity (I create a displaymessage activity already.) instead of back to the main page?

Many thanks in advance.

**Comment by DarkSpam91** [comment]
how you solve this problem?

**Comment by iryanjan18** [comment]
Looking for this also. If anyone managed to solve this, let me know. Thanks!
