### ISSUE TITLE
Call OnActivityResault on start scanner view in API 17

### ISSUE THREAD

**Issue by miwaniec** [journeyapps/zxing-android-embedded#317]
I have a problem with scanner on older device (HTC One, api 17).
When I call _initiateScan()_, at the same moment I got "Cancalled" toast. Camera preview still working, and even I can scan qr code properly (I heard beep), but I don't get results.

I call initiateScan from Fragment, but I want result in activity. I tested solution with IntentIntegrator.forSupportFragment, but it was exacly the same.
It's working correctly in device with api 23.

**Which library version are you using?** tested in 3.4 and 3.5

**Which phone/tablet are you using, and which Android version does it run?** Htc One X

**Does the same happen on other devices or an emulator?** yes, on emulator api19. no, on device with api 23.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

Fragmetn, button onclick:
`public void onClick(View v) {
                new IntentIntegrator( getActivity() ).initiateScan();
                // result go to Activity -> activity/Main.java
            }`

Main:
`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            if(result.getContents() == null) {
                Toast.makeText(this, "Cancelled", Toast.LENGTH_LONG).show();
            } else {
                final String qr = result.getContents();
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        displayViewPage("qr.html?qr=" + URLEncoder.encode(qr) );
                    }
                });
            }
        }

        super.onActivityResult(requestCode, resultCode, data);
    }`

**In the case of an error do you have a stack trace or adb logs?**
No errors.

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.
