### ISSUE TITLE
Continuous Scanning support AsyncTask or onActivityResult?

### ISSUE THREAD

**Issue by Tozilla617** [journeyapps/zxing-android-embedded#320]
#### Description of the problem:
I've been playing around the sample ContinuousCaptureActivity that add AsyncTask and overrode onActivityResult. The following is what I want 

1. Scan the barcode
2. Pass the result to asynctask and trigger web service.
3. stay in the same activity and continue to scan the next barcode. 

However, it does not trigger  onActivityResult method or AsyncTask 

**Which library version are you using?** E.g. 3.2.0.
3.5

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Samsung Galaxy S5

**Does the same happen on other devices or an emulator?** Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?** Yes

**In the case of an error do you have a stack trace or adb logs?**
No, error log. It does not trigger asynctask or onActivityResult

**Comment by rkistner** [comment]
This is a general app-level issue, the library only goes as far as calling the callback.
