### ISSUE TITLE
createCircularReveal makes square reveal on API16

### ISSUE THREAD

**Issue by Ashanmaril** [journeyapps/zxing-android-embedded#321]
#### Description of the problem:
I've been using the library since 1.3.1
I figured I'd try updating to the latest version today, so I updated it to 2.0.1, tweaked the code so it works with the new APIs (looks like you use a native Animator instead of the included SupportAnimator now), and it worked fine when I tested it on a Pixel with API26 (Oreo), but my app is backwards compatible to API16 (Jellybean), and the circular reveal seems to turn into a square now. I reverted back and it works on 1.3.1, but not with 2.0.1

**Which library version are you using?**
2.0.1

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Nexus 4, Android 4.2.2, stock

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
```
Animator anim
anim = io.codetail.animation.ViewAnimationUtils
                    .createCircularReveal(childBG, cx, cy, 0, finalRadius);
anim.setDuration(ANIMATION_LENGTH);
anim.setInterpolator(new AccelerateDecelerateInterpolator());
anim.start();
```

Also worth noting, I Googled the issue and found at least one other person running into this from May 8th:  
https://stackoverflow.com/questions/28544800/create-circular-reveal-for-pre-lollipop-devices-android#comment74732182_28604515

**Comment by rkistner** [comment]
Sound like this is an issue with https://github.com/ozodrukh/CircularReveal, not this library.

**Comment by Ashanmaril** [comment]
Arg! You're right! I must have gotten lost while tab juggling, you know how it is.

Sorry about that!
