### ISSUE TITLE
Improve scanning process

### ISSUE THREAD

**Issue by datnt1987** [journeyapps/zxing-android-embedded#322]
Hi pro,
I'm using zxing-android-embedded for my project and It take times to scan and return callback result. Then I want to speedup scanning from start scanning to return result callback. So, please help me to improve in my code to handle scanning process faster.

In my code:
`CameraSettings settings = new CameraSettings();
        settings.setFocusMode(CameraSettings.FocusMode.MACRO);
        barcodeScannerView.getBarcodeView().setCameraSettings(settings);
        barcodeScannerView.decodeSingle(callback);
        barcodeScannerView.getBarcodeView().addStateListener(this);`

Thanks in advance

**Comment by rkistner** [comment]
Barcode scanning takes time, and this depends on many different factors, including the device, camera, barcode being scanned, lighting conditions. Pull requests to improve the process are welcome.

**Comment by whiteboy** [comment]
Thanks for answering.

**Comment by whiteboy** [comment]
I would like to ask one more question, now I having an activity to scan QR code(A), and after scanning, I start another activity (B) (A is still not finished).
Case 1: In A, I use barcodeScannerView.decodeSingle(callback) at onResume(). So everytime when back from B, barcodeScannerView.decodeSingle(callback) is invoked onResume() to detect QR.
Case: In A, i use barcodeScannerView.decodeContinous(callback) at onCreate(). 

So the question is, which case is best performance and faster than the other?

**Comment by rkistner** [comment]
`decodeContinuous` may be slightly faster, since it keeps the decoding thread active, instead of stopping and starting it after each scan.
