### ISSUE TITLE
Not working when compiling ourself

### ISSUE THREAD

**Issue by ericfischerrv** [journeyapps/zxing-android-embedded#325]
We tried to implement the ZXing to our app. Testing the demo application impressed us. But when compiling with Android Studio, the scanner is very slow or does not scan. The demo is still working fine. We treid compiling on different PCs. Same problem when debugging/running from Android Studio.

Is there any known problem?

Library: 3.5.0
Device OS: Android 6.0.1 API 23

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.

That said, make sure to test _without debugging_. Debugging makes the scanning a lot slower.
