### ISSUE TITLE
Continuous scanner only QR code allowed

### ISSUE THREAD

**Issue by grigorz** [journeyapps/zxing-android-embedded#329]
#### Description of the problem:

Hi guys.

I am using your Continuous scanner sample app and I have following problem. I want to allow only QR code scanning. I tried to do research but couldn't find the solution. Is there way to do this? 

Thanks.

**Which library version are you using?** E.g. 3.5.0

**Does the same happen on other devices or an emulator?** Yes

**Comment by ericfischerrv** [comment]
You have to look closer at the code ZXing allows to include only QR codes. I think you have to set the option in the Intent.

**Comment by rkistner** [comment]
You can configure it to scan any type of barcode - see the samples.
