### ISSUE TITLE
NullPointerException crashes

### ISSUE THREAD

**Issue by pnevalle** [journeyapps/zxing-android-embedded#333]
#### Description of the problem:
NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.camera.CameraInstance.setSurface(com.journeyapps.barcodescanner.camera.CameraSurface)' on a null object reference
  Module "com.journeyapps.barcodescanner.CameraPreview", line 461, in onLayout
  Module "com.journeyapps.barcodescanner.CameraPreview$2", line 171, in surfaceChanged
  Module "com.journeyapps.barcodescanner.CameraPreview", line 53, in access$100
  Module "com.journeyapps.barcodescanner.CameraPreview", line 436, in startPreviewIfReady
  Module "com.journeyapps.barcodescanner.CameraPreview", line 649, in startCameraPreview
...
(50 additional frame(s) were not displayed)

NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.camera.CameraInstance.setSurface(com.journeyapps.barcodescanner.camera.CameraSurface)' on a null object reference
  Module "com.journeyapps.barcodescanner.CameraPreview$3", line 179, in handleMessage
  Module "com.journeyapps.barcodescanner.CameraPreview", line 53, in access$300
  Module "com.journeyapps.barcodescanner.CameraPreview", line 387, in previewSized
  Module "com.journeyapps.barcodescanner.CameraPreview", line 436, in startPreviewIfReady
  Module "com.journeyapps.barcodescanner.CameraPreview", line 649, in startCameraPreview
...
(6 additional frame(s) were not displayed)

**Which library version are you using?** E.g. 3.2.0.
3.1.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**
Same as above

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.
