### ISSUE TITLE
Scanner does not work in TabLayout 

### ISSUE THREAD

**Issue by hstorz** [journeyapps/zxing-android-embedded#335]
#### Description of the problem:
In the sample app the scanner which is embedded in the tab layout fragment does not work. The camera is shown correctly in the fragment, but when I want to scan a barcode it does not get recognized. Also the animated dots that usually appear while scanning, are not shown when I use the barcode scanner embedded in the tab layout. All other barcode scanner samples in the sample app work perfectly. However, I also need it embedded in a TabLayout and when I tried as shown in the sample it also did not work in my app.

**Which library version are you using?** E.g. 3.2.0.
Sample app 3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
OnePlus 3 with Android 7.1.1 Stock Oxygen 4.5.0

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Happens in sample app.

**Comment by rkistner** [comment]
Scanning does work in tabs - it is simply not enabled currently in the sample. All that needs to added is a call to `barcodeView.decodeContinuous()` or `barcodeView.decodeSingle()`.
