### ISSUE TITLE
Library Scan Wrong barcode sometimes

### ISSUE THREAD

**Issue by Samyak81** [journeyapps/zxing-android-embedded#337]
#### Description of the problem:

Hi

I am using below version

    compile 'com.journeyapps:zxing-android-legacy:2.3.0@aar'
    compile 'com.journeyapps:zxing-android-embedded:3.5.0@aar'
    compile 'com.google.zxing:core:3.3.0'

I have used DecoratedBarcodeView in my actiivty.

when i scan sometimes it scan and give me wrong barcode result and if i rescan it then it gives me correct result.

e.g.

my barcode is below
00373500598048386007

for the first time if i scan it gives this value

00373500598/4)3860&7

if i rescan it then it gives me correct value.
00373500598048386007

May i know why is this kind of issue occures. It is random behavior.  If i continuously scan  3-4 barcode then in 5th or 6th barcode i face this issue.

Please help me urgently,.

**Comment by anjiao** [comment]
me too

**Comment by rkistner** [comment]
Please follow the issue template. Specifically:

> If you have an issue scanning specific barcodes, please test with the Barcode Scanner application,
available on the Play Store: https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en
> 
> If you are also not able to scan the barcode there, the issue may be with the underlying zxing library,
in which case you should report the issue here: https://github.com/zxing/zxing/issues

This is generally an issue with some 1D barcode types such as EAN and UPC, which is difficult to scan with a phone camera, and doesn't have good error detection. If you get the same issue with the Barcode Scanner application, you're welcome to take the issue further there, but it's not likely that we'll get better results without significantly improving the algorithm, which is out of scope for this project.

**Comment by Samyak81** [comment]
Hi i tried that app and it works fine. But the issue is with this library. Also i am using DecoratedBarcodeView  and CompoundBarcodeView which takes too much time to scan. and it can not detect  barcode type COde-128. while if you trey to scan with below code . It does

 IntentIntegrator integrator = new IntentIntegrator(ScanOffActivity.this);
                integrator.setTimeout(20000);
                integrator.setOrientationLocked(false);
                integrator.initiateScan();

for DecoratedBarcodeView barcodeView = (DecoratedBarcodeView) findViewById(R.id.zxing_barcode_scanner);
        barcodeView.decodeContinuous(callback);

do we need to add some extra

can we add
 capture = new CaptureManager(ScanOnActivity.this, barcodeView);
  capture.initializeFromIntent(returnnf(), savedInstanceState);
  capture.decode();

but it finishes activity and doesnot give result to same activity

How can i achieve that??

Thanks in advance

**Comment by rkistner** [comment]
For a custom Activity, it is up to the application to ensure the results are correctly returned.

**Comment by pra-josh** [comment]
Hi @rkistner,
                  I am facing same issue so please send me custom Activity code.

Thanks in Advance

**Comment by pra-josh** [comment]
> For a custom Activity, it is up to the application to ensure the results are correctly returned.

Hi @rkistner,
I am facing same issue so please send me custom Activity code.

Thanks in Advance
