### ISSUE TITLE
Cant able to scan Code-128 type barcode using DecoratedBarcodeView

### ISSUE THREAD

**Issue by Samyak81** [journeyapps/zxing-android-embedded#338]
I have implemented below code in my application.

 barcodeView = (DecoratedBarcodeView) findViewById(R.id.zxing_barcode_scanner);
        capture = new CaptureManager(ScanOffActivity.this, barcodeView);
        capture.initializeFromIntent(getIntent(), savedInstanceState);
        capture.decode();

And If i try to to detect barcode of below 10 characters it couldn't scan that barcodes.
Even it couldn't scan barcode with special characters as weill. When the zxing https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en this library does it. 

any changes do i need to do?

Please let me know asap.

Thanks in advance

**Comment by rkistner** [comment]
Closing old issues - open another one if you still have trouble on the latest version.
