### ISSUE TITLE
Replace support-v4 with support-fragment

### ISSUE THREAD

**Issue by satorym** [journeyapps/zxing-android-embedded#339]
#### Description of the problem:
This lib depends on  `com.android.support:support-v4:25.1.0`.
Starting from `support-v4:24.2.0` it has been split into several smaller modules ([prooflink](https://developer.android.com/topic/libraries/support-library/rev-archive.html#24-2-0-v4-refactor))
`zxing-android-embedded` uses only `support-fragment` subset.

Please, replace 
`com.android.support:support-v4:25.1.0`
with
`com.android.support:support-fragment:25.1.0`

This will reduce number of transitive dependencies hence size of apks that use `zxing-android-embedded`

Thanks

**Comment by rkistner** [comment]
This has now been replaced with androidx libraries.

There may still be a similar case with the androidx versions. Pull requests are welcome, but I'm not considering this an issue.
