### ISSUE TITLE
can able to scan with android 6

### ISSUE THREAD

**Issue by DarkSpam91** [journeyapps/zxing-android-embedded#340]
#### Description of the problem:

i have been using this labrary for my proyects,  so far everything works fine, but when i try my app on android 6 it throws me the following error:

Sorry, the android camera has encountered a problem.
you may need to restart the computer.
![error](https://user-images.githubusercontent.com/8412219/32174409-220769e6-bd58-11e7-9854-ef0f67f58f6c.png)
the error is  in spanish but i translated them

in the dependencies of the proyect i have the following:
 compile 'com.journeyapps:zxing-android-embedded:3.0.2@aar'
  compile 'com.google.zxing:core:3.2.0'
 buildToolsVersion "25.0.3"

 minSdkVersion 16
 targetSdkVersion 25

i tried the application in two devices a samsung J1 Mini(SM-J106M) and a Blu Diamond M and both wanting to capture give the error i explained above, i really do not know what may be happening, i need your help in this problem.

**Comment by rkistner** [comment]
Please update to the latest version of this library, and check again: `compile 'com.journeyapps:zxing-android-embedded:3.5.0'`
