### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by ding33211** [journeyapps/zxing-android-embedded#346]
com.journeyapps.barcodescanner.ae.a(SourceData.java:186)
--
com.journeyapps.barcodescanner.ae.a(SourceData.java:163)
com.journeyapps.barcodescanner.ae.e(SourceData.java:101)
com.journeyapps.barcodescanner.u.a(DecoderThread.java:137)
com.journeyapps.barcodescanner.u.b(DecoderThread.java:145)
com.journeyapps.barcodescanner.u.a(DecoderThread.java:22)
com.journeyapps.barcodescanner.v.handleMessage(DecoderThread.java:38)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:142)
android.os.HandlerThread.run(HandlerThread.java:61)

this line
byte[] yuv = new byte[imageWidth * imageHeight];

**Comment by rkistner** [comment]
OutOfMemoryErrors depend on the overall memory usage of the app, and the available memory on the device. It just happens to crash at a point when this library is trying to allocate memory.
