### ISSUE TITLE
BarcodeView stays black because onresume

### ISSUE THREAD

**Issue by markwittbabbel** [journeyapps/zxing-android-embedded#348]
when i enter onresume in barcodeview, it doesn't show up.
It is IMPORTANT to call barcodeview.onresume inside of onresume.

**Comment by yuvaraj119** [comment]
@markwittbabbel did you got the solution for this issue i am getting the same issue and i am using kotlin.

**Comment by rkistner** [comment]
If you still run into this, post a sample project demonstrating the issue.
