### ISSUE TITLE
Unicode issue if scan content in other language

### ISSUE THREAD

**Issue by swapnilghadge2390** [journeyapps/zxing-android-embedded#349]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

I am using this library for scanning barcode but if barcode contains any other language content, i am getting result like %20%C3%84%C3%96%C3%9C%C3%9F instead of german language content.

IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);  this line gives result as %20%C3%84%C3%96%C3%9C%C3%9F

**Comment by ali77gh** [comment]
same problem in farsi
but result is like this -> ???????

**Comment by ali77gh** [comment]
you can use this method to generate qrcode bitmap:
~~~java
public static Bitmap Generate(String content) {

        Hashtable hints = new Hashtable(); //important
        hints.put(EncodeHintType.CHARACTER_SET, "UTF-8"); //important

        QRCodeWriter writer = new QRCodeWriter();
        try {
            BitMatrix bitMatrix = writer.encode(content, BarcodeFormat.QR_CODE, 512, 512,hints); //512 is size of bitmap
            int width = bitMatrix.getWidth();
            int height = bitMatrix.getHeight();
            Bitmap bmp = Bitmap.createBitmap(width, height, Bitmap.Config.RGB_565);
            for (int x = 0; x < width; x++) {
                for (int y = 0; y < height; y++) {
                    bmp.setPixel(x, y, bitMatrix.get(x, y) ? Color.BLACK : Color.WHITE);
                }
            }
            return bmp;

        } catch (WriterException e) {
            e.printStackTrace();
            throw new RuntimeException();
        }
    }
~~~

**Comment by rkistner** [comment]
If you are still having trouble with this, please open a new issue with an example image of the barcode, and the expected scan results.
