### ISSUE TITLE
Can't scan QR-code on Android

### ISSUE THREAD

**Issue by VIAwe** [journeyapps/zxing-android-embedded#351]
#### Description of the problem:

It's easy to use at the beginning. But with the increase of the code, the identification rate will slow down, and then basically can not get result.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Not enough info.
