### ISSUE TITLE
PDF417

### ISSUE THREAD

**Issue by kuleshovdv** [journeyapps/zxing-android-embedded#354]
When will library update for reading PDF417? The original ZXing supports it as beta.

**Comment by rkistner** [comment]
This library supports all barcodes that ZXing supports, including PDF417 (although it doesn't work well if it contains a lot of data).

**Comment by kuleshovdv** [comment]
Can it be set in method setDesiredBarcodeFormats() of class IntentIntegrator? Which string?
There is little data in [this barcode](http://wiki.lineris.ru/_media/pos/pdf417.gif). Does not read.

**Comment by rkistner** [comment]
Yes, see https://github.com/journeyapps/zxing-android-embedded/issues/166.

**Comment by kuleshovdv** [comment]
Sorry I did not understand what value of parameter string desiredBarcodeFormats in setDesiredBarcodeFormats method corresponds to the PDF17 encoding?
I try
`intentIntegrator.setDesiredBarcodeFormats("PDF17");`
doesn't work :(
If I don't call setDesiredBarcodeFormats it doesn't work either.

**Comment by rkistner** [comment]
There seems to be a typo: it should be `PDF417`, not `PDF17`.
