### ISSUE TITLE
auto snap

### ISSUE THREAD

**Issue by u007** [journeyapps/zxing-android-embedded#355]
#### Description of the problem:

is it possible to auto snap when barcode is detected?

**Which library version are you using?** E.g. 3.2.0.
3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
android lollipop

**Does the same happen on other devices or an emulator?**
guess so

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

can use sample, but i do not know if it is already exists
**In the case of an error do you have a stack trace or adb logs?**
n/a

**Comment by rkistner** [comment]
Need more info on what you would like to achieve.
