### ISSUE TITLE
Using IntentIntegrator in fragment, gives yellow dots when the camera opens

### ISSUE THREAD

**Issue by vivekwolf123** [journeyapps/zxing-android-embedded#357]
![screenshot_20171227-230411](https://user-images.githubusercontent.com/14298142/34394604-8a548ed6-eb5a-11e7-8b50-c2d543284ee1.png)
#### Description of the problem:
I am using IntentIntegrator in fragment and when the camera opens, I have yellow dots appearing in the camera scan.

I use it like this in fragment-
IntentIntegrator.forSupportFragment(this).setPrompt("").initiateScan();

I handle the result in an Activity in onActivityResult()

**Which library version are you using?**
This is my gradle dependency 
compile 'com.journeyapps:zxing-android-embedded:3.0.2@aar'
compile 'com.google.zxing:core:3.3.0'

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)** 
Samsung Galaxy S7 edge with 7.0 Android version

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by chris8447** [comment]
These dots are called Result Points. Looking also for a way to remove them.

**Comment by rkistner** [comment]
This is by design. You can customize this by creating your own Activity, and not using ViewfinderView (or modify ViewfinderView).

**Comment by jawed1412** [comment]
just put in you colors.xml
<color name="zxing_possible_result_points">#00ffffff</color>
