### ISSUE TITLE
Return whole photo bitmap

### ISSUE THREAD

**Issue by Chesteer89** [journeyapps/zxing-android-embedded#36]
Hi,

how should i take whole bitmap photo after scanned qr? Should I extends result method with bitmap, or try to save bitmap from view? I don't need really big images, i think 800x600 would be sufficient.

**Comment by rkistner** [comment]
It's probably best to make the image part of the results. This will have to
be done in the library, probably DecoderThread. I can't work on this in the
next two weeks, but pull requests are welcome.

**Comment by BugMaker** [comment]
Already in pull requests

**Comment by Chesteer89** [comment]
Agree, works like a charm. Good job :+1:

**Comment by rkistner** [comment]
Fixed in #37, thanks @BugMaker.

**Comment by maslick** [comment]
I was wondering if it is possible to get the whole photo?
