### ISSUE TITLE
Using Zxing for Smart glasses, no touch screen option, adding keydown to captureActivity

### ISSUE THREAD

**Issue by gamengamenut** [journeyapps/zxing-android-embedded#362]
#### Description of the problem:

Which library version are you using? : 3.3.0

Developing on the Vuzix M300 Smart Glasses

Using this method to implement ZXing:

        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureLayout(R.layout.activity_scan2);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt(" ");
        integrator.addExtra("CONTINEUOUS_SCAN", true);
        integrator.createScanIntent();
        integrator.setWide();  // Wide scanning rectangle
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.initiateScan();

Once it goes to the scanning page, Keydown presses don't do anything.
Just part of the code
 public boolean onKeyDown(int keyCode, KeyEvent event) {
        boolean retVal = false;
        switch (keyCode) {
            case KeyEvent.KEYCODE_DPAD_LEFT: {
                Log.d(LOGTAG, "Left Pressed");
                Intent intent = new Intent(RLOScan.this, RLOPlan.class);
                intent.putExtra("page", "fwd");
                startActivity(intent);
                this.finish();
                retVal = true;
            } break;
}
        return retVal;}

On keydown i would want to start another activity, but the scanner doesnt read any keydown when i press the button.

**Comment by rkistner** [comment]
Key presses are outside the scope of this library, and shouldn't be affected by library if you have your own Activity.
