### ISSUE TITLE
How remove spaces around QR?

### ISSUE THREAD

**Issue by lmdic** [journeyapps/zxing-android-embedded#363]
In my app/build.gradle

`    implementation 'com.journeyapps:zxing-android-embedded:3.5.0'`

OK. It's work fine. 
But the proble is that around QR code show spaces (white color).
How I can remove this spaces? And to remain only QR code.
Here example of qr:
![qr](https://user-images.githubusercontent.com/303539/34904806-f1a1d730-f855-11e7-989a-622f25148798.png)

**Comment by javichaques** [comment]
I have the same question

**Comment by bu2zhouzhu** [comment]
same question + 1

**Comment by rkistner** [comment]
Customizing generated barcodes is not supported in this library. The code is fairly simple though - you can copy and modify it yourself.

**Comment by LXLYHM** [comment]
same question + 1
