### ISSUE TITLE
Editing/Adding an element to the UI of the scanner

### ISSUE THREAD

**Issue by xDrei** [journeyapps/zxing-android-embedded#365]
Hi is there a way to change/edit the UI of the scanner, for example adding a logo or an icon on the gray part of the screen.

Something similar to this.
![image](https://user-images.githubusercontent.com/11171629/35087274-a30e73c6-fc6a-11e7-81f2-e08f2c54dd7e.png)

**Comment by pedroromao-acceptto** [comment]
Before posting look for open issues. You have the samples to serve as guide to make those changes. You can see my message on issue #352

**Comment by xDrei** [comment]
Thank you.
