### ISSUE TITLE
移动条码识别位置,如若需要改动源码,能否告知修改哪些自定义View哪些地方呢?

### ISSUE THREAD

**Issue by zhangjianzhu** [journeyapps/zxing-android-embedded#366]
![1](https://user-images.githubusercontent.com/18592113/35133968-37a33e74-fd0e-11e7-9138-a982ee00766d.png)
我这边需要实现一个这样的功能,请问如何把识别位置置顶呢?
如果需要修改源码的话,能否告知修改哪些地方:
BarcodeView、CameraPreview、CompoundBarcodeView、ViewfinderView?

**Comment by teolemon** [comment]
"I need to implement one such function here. How do I put the identification position to the top?
If you need to modify the source code, can you tell me where to change:
BarcodeView, CameraPreview, CompoundBarcodeView, ViewfinderView?"

**Comment by zhangjianzhu** [comment]
这个库的识别区域已经被定死在正中间,所有如果我想改变识别区域的话,要这么做呢.

**Comment by teolemon** [comment]
你能否努力用英语写你的评论？ 我是法国人，我会说一点中文，但国际工作语言是英语 ;）

**Comment by teolemon** [comment]
如果有更多人能够理解，你会有更多的答案。

**Comment by zhangjianzhu** [comment]
The recognition area of this library has been fixed in the middle, so if I want to change the recognition area.
How do I do that?

**Comment by rkistner** [comment]
Please post issues in English.

The logic is currently in `PicturePreview#calculateFramingRect`. You'll have to override this method in `BarcodeView` to change the position.
