### ISSUE TITLE
How to set orientation is vertical

### ISSUE THREAD

**Issue by punnoket** [journeyapps/zxing-android-embedded#368]
Hello

I would like to ask you some questions in terms of your library. It's working and really great but  I want to know how to setting vertical orientation  because default screen is horzontal.

Thank you for your kindness
Pannawat

**Comment by nandur93** [comment]
See here: https://github.com/journeyapps/zxing-android-embedded#changing-the-orientation

**Comment by momokosa** [comment]
@punnoket 
integrator.setOrientationLocked(false); // horzontal
integrator.setOrientationLocked(true); // vertical 
Close issue please

**Comment by hugey010** [comment]
@nandur93 that method give me manifest merger errors.

I was able to get this functional with all current tools (gradle 5.2.1, androidx, etc.) by using the given [sample](https://github.com/journeyapps/zxing-android-embedded/tree/androidx/sample/src/main/java/example/zxing).

Steps:
* Add zxing dependency like normal:
```
    implementation "com.journeyapps:zxing-android-embedded:3.6.0"
    implementation "com.google.zxing:core:3.3.3"
```
* Create empty activity similar to `AnyOrientationCaptureActivity.java` which extends `CaptureActivity`
* Register this new activity in AndroidManifest:
```
<activity
            android:name=".AnyOrientationCaptureActivity"
            android:screenOrientation="fullSensor"
            android:stateNotNeeded="true"
            android:theme="@style/zxing_CaptureTheme"
            android:windowSoftInputMode="stateAlwaysHidden"></activity>
```
* To launch the scanner activity:
```
IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setCaptureActivity(AnyOrientationCaptureActivity.class);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
        integrator.setPrompt("Scan something");
        integrator.setOrientationLocked(false);
```

Hope it works for you as well!

**Comment by mohammaddvi** [comment]
step 1: (Class)
IntentIntegrator integrator = new IntentIntegrator(this);
    integrator.setPrompt("Scan a barcode");
    integrator.setCameraId(0);  // Use a specific camera of the device
    integrator.setOrientationLocked(true);
    integrator.setBeepEnabled(true);
    integrator.setCaptureActivity(CaptureActivityPortrait.class);
    integrator.initiateScan();

step 2: (Class)
public class QrCodeActivity extends CaptureActivity

step 3: (Manifest)
<activity android:name=".CaptureActivityPortrait"
        android:screenOrientation="portrait"
        android:stateNotNeeded="true"
        android:theme="@style/zxing_CaptureTheme"
        android:windowSoftInputMode="stateAlwaysHidden"></activity>

**Comment by mohammaddvi** [comment]
I have a portrait Qr Code(quick response code) scanner with this solution:

step 1:
IntentIntegrator integrator = new IntentIntegrator(this);
    integrator.setPrompt("Scan a barcode");
    integrator.setCameraId(0);  // Use a specific camera of the device
    integrator.setOrientationLocked(true);
    integrator.setBeepEnabled(true);
    integrator.setCaptureActivity(CaptureActivityPortrait.class);
    integrator.initiateScan();

step 2:

  public class CaptureActivityPortrait extends CaptureActivity {
  }

step 3:
	
<activity android:name=".CaptureActivityPortrait"
        android:screenOrientation="portrait"
        android:stateNotNeeded="true"
        android:theme="@style/zxing_CaptureTheme"
        android:windowSoftInputMode="stateAlwaysHidden"></activity>

Enjoy rest of your lifes...

**Comment by nandur93** [comment]
This issue should be **Closed** as @hugey010 and @mohammaddvi sugesstions are works.

**Comment by alizaidi606** [comment]
There should be an option to set orientation while initiating IntentIntegrator rather creating whole new empty activity.

**Comment by rkistner** [comment]
This is covered by the [docs](https://github.com/journeyapps/zxing-android-embedded#changing-the-orientation) and the comments above.

Unfortunately in Android you need to specify the orientation in the manifest, so this cannot be made fully configurable via the Intent.

**Comment by fgroupindonesia** [comment]
> @nandur93 that method give me manifest merger errors.
> 
> I was able to get this functional with all current tools (gradle 5.2.1, androidx, etc.) by using the given [sample](https://github.com/journeyapps/zxing-android-embedded/tree/androidx/sample/src/main/java/example/zxing).
> 
> Steps:
> 
> * Add zxing dependency like normal:
> 
> ```
>     implementation "com.journeyapps:zxing-android-embedded:3.6.0"
>     implementation "com.google.zxing:core:3.3.3"
> ```
> 
> * Create empty activity similar to `AnyOrientationCaptureActivity.java` which extends `CaptureActivity`
> * Register this new activity in AndroidManifest:
> 
> ```
> <activity
>             android:name=".AnyOrientationCaptureActivity"
>             android:screenOrientation="fullSensor"
>             android:stateNotNeeded="true"
>             android:theme="@style/zxing_CaptureTheme"
>             android:windowSoftInputMode="stateAlwaysHidden"></activity>
> ```
> 
> * To launch the scanner activity:
> 
> ```
> IntentIntegrator integrator = new IntentIntegrator(this);
>         integrator.setCaptureActivity(AnyOrientationCaptureActivity.class);
>         integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
>         integrator.setPrompt("Scan something");
>         integrator.setOrientationLocked(false);
> ```
> 
> Hope it works for you as well!

great.... discussion closed.
