### ISSUE TITLE
View stays black when using multiple DecoratedBarcodeViews

### ISSUE THREAD

**Issue by woodii** [journeyapps/zxing-android-embedded#370]
When i try to use more than one Fragment with DecoratedBarcodeView the SurfaceView on the first tab stays black.
After changing orientation or switching tabs everything works fine.

I could also reproduce the issue with a slightly modified version of your sample project.
Just use two ScanFragments in the SectionsPagerAdapter in TabbedScanning.java.

```
@Override
        public android.support.v4.app.Fragment getItem(int position) {
            if(position == 0) {
                return ScanFragment.newInstance();
            } else {
                return ScanFragment.newInstance();
            }

        }
```

When this happens I also get the following error:

> 02-22 09:37:42.164 20935-20974/example.zxing E/CameraInstance: Failed to configure camera
                                                               java.lang.RuntimeException: getParameters failed (empty parameters)
                                                                   at android.hardware.Camera.native_getParameters(Native Method)
                                                                   at android.hardware.Camera.getParameters(Camera.java:3099)
                                                                   at com.journeyapps.barcodescanner.camera.CameraManager.setParameters(CameraManager.java:379)
                                                                   at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:159)
                                                                   at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:203)
                                                                   at android.os.Handler.handleCallback(Handler.java:836)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                   at android.os.Looper.loop(Looper.java:203)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

Would be glad if you can resolve this issue.
Best regards
woodii

**Which library version are you using?** 3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Gigaset S270 plus (Android 7.0)
Emulator Nexus 6P (Android 8.0)

**Does the same happen on other devices or an emulator?**
both

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
yes with a slightly modified version of your sample

**In the case of an error do you have a stack trace or adb logs?**
https://pastebin.com/q6V75kcn

**Comment by rkistner** [comment]
In general, you'll get that issue when the app tries to open a second camera instance while another one is still in use.

Since this library does camera operations in a background thread, instead of the main thread, this can sometimes be tricky for cases like this. That's why the tabbed example in this project calls `barcodeView.pauseAndWait()` instead of `barcodeView.pause()`.

I can see from your logs that there are two calls to `CameraPreview#resume()` happening shortly after each other. This is not supposed to happen if the tab is not visible. If you can figure out why that is happening, it may help to debug this issue.

**Comment by woodii** [comment]
Thank you for your fast reply.

yeah i had similar ugly issues with the google vision api (which I tried to use before)

Even with `mViewPager.setOffscreenPageLimit(0);` both Fragments are being crated when you open the `TabbedScanning` activity.

The following methods are being called during that:
3x setUserVisibleHint (2x first fragment, 1x second fragment)
2x onCreateView
2x onResume of each fragment which `calls barcodeView.resume()`.

**Comment by woodii** [comment]
I guess a have found a workaround for that problem:

in `setUserVisibleHint` you have to assign a local field.

    private boolean isVisibleToUser = false;

    public void setUserVisibleHint(boolean isVisibleToUser) {
        super.setUserVisibleHint(isVisibleToUser);
        this.isVisibleToUser = isVisibleToUser;
        ...

and check this value in `onResume`

    @Override
    public void onResume() {
        super.onResume();
        if (isVisibleToUser)
            barcodeView.resume();
    }

I have tested this now on 2 different devices and haven't encountered any other problem after changing the screen orientation or minimizing the app.

Thank you for your tip with `resume` ;)

**Comment by Nonononoki** [comment]
@woodii Sorry to bother you, but I have the same problem and can't figure out how to solve it, Do you maybe have a working example to share?

**Comment by rkistner** [comment]
The current Tabs example is working, use that as an example to start with.
