### ISSUE TITLE
QR and 1D codes take to long to read.

### ISSUE THREAD

**Issue by ashx1** [journeyapps/zxing-android-embedded#371]
Hi,

Trying to scan QR and 1D codes take a long time to read from a distance.

1D codes take long to read when close to the camera as well.

Is it possible to make it faster to read or process close up for 1D codes and from a distance for 1D codes and QR codes?

Thanks.

**Comment by rkistner** [comment]
This is not easy to achieve with the library. With some effort you may be able to use different resolutions for different formats (e.g. crop or scale the image down before trying to read the 1D barcode), but I'm not sure if that will improve anything.
