### ISSUE TITLE
What is the supported minSdk for 3.6.0 and core 3.3.2 (14 or 19)?

### ISSUE THREAD

**Issue by plastiv** [journeyapps/zxing-android-embedded#372]
I'm confused what is supported minSdk. Is it a typo at the release notes or `README`?

![image](https://user-images.githubusercontent.com/179550/36986679-b78ece8c-209a-11e8-84c1-11348e36c293.png)

but readme claims the opposite 

![image](https://user-images.githubusercontent.com/179550/36986724-da0236ca-209a-11e8-962d-b9ff69e7b0d1.png)

What should I use to have minSdk14 version?

**Comment by rkistner** [comment]
zxing:core 3.3.1 and later only supports SDK 19+, according to its [release notes](https://github.com/zxing/zxing/releases/tag/zxing-3.3.1).

By default this library uses zxing:core 3.3.2, which also makes it require 19+.

However, you can still downgrade zxing:core to 3.3.0, which makes this library compatible with 14+. For older versions (11+, I think), you have to downgrade to an older version of this library.

I'll update the readme to clarify this.

**Comment by rkistner** [comment]
Fixed the readme, let me know if it's still unclear.
