### ISSUE TITLE
ContinuousCaptureActivity is there a way to get results via onActivityresult?

### ISSUE THREAD

**Issue by ichbindemiurge** [journeyapps/zxing-android-embedded#374]
I'm using the example of ContinuousCaptureActivity but it does not trigger onActivityresult of the activity i called ContinuousCaptureActivity from (main activity).
it only triggers onActivityresult of the main activity if i return to it via back button, not immediately after ContinuousCaptureActivity scanned a barcode.

**Comment by rkistner** [comment]
`onActivityResult` is only called when an Activity is finished, and cannot be called while the Activity is still running. Your main Activity will also be paused for that period, so it can't really receive any data.

There are many other ways to handle the data while it's being scanned, but that's up to your application, and outside the scope of this library.
