### ISSUE TITLE
how to access camera settings?

### ISSUE THREAD

**Issue by ghost** [journeyapps/zxing-android-embedded#376]
#### Description of the problem:
how to access camera setting from" Intent Integrator" in android integration package

**Comment by rkistner** [comment]
You can't really access camera settings from the Intent Integrator, apart from specifying which camera to use. (See all options in the source here: https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/google/zxing/integration/android/IntentIntegrator.java)

Accessing camera settings is outside the scope of this library. You'll have to dig through the source to see what you can do, and will most likely have to make a fork to change the more advanced settings.
