### ISSUE TITLE
how to set request code for each activity 

### ISSUE THREAD

**Issue by kmal47** [journeyapps/zxing-android-embedded#377]
i add one more button to scan another code, but it had conflict as the request code is not set.How to set the request code for each button.Below are my code sample.

    scanBtnModel.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            IntentIntegrator integrator = new IntentIntegrator(activity);
            integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
            integrator.setPrompt("Scan Model Number");
            integrator.setBeepEnabled(false);
            integrator.setCameraId(0);
            integrator.setBarcodeImageEnabled(false);
            integrator.initiateScan();

        }
    });

**Comment by rkistner** [comment]
This changed in 3.6.0. See the sample here: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L37

And handling the results: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L111

**Comment by kmal47** [comment]
I had working on my code. But why setRequestCode method is cannot resolve?



```
public class MainActivity extends AppCompatActivity {


String scannedData;
String scannedData2;
TextView  contentTxt;
TextView  contentTxt2;

Button scanBtnSerial;
Button scanBtnModel;





//Button viewBtn;
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    final Activity activity =this;
    scanBtnSerial = (Button)findViewById(R.id.scan_btn);//to scan serial number
    scanBtnModel = (Button)findViewById(R.id.scan2_btn);//to scan model number

    contentTxt = (TextView)findViewById(R.id.textView);//to view scanned serial number
    contentTxt2 = (TextView)findViewById(R.id.textView3);//to view scanned model number

    final TextView textView=(TextView)findViewById(R.id.textView);


    scanBtnSerial.setOnClickListener(new View.OnClickListener() {

        public void setRequestCode(int requestCode) {
            REQUEST_CODE = requestCode;
        }
        @Override
        public void onClick(View view) {


            IntentIntegrator integrator = new IntentIntegrator(activity);
            integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
            integrator.setPrompt("Scan Model Number");
            integrator.setBeepEnabled(false);
            integrator.setCameraId(0);
            integrator.setBarcodeImageEnabled(false);
            integrator.setRequestCode(1);
            integrator.initiateScan();

        }
    });

    scanBtnModel.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View view) {
            IntentIntegrator integrator = new IntentIntegrator(activity);
            integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
            integrator.setPrompt("Scan Model Number");
            integrator.setBeepEnabled(false);
            integrator.setCameraId(0);
            integrator.setBarcodeImageEnabled(false);
            integrator.setRequestCode(2);
            integrator.initiateScan();
        }
    });


}


@Override
 protected void onActivityResult(int requestCode, int resultCode, Intent 
 data) 
{
    IntentResult result = 
    IntentIntegrator.parseActivityResult(requestCode,resultCode,data);
    if(result!=null) {

            // Here we need to handle scanned data...
            Log.d("MainActivity", "Scanned");
            if(requestCode == 1) { //Again, use a const here
                contentTxt.setText(result.getContents());
                scannedData = result.getContents();
            } else if(requestCode == 2) {
                contentTxt2.setText(result.getContents());
                scannedData2 = result.getContents();
            }
            new SendRequest().execute();//send to database 


    }
    super.onActivityResult(requestCode, resultCode, data);
}
```

**Comment by rkistner** [comment]
Are you sure you're using version 3.6.0?

Also, if you're using that method, you'll need to use this version of `parseActivityResult`:

```
IntentIntegrator.parseActivityResult(resultCode, data);
```

You'll also have to check the requestCode yourself.

**Comment by kmal47** [comment]
Sorry i'm using the  3.3.0 version.So,the implementation is different?

**Comment by rkistner** [comment]
It's not supported in 3.3.0, you'll have to upgrade.

**Comment by kmal47** [comment]
Thanks dude,now i understand.The error is gone!

**Comment by jeredez182** [comment]
hi ! i'm on 3.6.0 but your answer dont fit to me, here is my mainactivity, i just dont see how to set up the requestcode in the last part, to call result 1 from button 1 and result 2 from button 2 in allocated textview...thanks for your help

public class MainActivity extends AppCompatActivity {

    Button btn_scan;
    TextView text_result;
    Button btn_scan2;
    TextView text_result2;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        text_result = findViewById(R.id.text_result);
        text_result2 = findViewById(R.id.text_result2);
      
        findViewById(R.id.btn_scan).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IntentIntegrator integrator = new IntentIntegrator(MainActivity.this);
                integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
                integrator.setPrompt("Scan);
                integrator.setCameraId(0);  // Use a specific camera of the device
                integrator.setBeepEnabled(true);
                integrator.setBarcodeImageEnabled(true);
                integrator.initiateScan();
            }
        });

        findViewById(R.id.btn_scan2).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IntentIntegrator integrator = new IntentIntegrator(MainActivity.this);
                integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
                integrator.setPrompt("Scan");
                integrator.setCameraId(0);  // Use a specific camera of the device
                integrator.setBeepEnabled(true);
                integrator.setBarcodeImageEnabled(true);
                integrator.initiateScan();
            }
        });
      
           }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if(result != null) {
            if(result.getContents() == null) {
                Toast.makeText(this, "cancel", Toast.LENGTH_LONG).show();
            } else {
                //Toast.makeText(this, "scan: " + result.getContents(), Toast.LENGTH_LONG).show();
                text_result.setText(""+result.getContents());
            }
        } else {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
}
