### ISSUE TITLE
Using the integrator.setRequestCode(1); IntentResult result will be null

### ISSUE THREAD

**Issue by thamathar** [journeyapps/zxing-android-embedded#382]
#### Description of the problem:

Hi, I have been calling the camera  with:

```
IntentIntegrator integrator = new IntentIntegrator(this);
integrator.setOrientationLocked(true);
integrator.setPrompt(getString(R.string.documents_barcode_message));
integrator.setBeepEnabled(true);
integrator.initiateScan();
```

and to get the result using 

```
IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
if(result != null)
{
	if(result.getContents() != null)
	{
		_prodCodBarras.setText(result.getContents());
		_prodCodBarras.clearFocus();
		doAfterLeaveCodBarEditText();
		if (TextUtils.equals(GlobalVars.GeneralConfig.get("prodPrecoType"), "1"))
		{
			_prodPreco.requestFocus();
		}
		else
		{
			_prodQtd.requestFocus();
		}
	}
}
else
{
	super.onActivityResult(requestCode, resultCode, data);
}
```
but if I add `integrator.setRequestCode(1);` the `IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);` it will be allways null

I need to grab the codbar by doing this

```
if (resultCode == Activity.RESULT_OK)
{
	String contents = data.getStringExtra("SCAN_RESULT");
}
```
Isn't the purpose of the `integrator.setRequestCode(1);` to be like the `startActivityForResult(intent, 2);` ?

Just notice this issue (love the lib by the way 👍 ) but if the activity as more starts more then 1 Activity and require's information from more then one would be nice not to go manually in sort of speak hehe

The integrator was working at 100% until I needed to add the `setRequestCode` since I need to return a new info from an activity that is started at the same activity as the camera.
**Which library version are you using?** E.g. 3.2.0.
3.6.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Testing o several, Zebra TC20, LG Spirit, Samsung Galaxy S8 and the emulators (API23+)
**Does the same happen on other devices or an emulator?**
Yep
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Provided the code and the reason at the beguining
**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
If you are using `setRequestCode`, you need to use this version of `parseActivityResult`: `IntentIntegrator.parseActivityResult(resultCode, data)`. You also need to have your own check for `requestCode` for this case.

**Comment by jerrychong25** [comment]
> If you are using `setRequestCode`, you need to use this version of `parseActivityResult`: `IntentIntegrator.parseActivityResult(resultCode, data)`. You also need to have your own check for `requestCode` for this case.

Thanks for this solution.

If `scanner.setRequestCode(3)` is used, then need to use
`val result = IntentIntegrator.parseActivityResult(resultCode, data)` for getting QR scan result.
