### ISSUE TITLE
Stuck on landscape mode on view

### ISSUE THREAD

**Issue by cdrandin** [journeyapps/zxing-android-embedded#385]
#### Description of the problem:

When using IntentIntegrator for QR code scanning the orientation is forced to landscape despite following [changing-the-orientation](https://github.com/journeyapps/zxing-android-embedded#changing-the-orientation).

**Which library version are you using?** E.g. 3.2.0.

- zxing:core:3.3.0
- zxing-android-embedded:3.6.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Google Pixel XL

**Does the same happen on other devices or an emulator?**

The same thing happens on emulator

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

I am just following the example on the README.

```
        // Acitivty
        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setOrientationLocked(false);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.QR_CODE);
        integrator.setPrompt("Scan a qr code");
        integrator.initiateScan();

       // Manifest
        <activity
            android:name=".QrScan"
            android:screenOrientation="portrait"
            tools:replace="screenOrientation"></activity>

```

**In the case of an error do you have a stack trace or adb logs?**

I don't notice any odd errors.

**Comment by rkistner** [comment]
The readme could be more clear on this, but you either need to:

1. Override the manifest for the built-in `CaptureActivity` (what the readme does). OR:
2. Create your own Activity, then specify that in the `IntentIntegrator` (what you are doing).

For (2), you need to add this line:

```java
integrator.setCaptureActivity(QrScan.class);
```

**Comment by rkistner** [comment]
What does your `QrScan` Activity look like? It needs to extend from `CaptureActivity`, or implement the scanning in another way.

**Comment by cdrandin** [comment]
It is pretty much an empty view inheriting from `AppCompatActivity`. I did the method you suggested inheriting from `CaptureActivity`, but Android Studio has me import `com.journeyapps.barcodescanner.CaptureActivity`. I get nothing in relation to `com.google.zxing.integration.android.`.

Is there only one way to orientate the scanner?

**Comment by farislivemaker** [comment]
I got a slightly different issue, when using  `integrator.initiateScan();`(ACTIVITY) the orientation is in control portrait/landscape. But when i use `integrator.forFragment(xxxxx.this).initiateScan();`(FRAGMENT) the orientation structs only in landscape mode.

How to make change orientation control for fragment.

**Comment by yusufceylan** [comment]
Same here, when I use integrator.forSupportFragment(xxxxx.this).initiateScan();, I cant control orientation, it stucks landscape mode

**Comment by mehran22k** [comment]
thanks guys.
This library would be great, but since there is no support for portrait mode then it is useless for us

**Comment by hugey010** [comment]
I struggled with this for a bit, but was able to get it working. Added steps here: https://github.com/journeyapps/zxing-android-embedded/issues/368#issuecomment-469307808

**Comment by rkistner** [comment]
Thanks @hugey010.
