### ISSUE TITLE
setScanningRectangle has been deprecated ?

### ISSUE THREAD

**Issue by hyoungtaikkim** [journeyapps/zxing-android-embedded#386]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

    I am trying many versions including 1.9 to 3.6.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

     My app is supposed to run any Android devices from Lollipop to Oreo.

**Does the same happen on other devices or an emulator?**

     Yes.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

         IntentIntegrator scanIntegrator = new IntentIntegrator(QrCodeScannerActivity.this);
        scanIntegrator.setScanningRectangle(404, 184);
       .......

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
You can set the size using `app:zxing_framing_rect_width` and `app:zxing_framing_rect_height` on `BarcodeView`. See the `custom_barcode_scanner.xml` layout example.
