### ISSUE TITLE
How to decode exist picture from phone album

### ISSUE THREAD

**Issue by loveshe9421314** [journeyapps/zxing-android-embedded#387]
I loaded qr code from my phone but 'onActivityResult' reture null.
I had tried .png and .jpg format but 'result.getContents() reture null'
How to solve this problem?

Android Studio: 2.3
compileSdkVersion: 25
buildToolsVersion: 25.0.3
Mobile: Samsung Galaxy S3
Android Version: 4.1.2

**Comment by rkistner** [comment]
That is outside the scope of this library.
