### ISSUE TITLE
Repository on JCenter

### ISSUE THREAD

**Issue by dschuermann** [journeyapps/zxing-android-embedded#39]
Instead of
```
url "http://dl.bintray.com/journeyapps/maven"
```
I would propose using
```
url "https://dl.bintray.com/journeyapps/maven"
```
to prevent MitM attackers injecting a infected version of your library.

BTW: Is there any reason your library is not available on Bintray's JCenter?

**Comment by rkistner** [comment]
Last time I tried I couldn't figure out how to add it to JCenter. I'll try again sometime.

**Comment by dschuermann** [comment]
https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html

**Comment by rkistner** [comment]
It was recently added to JCenter - you can test it now.

The issue previously was that only one of the three packages in the repository was linked, but their support sorted it out.

**Comment by dschuermann** [comment]
Awesome! I cleared all gradle caches and tested it with jcenter only. Works. See https://github.com/open-keychain/open-keychain/commit/8c97bee14cd2a293345c344033cec45cf17ac70b

**Comment by rkistner** [comment]
Thanks for testing - I updated the readme now.
