### ISSUE TITLE
onActivityResult calling before result back from the CaptureActivity

### ISSUE THREAD

**Issue by ola-skorp** [journeyapps/zxing-android-embedded#394]
I have a problem like this https://github.com/journeyapps/zxing-android-embedded/issues/193 in 3.5.0 on tablet, on phone it works well. onActivityResult is called just after IntentIntegrator(activity).setOrientationLocked(false).setCaptureActivity(captureActivity).initiateScan() and before captureActivity.onCreate. My tablet is Galaxy Tab E, android 4.4.4.

**Comment by rkistner** [comment]
Check the adb logs for errors. Other than that, we need more info (source code) to help debug, since this is most likely an issue in your application.

As a side note, please follow the issue template - the info is really required for most issues.

**Comment by ola-skorp** [comment]
Thank you for your answer. I found what was wrong. It depends on android version. 

I cloned code with example MainActivity and tried to get the same behavior.
If android version is 4.4.4 and MainActivity base have singleInstance launch mode, then the following sequence of MainActivity callbacks will be called after initiateScan:
onPause
onActivityResult
onResume
onPause
onStop
---here QR-code was scaned---
onRestart
onStart
onResume

If android version is 5.1 or 7.1 with the same code:
onPause
onStop
---here QR-code was scaned---
onActivityResult
onRestart
onStart
onResume

With launch mode singleTask this problem has gone.
