### ISSUE TITLE
Crash while scanning QR code

### ISSUE THREAD

**Issue by abdulsattar-sit** [journeyapps/zxing-android-embedded#398]
#### Description of the problem:
Application crash while scanning  

**Which library version are you using?** E.g. 3.2.0.
3.5.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Samsung Model: SM-G906K

**Does the same happen on other devices or an emulator?**

Also happening on 
Samsung Model: SM-N910G and SamsungModel: SM-G920I

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

Exception java.lang.OutOfMemoryError: Failed to allocate a 1183756 byte allocation with 1039032 free bytes and 1014KB until OOM
com.journeyapps.barcodescanner.SourceData.rotateCW (SourceData.java:186)
com.journeyapps.barcodescanner.SourceData.rotateCameraPreview (SourceData.java:163)
com.journeyapps.barcodescanner.SourceData.createSource (SourceData.java:102)
com.journeyapps.barcodescanner.DecoderThread.createSource (DecoderThread.java:137)
com.journeyapps.barcodescanner.DecoderThread.decode (DecoderThread.java:145)
com.journeyapps.barcodescanner.DecoderThread.access$000 (DecoderThread.java:22)
com.journeyapps.barcodescanner.DecoderThread$1.handleMessage (DecoderThread.java:38)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:158)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by abdulsattar-sit** [comment]
Can someone please help to resolve this issue?

**Comment by rkistner** [comment]
This looks like a standard OutOfMemoryError, which may or may not be related to this library.

Check with something like [LeakCanary](https://github.com/square/leakcanary) if your application has any memory leaks, or check whether it's just using a lot of memory with a [memory profiler](https://developer.android.com/studio/profile/memory-profiler).

**Comment by lexboss93** [comment]
I have added the following code to avoid memory leaking:
```
public void BarcodeResult(BarcodeResult result)
{
		...
	result.Bitmap.Dispose();
	result.Dispose();
	GC.Collect();
		...
}
```
p.s. it's C#

**Comment by iRYO400** [comment]
@lexboss93 is your fix for Xamarin?

**Comment by lexboss93** [comment]
> @lexboss93 is your fix for Xamarin?

Yes.

**Comment by rkistner** [comment]
Closing this issue. If you find leaks using a memory profile tool or similar, please open a new issue.
