### ISSUE TITLE
Does not scan this aztec image

### ISSUE THREAD

**Issue by manishb-socialcurry** [journeyapps/zxing-android-embedded#399]
Hello there:

I am using library version 3.5.0. I tried to scan the attached images using DecoratedBarcodeView. It failed! Could you please help? Are the images too small?

I went to the online zxing decoder page and uploaded one of these images and the decoder could read it fine.

![q1](https://user-images.githubusercontent.com/37432644/40505714-bb135e68-5fb2-11e8-9a83-7052fd2fab37.png)

![q2](https://user-images.githubusercontent.com/37432644/40505715-bb55e01c-5fb2-11e8-84f4-02b153aa6bd1.png)

![q3](https://user-images.githubusercontent.com/37432644/40505717-bcbf42d6-5fb2-11e8-8931-0138d299bd76.png)

Thanks,
Manish

**Comment by Videl555** [comment]
Thanks

**Comment by rkistner** [comment]
Please follow the issue template - the info there is required before we can help with issues such as these.
