### ISSUE TITLE
setOrientation portait Samsung galaxy SII

### ISSUE THREAD

**Issue by Bmooij** [journeyapps/zxing-android-embedded#40]
Portait mode doesn't work on the Samsung galaxy SII (GT-I9100)  with Android: 2.3.4.
The flowing code is used:
```java
IntentIntegrator i= new IntentIntegrator(this);
i.setOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
i.initiateScan();
```

This does work on the Google Nexus 4 with Android: 5.0.0.

**Comment by rkistner** [comment]
Portrait mode is not supported in the legacy lib, which is used on Android
2.3. You can try the 3.x branch (see readme), which does support portrait
mode on Android 2.3 (but does not support older Android versions at all).

**Comment by Bmooij** [comment]
ok
