### ISSUE TITLE
请问下使用连续模式时，可以设置在一定时间只扫描一次吗

### ISSUE THREAD

**Issue by tx123456** [journeyapps/zxing-android-embedded#400]
我将DecodeMode设置为CONTINUOUS时，可以设置在一两秒之内只扫描一次吗，别一直扫

**Comment by teolemon** [comment]
"Will you be able to scan only once in a certain period of time when using continuous mode?"
"When I set DecodeMode to CONTINUOUS, I can set it to scan only once in a second or two."

**Comment by Tougee** [comment]
@tx123456  [u can try this](https://github.com/Tougee/zxing-android-embedded)

**Comment by rkistner** [comment]
Please post issues in English.

You can add your own logic to ignore results if it the last one is too recent.
