### ISSUE TITLE
Someone ever see this Error?

### ISSUE THREAD

**Issue by luyun181** [journeyapps/zxing-android-embedded#402]
#### Description of the problem:
 E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
 E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
 E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

**Which library version are you using?** 
 3.6.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Android 7.1.2
**Does the same happen on other devices or an emulator?**
yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
This is likely device-specific, and does not indicate an issue in the scanning process.

**Comment by Trojan1988th** [comment]
'final VideoView videoview = (VideoView) findViewById(R.id.videoview);
   	  Uri uri = Uri.parse("android.resource://"+getPackageName()+"/"+R.raw.yourvideo);
         videoview.setVideoURI(uri);
         videoview.start();
         videoview.seekTo(1);
         videoview.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
        	public void onPrepared(MediaPlayer mp) {
        		mp.setLooping(true);
        		}
        		});'

getting same error in Logcat, using the code above
