### ISSUE TITLE
The problem with data being empty when using intentIntegrator.setRequestCode()

### ISSUE THREAD

**Issue by VincentYD** [journeyapps/zxing-android-embedded#403]
#### Description of the problem:

The following code:

IntentIntegrator.forSupportFragment(fragment)
        .setRequestCode(101)
        .setOrientationLocked(false)
        .initiateScan();
IntentResult scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data)

When I used setRequestCode, I couldn't get any scan results(scanResult is null)
Has anyone found a solution to this problem?

**Comment by ashish-coutloot** [comment]
Having same problem

**Comment by rkistner** [comment]
Duplicate of https://github.com/journeyapps/zxing-android-embedded/issues/382 - see the fix there.
