### ISSUE TITLE
Can the camera reuse change the data source

### ISSUE THREAD

**Issue by liupeng110** [journeyapps/zxing-android-embedded#404]
Can the camera reuse change the data source？ 
Scan two dimensional code and video on one side  
How should I modify it？？
能不能复用摄像头,一边扫二维码一边录像

**Comment by rkistner** [comment]
That's not possible at the moment. My best suggestion is to start with a camera stream, and then try to decode the individual frames one by one. You can use this repo as a starting point, but it will require a lot of coding from your side, that I'm not able to assit with.

**Comment by deepakdrs** [comment]
Dear Sir,

Is it we can use this library for business purpose. Is there is any license we have to take from Journeyapps?

**Comment by rkistner** [comment]
@deepakdrs This library is licensed under the Apache 2.0 license (see [COPYING](https://github.com/journeyapps/zxing-android-embedded/blob/master/COPYING)). You are free to use and/or modify it for commercial purposes, but see the license file for full details.

**Comment by deepakdrs** [comment]
Ok Sir I got it. Comes to com.journeyapps:zxing-android-embedded:2.3.0@aar for using this archive file, is their any license from Journeyapps.?
