### ISSUE TITLE
How to get the current status of DecoratedBarcodeView

### ISSUE THREAD

**Issue by apc107** [journeyapps/zxing-android-embedded#410]
#### Description of the problem:
I would like to put one button to toggle decoratedbarcodeview pause() and resume() like what you did to toggle flashlight in sample code but not separated into two buttons.
How can I get the current status of the decoratedbarcodeview to determine whether it's on puase or on resume?

**Which library version are you using?** E.g. 3.2.0.
3.6.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Emulator API 28

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
You can use `decoratedBarcodeView.getBarcodeView().getCameraInstance() != null`: It will be null when it's paused, and present when it's active.
