### ISSUE TITLE
Fail to recognize the QR code second time

### ISSUE THREAD

**Issue by anricheng** [journeyapps/zxing-android-embedded#411]
zxing version:3.5.0;  android version:8.0 xiaomi

zxing recognize a QR code and start a new Activity, do sth and back to zxing scan Activity again,we found zxing can't recognize the QR code anymore;

**Comment by da-na** [comment]
+1
Having the same issue. 
zxing version: 3.6.0
android version 5.0.1
Galaxy note 4

Here's my scenario: the scanner loads correctly the very first time I load BarcodeActivity in my app.
I can scan without any trouble.

Then in my app, when I launch a different activity (from a side menu) the BarcodeActivity that uses barcode scanner is destroyed.

When going again to that BarcodeActivity (from a side menu) the **onCreate** method is triggered and it seems everything should work as it does the first time, but instead I see a blank screen and can't scan, even though everything seems to get setup like the very first time.  

Here's the BarcodeActivity code (minus some irrelevant code)
```
public class BarcodeActivity extends MyActivity {

    private BarcodeView barcodeView;
    private boolean torchOn = false;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_scan);
        initComponents(savedInstanceState);
    }

    @Override
    public void onResume() {
        super.onResume();
        barcodeView.resume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        barcodeView.pause();
    }

    @Override
    protected void sideMenuWillOpen() {
        super.sideMenuWillOpen();
        barcodeView.pause();
    }

    @Override
    protected void sideMenuDidClose() {
        super.sideMenuDidClose();
        barcodeView.resume();
    }

    @SuppressWarnings("UnusedParameters")
    private void initComponents(Bundle savedInstanceState) {
        barcodeView = (BarcodeView) findViewById(R.id.barcodeView);
        barcodeView.setMarginFraction(0.0);
        barcodeView.decodeContinuous(new BarcodeCallback() {
            @Override
            public void barcodeResult(BarcodeResult result) {
                scan(result.getText(), null);
            }

            @Override
            public void possibleResultPoints(List<ResultPoint> resultPoints) {}
        });

        ((ViewfinderView) findViewById(R.id.viewfinderView)).setCameraPreview(barcodeView);

        if (MyApp.hasCameraFlash()) {
            findViewById(R.id.torchToggle).setVisibility(View.VISIBLE);
        }
    }

    private void scan(String ticketBarcode, String ticketNumber) {
        barcodeView.pause();
        // (...) some API calls
    }

    @SuppressWarnings({ "UnusedParameters", "unused" })
    public void onTorchToggleClick(View view) {
        torchOn = !torchOn;
        barcodeView.setTorch(torchOn);
    }

}
```

Please help verifying why on the second launch the Activity doesn't load the barcode scanner correctly. Thanks!

**Comment by rkistner** [comment]
Not enough info here to see what is wrong. The logs may include an error with details. Otherwise try working from the existing samples, which should all be working.
