### ISSUE TITLE
Can only barcode scan be allowed? Or only two-dimensional code scanning is allowed?

### ISSUE THREAD

**Issue by LXLYHM** [journeyapps/zxing-android-embedded#414]
#### Description of the problem:
hello!
Can only barcode scan be allowed? Or only two-dimensional code scanning is allowed?Can you provide an outsourcing call method that only supports barcode scanning (no scanning of qr codes)?

可以只允许条形码扫描吗？或者只允许二维码扫描？能否提供仅支持条形码扫描（禁止扫描二维码）的外包调用方法？
**Which library version are you using?** E.g. 3.2.0.
3.6.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
See the samples for how to set the barcodes decoders to be used.
