### ISSUE TITLE
Program type already present: com.google.zxing.client.android.camera.open.OpenCameraInterface

### ISSUE THREAD

**Issue by NateZ7** [journeyapps/zxing-android-embedded#415]
#### Description of the problem:

In my gradle file, I have the following imports -

```
    implementation 'com.dlazaro66.qrcodereaderview:qrcodereaderview:2.0.2'
    implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.0'
```
I know that the first library is using ZXING, but I need to be able to use both libs.
When using both libs, compiling gets me the following error - 

`Program type already present: com.google.zxing.client.android.camera.open.OpenCameraInterface
`
Which library version are you using? **3.6.0**

Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0) - **Galaxy S6**

Does the same happen on other devices or an emulator? **Yes**

Any help will be appreciated, cheers!

**Comment by rkistner** [comment]
No known workaround for this - you can't have two copies of the same class in an Android application.

**Comment by khaliqdadmohmand** [comment]
press Ctrl+N and search for ChecksumException to see which classes are same..
