### ISSUE TITLE
Insecure Temporary File (CWE ID 377)(Time and State)

### ISSUE THREAD

**Issue by Dharmaraj-Rupakheti** [journeyapps/zxing-android-embedded#416]
**#### Description of the problem:**

We are using Journeyapps/Zxing Android Embedded library (com.journeyapps:zxing-android-embedded: **3.6.0** ) on our project. And We did Vera Code (Ref: https://www.veracode.com ) Scan to find out the flaws and fix them. And We got the Insecure Temporary File (CWE ID 377)(Time and State) flaw on **CaptureManager.java (Line Number: 360)**. It is producing by creating and using insecure temporary files and which can leave application and system data vulnerable to attack.

**Current Code, which produce this flaw**
File bitmapFile = File.createTempFile("barcodeimage", ".jpg", activity.getCacheDir());

**Recommendations**
Ensure that unpredictable names are used for temporary files and that files are created in a secure directory with appropriate permissions. Using mkstemp() is a reasonably safe way to create temporary files. It will attempt to create and open a unique file based on a filename template provided by the user, combined with a series of randomly generated characters. Note that mkstemp() is safe if only the descriptor is used and the returned filename is not used in a subsequent function call with extra privileges. Using mkstemp() does not completely eliminate race conditions but does provide better protection than other methods. (Taking reference from Vera Code Scan Report Recommendation).

**Which library version are you using?** 
-> 3.6.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
-> Samsung Galaxy S7

**Does the same happen on other devices or an emulator?**
-> Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
-> We have issue from this library and we have following details to check the code to produce this flaw.

**File Name :** CaptureManager.java  And **Line Number:** 360
**Current Code, which produce this flaw**
File bitmapFile = File.createTempFile("barcodeimage", ".jpg", activity.getCacheDir());

Can you guys please help to fix this issue ? I know, we can use the temporary Mitigation action (https://help.veracode.com/reader/DGHxSJy3Gn3gtuSIN2jkRQ/~p4MSKOS8F8X8h0KwFTKoQ) But I think, this is not good idea to avoid the issue instead of fix, if possible. Thanks!

**Comment by rkistner** [comment]
I do not view this as a security issue, and do not trust results from a purely automatic code analysis in general.

> Ensure that unpredictable names are used for temporary files and that files are created in a secure directory with appropriate permissions.

 `getCacheDir()` returns a folder that is only accessible to the application itself, so it is already a secure directory.

If you can demonstrate what the actual security impact is, we can look into it further.

**Comment by Dharmaraj-Rupakheti** [comment]
Sure, Make sense. Thanks @rkistner for the quick response.
