### ISSUE TITLE
What is default error correction rate of DecoratedBarcodeView generated from DefaultDecoderFactory?

### ISSUE THREAD

**Issue by cyberrob** [journeyapps/zxing-android-embedded#421]
#### Description of the problem:

**Which library version are you using?** 
```
implementation 'me.dm7.barcodescanner:zxing:1.9.8'
implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
```

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Nexus 5X on Android 8.1.0

I've readed https://github.com/journeyapps/zxing-android-embedded/blob/master/EMBEDDING.md

I'm using DecoratedBarcodeView in my activity. The scanner works just fine. But I'd like to know what's the DEFAULT error correction rate with code like this:

```kotlin
val formats= arrayListOf(BarcodeFormat.QR_CODE, BarcodeFormat.CODE_39)
barcodeScanner.barcodeView.decoderFactory = DefaultDecoderFactory(formats, null, null, Intents.Scan.MIXED_SCAN)
barcodeScanner.decodeContinuous(barcodeCallback)

```

And is it possible to change error correction rate? Thanks.

**Comment by rkistner** [comment]
Error correction level is only relevant when generating barcodes, not when scanning.
