### ISSUE TITLE
Run from Fragment

### ISSUE THREAD

**Issue by khoshbin** [journeyapps/zxing-android-embedded#422]
#### Description of the problem:

Hi there 
At first I called this from my fragment and it worked perfectly:
 IntentIntegrator.forSupportFragment(this).initiateScan();

Now I want to customize it like: 

       IntentIntegrator integrator = new IntentIntegrator(getActivity());
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ALL_CODE_TYPES);
        integrator.setPrompt("Scan Barcode");
        integrator.setCameraId(0);
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(false);
        integrator.initiateScan();

How can I configure the integrator and then call it from my fragment instead of activity?

Thank you very much

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Just start with `IntentIntegrator integrator = IntentIntegrator.forSupportFragment(this)`, then continue with the configuration as you had it.

**Comment by LXLYHM** [comment]
can see：https://blog.csdn.net/ggy2l/article/details/78656635?locationNum=9&fps=1
