### ISSUE TITLE
IntentIntegrator always returns result -1

### ISSUE THREAD

**Issue by vebut** [journeyapps/zxing-android-embedded#424]
First of all, I'm far from an Android professional when it comes to programming so I hope this is actually an issue worth reporting, but I felt it being strange that the result code is "error" when it should be "success" for a successful qr-code detection and data read.

This is my findings;

#### Description of the problem:
Initializing a new `IntentIntegrator` and then scanning a QR-code always returns -1 (error), even if the data is complete and has been read successfully.

**Which library version are you using?**
```
implementation "com.journeyapps:zxing-android-embedded:3.6.0"
implementation "com.google.zxing:core:3.3.3"
```

**Which phone/tablet are you using, and which Android version does it run?**
Samsung Galaxy S7 (Android 8.0.0), OnePlus 6 (Android 8.1.0)

**Does the same happen on other devices or an emulator?**
I've only tested the two devices.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
```java
// Initializer
IntentIntegrator qrScannerIntent = new IntentIntegrator(this);
qrScannerIntent.setBeepEnabled(false);
qrScannerIntent.setPrompt("");
qrScannerIntent.setRequestCode(REQUEST_QRCODE_SCAN); // 55
qrScannerIntent.initiateScan();

// This doesn't work as described by your documentation
protected void onActivityResult (int requestCode, int resultCode, Intent data)
{
    if (requestCode == REQUEST_QRCODE_SCAN) {
        // resultCode is always -1, as such intentResult is always null too
        IntentResult intentResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
    }
}

// Solution is to do this instead;
protected void onActivityResult (int requestCode, int resultCode, Intent data)
{
    // QR code scan?
    if (requestCode == REQUEST_QRCODE_SCAN) {
        if (!data.hasExtra(Intents.Scan.RESULT)) {
            return;
        }

        String qrCodeResult = data.getStringExtra(Intents.Scan.RESULT);
        if (qrCodeResult.length() == 0) {
            return;
        }

        // Works!! qrCodeResult contains the data from the QR code, even if resultCode is -1!
    }
}
```

**Comment by SvenCarstensen** [comment]
Same problem here.
Has anyone solved this?

**Comment by vebut** [comment]
@SvenCarstensen I provided a solution in the code. Just do that and you'll be good. It'll work now and after the bug is fixed.

**Comment by lancecontreras** [comment]
Where did you get the value of REQUEST_QRCODE_SCAN from? For me the request code is 49374.

**Comment by vebut** [comment]
I'm not by the computer now and it was a while since I reported this, but I think that is my activity request code, it will be different depending on your implementation, you decide it's value to determine what result is being passed to onActivityResult().

**Comment by lancecontreras** [comment]
Just to clarify -1 does not mean error. -1 is equivalent to Activity.RESULT_OK. But thanks for the solution @vebut, I've been pulling my hair the whole day!

Here's what's weird, the code you provided above is that same exact code I tried, it works fine when I'm using java but when in a kotlin activity that's when I get the issue. The only difference I think is that in my java code, I passed in MyActivity.this in the contructor parameter of IntentIntegrator instead of just passing 'this'.  

Didn't really get it, there must be something that's going on here.

**Comment by jeppsson** [comment]
I had similar problem. My problem was that I called `IntentIntegrator.parseActivityResult()` with `intent` as argument and not `data` from `onActivityResult()`.

In Kotlin:
```
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        val scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, data)
        if (scanResult != null) {
            AlertDialog.Builder(this)
                .setMessage(scanResult.toString())
                .show()
        } else {
            super.onActivityResult(requestCode, resultCode, data)
        }
    }
```

**Comment by rkistner** [comment]
If you change the requestCode, you have to use the `parseActivityResult(resultCode, data)` method (the version without the requestCode parameter).

**Comment by xrpdevs** [comment]
> If you change the requestCode, you have to use the `parseActivityResult(resultCode, data)` method (the version without the requestCode parameter).

Thanks for this, I wasted hours this evening due to this... Onwards and upwards!
