### ISSUE TITLE
Generate Barcode Padding

### ISSUE THREAD

**Issue by nguyenlinhnttu** [journeyapps/zxing-android-embedded#427]
#### Description of the problem:
Can you help me Generate QR_Code full size. Current it include padding.

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by BestCoderXQX** [comment]
/**
     * 删除二维码的空白区域
     * @param matrix
     * @return
     */
    public static BitMatrix deleteWhite(BitMatrix matrix)
    {
        int[] rec = matrix.getEnclosingRectangle();
        //数字2  代表了留的空白区域的大小
        int resWidth = rec[2] + 2;
        int resHeight = rec[3] + 2;
        BitMatrix resMatrix = new BitMatrix(resWidth, resHeight);
        resMatrix.clear();
        for (int i = 2; i < resWidth; i++)
        {
            for (int j = 2; j < resHeight; j++)
            {
                if(matrix.get(i+rec[0],j+rec[1]))
                    resMatrix.set(i,j);
            }
        }
        return resMatrix;
    }

**Comment by rkistner** [comment]
Customizing the encoded image is outside the scope of this library. You can copy and modify the code, as posted above.
