### ISSUE TITLE
Unable-to-scan barcode exmples

### ISSUE THREAD

**Issue by FaranegarMobile** [journeyapps/zxing-android-embedded#428]
The barcode scanner doesn't scan these barcodes. We tried on a wide variety of Android versions and smartphones. It didn't work. Can anybody give me some information about these kinds of barcodes?

Thanks in advance.

**Which library version are you using?**  3.6.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0, Samsung Galaxy s9 Android 8.0)**

**Does the same happen on other devices or an emulator?**

![photo_2018-09-24_09-11-05](https://user-images.githubusercontent.com/39724430/45938766-e1afbf80-bfd9-11e8-8a82-e1fdcfc2d822.jpg)
![photo_2018-09-24_09-11-21](https://user-images.githubusercontent.com/39724430/45938767-e1afbf80-bfd9-11e8-81d7-9bc65eaa7f7c.jpg)
![photo_2018-09-24_09-11-24](https://user-images.githubusercontent.com/39724430/45938768-e2485600-bfd9-11e8-823c-f01bb104850c.jpg)

**Comment by rkistner** [comment]
These appear to be PDF417 barcodes. I could also not scan these using the Barcode Scanner application - not sure if it's an issue with the decoder or something different in the barcodes.

I'd recommend trying a commercial library such as https://microblink.com/products/pdf417 for PDF417 barcodes.
