### ISSUE TITLE
functionality possible only use half of the screen

### ISSUE THREAD

**Issue by daisylassie** [journeyapps/zxing-android-embedded#43]
hi ralf,
i am currently looking for an easy integration possibility of zxing.

we have to realize: 
only use half of the screen for camera preview, scan more than one barcode in a loop and display on the bottom of the screen productdata to the barcode.

my questions are: 

a) is this possible with your solution and 
b) when will it be available and stable about?

thx a lot, daisy

**Comment by rkistner** [comment]
Yes, it is possible, but will require some work from your side.

You will need to use the 3.x branch. There may still be some API changes
before the final release, but the functionally is already there.

If I remember correctly there is already a sample that does continuous
scanning, and displays the scanned barcode below the preview. The product
data lookup you'll have to do yourself.
