### ISSUE TITLE
In Depth details to issue : Pause scanning in continuous capture mode #71

### ISSUE THREAD

**Issue by Deinos23** [journeyapps/zxing-android-embedded#430]
Hi there, 
first of all thank you very much for your awesome project!

I'm trying to do pretty much the same what buddhasaikia here asked for in "https://github.com/journeyapps/zxing-android-embedded/issues/71" .

Layoutwise I'd love to create something like the Zxing App in "https://play.google.com/store/apps/details?id=com.google.zxing.client.android ".
Namely showing the picture, content and overlaying this after scanning without stopping the camera,
now I do not completely comprehend your Reply to the first issuer, I'm still fairly new to Android.

So my Question:
How do I start Single Scans without it automatically returning to the calling activity or otherwise how would I stop Continuous Scans without stopping the Camera?
Sorry if I'm asking something obvious but so far with all the googling and looking through the sample codes I didn't find a solution to this myself yet.

**Comment by jgavazzisp** [comment]
Hello, one solution could be using this code as template:

https://github.com/journeyapps/zxing-android-embedded/blob/aec45c4f10e3769d7449bcb7b82b5d09689512a4/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

but replace line 65:
`barcodeView.decodeContinuous(callback);`

for this instead:
`barcodeView.decodeSingle(callback);`

So it will capture the qr code and keep the action open, however, it will stop to decode future qr codes.

**Comment by buddhasaikia** [comment]
This might help you
https://stackoverflow.com/questions/31761832/how-to-stop-continuous-scanning-by-zxing-android-embedded-in-android
