### ISSUE TITLE
Access denied finding property "camera.aux.packagelist"

### ISSUE THREAD

**Issue by Rajib-Sarwar** [journeyapps/zxing-android-embedded#431]
#### Description of the problem:

Nothing is happening after scanning QRCode. I am just getting the following error:
`Access denied finding property "camera.aux.packagelist"`

Using library **com.journeyapps:zxing-android-embedded:3.6.0**
Using **Vivo V9  Funtouch OS** Android version **8.1.0**

Here is the log:
```
D/Camera: release finalizeCamera
V/Camera: sendReleaseCameraBroadCast mIsNormalCamera = true
D/Camera: closeFlashlightService package name io.shoffrstoreboard
W/CameraThread: type=1400 audit(0.0:6884): avc: denied { open } for path="/dev/__properties__/u:object_r:camera_prop:s0" dev="tmpfs" ino=14398 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "camera.aux.packagelist"
D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=CaptureActivityPortrait, firebase_previous_id(_pi)=-7282452548712047663, firebase_screen_class(_sc)=StoreListActivity, firebase_screen_id(_si)=-7282452548712047665}]
V/FA: Activity resumed, time: 56421652
```

**Comment by rkistner** [comment]
This looks like an issue with the specific device or application. Does scanning work with the sample application or the [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) app?

**Comment by muqeemht** [comment]
did you guys solve this problem?, I am also facing this issue.

**Comment by marcelamelobh** [comment]
The same error also happens to me, in some devices, when I try to scan a bar code.

```
W/CameraThread: type=1400 audit(0.0:150997): avc: denied { read } for name="u:object_r:nvram_country_prop:s0" dev="tmpfs" ino=490 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:nvram_country_prop:s0 tclass=file permissive=0
E/libc: Access denied finding property "ro.camera.sound.forced"
E/libc: Access denied finding property "camera.hal1.packagelist"
```

**Comment by miralas** [comment]
I have the same issue in my app. Barcode Scanner app works like a charm. It's seems to be a hardware problem(probably autofocus)

**Comment by DarshanPatel23** [comment]
I have to face the same issue in MI A1 device but not using this library.

My solution is to use the below code in your manifest 

`<application>
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
</application>`

It was solved my Access denied finding property "camera.aux.packagelist" issue.

**Comment by rkistner** [comment]
Closing this issue, as it is device-specific, and probably doesn't affect the actual scanning.

**Comment by pawellrus** [comment]
I have the same problem on OnePlus 8T Pro.
Other scanners app from store work fine.

**Comment by zhubinsheng** [comment]
这个问题应该被重新打开和找出原因，大概率还是代码问题
