### ISSUE TITLE
BarcodeView Framing rect width attribute not working

### ISSUE THREAD

**Issue by amadeu01** [journeyapps/zxing-android-embedded#432]
#### Description of the problem:

```xml
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.journeyapps.barcodescanner.BarcodeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_barcode_surface"
        app:zxing_framing_rect_width="350dp"
        app:zxing_framing_rect_height="50dp"/>

    [...]

</merge>
```

Regardless of the values I put on `app:zxing_framing_rect_width="350dp"` and `app:zxing_framing_rect_height="50dp"`, the size of the frame does not change.
And, if I use only one value, like `app:zxing_framing_rect_height="50dp"`and erase the other attribute. It is like both of them does not exist. I checked the source code and it seems that the attributes are never used. So, what is the expected behaviour of these attrubutes `app:zxing_framing_rect_height` and `app:zxing_framing_rect_width`?

**Which library version are you using?**  3.6.0.

**Which phone/tablet are you using, and which Android version does it run?**   Samsung Galaxy A3, Android 5.0

**Does the same happen on other devices or an emulator?** I have not checked on the emulator.

**In the case of an error do you have a stack trace or adb logs?** It has no logs.

**Comment by rkistner** [comment]
The values are used here: https://github.com/journeyapps/zxing-android-embedded/blob/aec45c4f10e3769d7449bcb7b82b5d09689512a4/zxing-android-embedded/src/com/journeyapps/barcodescanner/CameraPreview.java#L279

Setting the values does have an effect in the sample app (Custom Scanner Activity button).

**Comment by amadeu01** [comment]
@rkistner It works indeed. Sorry for the inconvenience.
I might have done some mistake

**Comment by amadeu01** [comment]
However, if I use only the `zxing_framing_rect_height`. It does not change the height size

**Comment by amadeu01** [comment]
![image](https://user-images.githubusercontent.com/11631092/46965871-5bd7df00-d082-11e8-9b51-0df8cb3efd4c.png)


```xml
<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:tools="http://schemas.android.com/tools"
       xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.journeyapps.barcodescanner.BarcodeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_barcode_surface"
        app:zxing_framing_rect_height="10dp"/>

    <com.journeyapps.barcodescanner.ViewfinderView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_viewfinder_view"
        app:zxing_possible_result_points="@color/zxing_custom_possible_result_points"
        app:zxing_result_view="@color/zxing_custom_result_view"
        app:zxing_viewfinder_laser="@color/zxing_custom_viewfinder_laser"
        app:zxing_viewfinder_mask="@color/zxing_custom_viewfinder_mask"/>

    <TextView
        android:id="@+id/zxing_status_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal"
        android:background="@color/zxing_transparent"
        android:text="@string/zxing_msg_default_status"
        android:textColor="@color/zxing_status_text"/>

</merge>

```

I used `app:zxing_framing_rect_height="10dp"`, but it did not change the height

**Comment by rkistner** [comment]
Yes - you do need to specify both at the moment.

**Comment by amadeu01** [comment]
@rkistner I will use the same thread. But, it is not really related to this.
Can I change the attributes dynamically? programmatically?
Like, can I change the mask colour programmatically? Is that possible to change `app:zxing_viewfinder_mask="@color/zxing_custom_viewfinder_mask"/>` programmatically ?

**Comment by krishan3421** [comment]
I am not getting rectangle frame from above code. please suggest

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.journeyapps.barcodescanner.BarcodeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/barcode_view"
        app:zxing_framing_rect_width="350dp"
        app:zxing_framing_rect_height="50dp" />

    <com.journeyapps.barcodescanner.ViewfinderView
        android:layout_width="200dp"
        android:layout_height="200dp"
        android:id="@+id/zxing_viewfinder_view"
        android:layout_centerInParent="true"
        app:zxing_possible_result_points="@color/zxing_custom_possible_result_points"
        app:zxing_result_view="@color/zxing_custom_result_view"
        app:zxing_viewfinder_laser="@color/zxing_custom_viewfinder_laser"
        app:zxing_viewfinder_mask="@color/zxing_custom_viewfinder_mask"/>
     <ImageView
         android:id="@+id/img_flash"
         android:layout_margin="16dp"
         android:layout_alignParentBottom="true"
         android:src="@drawable/flash_off"
         android:layout_width="wrap_content"
         android:layout_height="wrap_content" />

</RelativeLayout>

**Comment by amadeu01** [comment]
I haven't used this for a while. So, I'll close this issue.
