### ISSUE TITLE
Can I use this with androidx?

### ISSUE THREAD

**Issue by ehammo** [journeyapps/zxing-android-embedded#439]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Not yet, but a new release will be done soon for androidx.

**Comment by DummyCo** [comment]
@ehammo @rkistner Basically you're still free to use any libraries containing support dependencies thanks to Jetifier (tool to automatically migrate binaries to X):
```
android.useAndroidX=true
android.enableJetifier=true
```
And from my experience it works well with zxing too.

**Comment by octohub** [comment]
Be sure to use `forSupportFragment` instead of `forFragment` if you are using the androidx libraries.

**Comment by rkistner** [comment]
Version 4.0.2 now uses androidx.

**Comment by massivemadness** [comment]
@rkistner No, it's not. `CaptureManager` still uses support libraries
<img width="401" alt="Снимок экрана 2020-10-05 в 16 29 13" src="https://user-images.githubusercontent.com/7825871/95085484-f62a0500-0727-11eb-9d8c-d07c5b3c942c.png">
