### ISSUE TITLE
Custom UI

### ISSUE THREAD

**Issue by bakar517** [journeyapps/zxing-android-embedded#440]
Hi,
Is it possible to add custom rectangle/ give custom background to camera Preview of BarcodeView ?
I found a solution in which we add a View with fix width and height as well as fix "**zxing_framing_rect_height**" and "**zxing_framing_rect_width**" but i don't want to fix it, is there any other solution ?
![a1](https://user-images.githubusercontent.com/44984924/48377841-af286600-e6f0-11e8-9591-0a33aa429544.png)

**Comment by rkistner** [comment]
You can get that sizes from the `BarcodeView` instance, but it requires some scaling. See:

https://github.com/journeyapps/zxing-android-embedded/blob/6556f815584f921e21bb088d2f6423baa99d0547/zxing-android-embedded/src/com/journeyapps/barcodescanner/ViewfinderView.java#L95
https://github.com/journeyapps/zxing-android-embedded/blob/6556f815584f921e21bb088d2f6423baa99d0547/zxing-android-embedded/src/com/journeyapps/barcodescanner/ViewfinderView.java#L171

It may be easier to just create a copy of ViewfinderView and modify it directly. If you extend from ViewfinderView, you can create a custom layout for DecoratedBarcodeView and reference it:
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/res/layout/custom_barcode_scanner.xml

Alternatively, just create your own copy of DecoratedBarcodeView as well.

**Comment by bakar517** [comment]
Thanks for help.
is possible to change place of string message. I mean to place under camera preview instead bottom or top of parent layout ?

**Comment by rkistner** [comment]
Yes - if you modify the layout for ViewfinderView - same process as in my previous comment.

**Comment by bakar517** [comment]
Can you tell me about method name where i can see about textView as you mention chunk of code in your previous comment
