### ISSUE TITLE
decode*(callback) not called

### ISSUE THREAD

**Issue by drindt** [journeyapps/zxing-android-embedded#441]
#### Description of the problem:
The callback decoratedBarcodeView.decodeSingle(callback); i set is not called. When i debug the application it works as expected.

**Which library version are you using?** E.g. 3.2.0.

3.6.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Nexus 6P

**Does the same happen on other devices or an emulator?**

yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

`@EActivity(R.layout.activity_scan)
public class ScanActivity extends AppCompatActivity {

    @ViewById(R.id.zxing_barcode_scanner)
    DecoratedBarcodeView decoratedBarcodeView;

    private BarcodeCallback callback = new BarcodeCallback() {

        @Override
        public void barcodeResult(BarcodeResult result) {
            Log.d(getClass().getSimpleName(), "BarcodeResult: " + result);
            Log.d(getClass().getSimpleName(), "Result: " + result.getResult().getText());
        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
            Log.d(getClass().getSimpleName(), "Result Points: " + resultPoints);
        }
    };

    @Override
    protected void onStart() {
        super.onStart();
        Collection<BarcodeFormat> formats = Arrays.asList(
                BarcodeFormat.QR_CODE,
                BarcodeFormat.DATA_MATRIX,
                BarcodeFormat.ITF
        );
        decoratedBarcodeView.getBarcodeView().setDecoderFactory(new DefaultDecoderFactory(formats));
        decoratedBarcodeView.decodeSingle(callback);
    }

    @Override
    protected void onResume() {
        super.onResume();
        decoratedBarcodeView.resume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        decoratedBarcodeView.pause();
    }
}
`

**Comment by darienalvarez** [comment]
did you find any way to solve the issue?

**Comment by rkistner** [comment]
It's difficult to tell from the sample code what the issue could be. My best suggestion is to use the sample project as a reference, and go further from there.
