### ISSUE TITLE
zxing3.6.0 / support:appcompat-v7 error...

### ISSUE THREAD

**Issue by YoonHo-Lee** [journeyapps/zxing-android-embedded#442]
#### Description of the problem:

I try...

- Create New Project 
- target sdk version 28, min sdk version 19
- compile sdk version 28
- insert gradle dependencies :  implementation 'com.journeyapps:zxing-android-embedded:3.6.0'

- implementation 'com.android.support:appcompat-v7:28.0.0' <-Error....

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 25.3.1. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:support-media-compat:25.3.1 less... (⌘F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).

How can fix...??? T_T

```apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.yoonho.jitest"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'     // <-Error Here!!!
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
}

```

**Which library version are you using?** E.g. 3.6.0.

**Which phone/tablet are you using, and which Android version does it run? ** galaxy s4

**Does the same happen on other devices or an emulator?** same happen on other emulator

**Comment by ricustr** [comment]
Hi, I have the same error on my project, can someone help with this. Thanks.

**Comment by solusoftek** [comment]
implementation 'com.journeyapps:zxing-android-embedded:3.6.0@aar' <-- should remove the conflict

**Comment by amplified22** [comment]
> implementation 'com.journeyapps:zxing-android-embedded:3.6.0@aar' <-- should remove the conflict

Hi there Solusoftek. Your suggestion has certainly removed my error. Can you give me an idea what @aar actually does?

**Comment by solusoftek** [comment]
Hi, I think the @aar annotation implements a compiled binary, while without that annotation it drops a copy of the repository to be compiled with your project and that's where the error appears

**Comment by rkistner** [comment]
The main library is an aar file anyway, even without the `@aar` annotation. I suspect that specifying explicitly does roughly the same as this:

```
implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
```

Which basically says "use this library, but none of its dependencies".

**Comment by amplified22** [comment]
So then we can conclude that it was the dependencies that were incompatible with my SDK 28.0 that was not allowing my gradle to sync correctly. Thanks for letting us know about the fix solusoftek and thanks for the explanation rkistner!

**Comment by jonathan3087** [comment]
'@aar' didn't work for me.

**Comment by jonathan3087** [comment]
> Hi, I have the same error on my project, can someone help with this. Thanks.

Did you ever get a resolution?  Or did you switch to a different library?

**Comment by solusoftek** [comment]
implementation ('com.journeyapps:zxing-android-embedded:3.6.0@aar') { transitive = false }  should be zxing-android-embedded:3.6.0 witouth aar

**Comment by jonathan3087** [comment]
implementation ('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
implementation 'com.google.zxing:core:3.3.2'

Still doesn't work for me. :(

**Comment by jonathan3087** [comment]
I'm probably going to just go back to SDK 27 and forget about it.  Wasted too much of my time so far.

**Comment by solusoftek** [comment]
> I'm probably going to just go back to SDK 27 and forget about it. Wasted too much of my time so far.

Im not an Expert on this library, but implementing the core its only necessary if you traied to add this for Minor SDK than 23, 
I think you've got tangled up and I recommend you to do cleanup your project and sync again, or even invalidate cache, i use androidX SDK 28 and its work like a charm

**Comment by amplified22** [comment]
I had a similar issue which was not quite like the first. Turning off the
transitive removed a lot of required dependencies. In fact - so much that I
couldn't get the project to compile.
I got past it by reverting my target SDK to 23, syncing, cleaning project
and rebuilding.
See if that works for you.

**Comment by rkistner** [comment]
v4.0.0 uses SDK version 28, so there shouldn't be any issues. If you still run into issues after trying the suggestions in this thread, or upgrading to v4.0.0, open another issue with a small sample project showing the issue.
