### ISSUE TITLE
Only rotate camera can recognize the qrcode

### ISSUE THREAD

**Issue by xxss0903** [journeyapps/zxing-android-embedded#444]
#### Description of the problem:
I have to rotate my device then can quickly recognize the qrcode image.
If face straight vertical to the qrcode can very hardly scan the result.
![qrcode](https://user-images.githubusercontent.com/10261567/49095949-79fd4580-f2a4-11e8-8c5b-75a98c81c4da.png)

**Which library version are you using?** E.g. 3.2.0.
3.3.3

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Everyone i have

**Does the same happen on other devices or an emulator?**
yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**
I debug the Detector and find when i go to processFinderPatternInfo and get a wrong qrcode version, it supposed to be 9,but it actually is 8.

**Comment by NicReich** [comment]
I’ve had the same issue. I used this for a school project and the qr reader scans immediately after a screen rotation. I thought is was because I was using it to scan a display connected to raspberry pi running Android things. Nonetheless, I had the same issue

**Comment by xxss0903** [comment]
> I’ve had the same issue. I used this for a school project and the qr reader scans immediately after a screen rotation. I thought is was because I was using it to scan a display connected to raspberry pi running Android things. Nonetheless, I had the same issue

I found if rotate BitMatrix data by rotate180 function in Decoder toBitmap() function, it can get result very quickly.

**Comment by rkistner** [comment]
zxing:core 3.4.0 has some improvements for QR codes scanning. Please open an issue again if you still have trouble after upgrading.

**Comment by stud0709** [comment]
same problem as of 3.5.0 as described here: https://stackoverflow.com/questions/73624155/zxing-problems-reading-qr-code-in-portrait-landscape
