### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by Mr-ARBN** [journeyapps/zxing-android-embedded#447]
while i want to sync project, i get this errors.
i search in whole project and i didn't find the missing files.
what to do?

> Android resource linking failed
Output:  C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:199: error: resource android:attr/fontVariationSettings not found.
C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:200: error: resource android:attr/ttcIndex not found.
error: failed linking references.
Command: C:\Users\---\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\f5e5d80de833e9e3d8fae41238c82013\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        D:\Programing\SDK\platforms\android-27\android.jar\
        --manifest\
        C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml\
        -o\
        C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\processed_res\debug\processDebugResources\out\resources-debug.ap_\
        -R\
        @C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\incremental\processDebugResources\resources-list-for-resources-debug.ap_.txt\
        --auto-add-overlay\
        --java\
        C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\
        --custom-package\
        example.zxing\
        -0\
        apk\
        --output-text-symbols\
        C:\Users\---\zxing-android-embedded-3.6.0\sample-nosupport\build\intermediates\symbols\debug\R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0

**Comment by dharmadev108** [comment]
My guess is there must be something wrong with at least one of your XMLs.

I'll give it a look asap :)

**Comment by rkistner** [comment]
If you still run into this issue after doing a clean build, try to reduce the issue to a small sample project that demonstrates it.

**Comment by sudeqiangxx** [comment]
I also encountered the same problem，May be com.android.support:support-v4:27.1.1  Caused by the
