### ISSUE TITLE
Bar-code library scans irrelevant bar-code values in some cases

### ISSUE THREAD

**Issue by Vikram-rattletech** [journeyapps/zxing-android-embedded#448]
#### Description of the problem:

**I am using below library to scan a barcode
compile 'com.journeyapps:zxing-android-embedded:3.2.0@aar'

But sometimes it scans the irrelevant barcode values while scanning the product.

What is the need for "android:hardwareAccelerated" property on the bar-code scanner?

Can anyone help me with this?

**Does the same happen on other devices or an emulator?**
Yes

**Comment by rkistner** [comment]
Unfortunately some 1D barcode decoders are quite sensitive to noise. It is outside the scope of this project to handle those issues, unless it is noticeably worse than the Barcode Scanner application from the Play Store.
