### ISSUE TITLE
How to get only scanned barcode or QR code image 

### ISSUE THREAD

**Issue by code4rox** [journeyapps/zxing-android-embedded#449]
I want only scanned barcode as image. I know about the **ResultPoints** of barcode but can't understand how to get the **barcode or QR code** height and wight .

**The scanned image show like this** 

![image-1546837891640](https://user-images.githubusercontent.com/34452490/50750289-f56bf280-1265-11e9-9be8-366d66ec1c4a.jpg)

**But I want scanned image like this.**

![image-15468378916401](https://user-images.githubusercontent.com/34452490/50750342-3b28bb00-1266-11e9-8d42-f9db140e98df.jpg)

**Comment by rkistner** [comment]
The scanning process doesn't currently return enough info to do that accurately - the decoder will have to be modified to record and return more info.

**Comment by code4rox** [comment]
@rkistner can you guide me little bit for do that?

**Comment by code4rox** [comment]
@rkistner thanks for guide

**Comment by rkistner** [comment]
Closing as out of scope.
