### ISSUE TITLE
Customized the camera focus for a specific distance.

### ISSUE THREAD

**Issue by kamleshkarwande** [journeyapps/zxing-android-embedded#450]
Hi,
Thanks a lot for this library, It has helped me and many others to easily integrate barcode scanning in our android projects.

I am able to get it working as per my needs by following options

`CameraSettings mCameraSettings  = new CameraSettings();
        mCameraSettings.setFocusMode(CameraSettings.FocusMode.MACRO);
        mCameraSettings.setMeteringEnabled(true);
        mCameraSettings.setBarcodeSceneModeEnabled(true);
        mCameraSettings.setAutoFocusEnabled(true);
        mCameraSettings.setContinuousFocusEnabled(false);
        mCameraSettings.setExposureEnabled(false);
        mBarcodeView.setCameraSettings(mCameraSettings);`

This enables me to focus on closer objects. This works great, but I am trying a level better where the camera focus is set on a fixed point, at a distance of 10cm (X cm) from the camera, and it does not change.

First of all is it possible? and if so what is the best way to achieve it.

library version : 3.3.2
device : I have tested on samsung and moto devices.
OS : Kitkat,Lollipop,Marshmallow,Nougat,Oreo

**Comment by rkistner** [comment]
Camera focus is tricky in general, and the available options can vary a lot between devices. If you do find a solution, please post it here.

**Comment by kamleshkarwande** [comment]
The only option that I see which has reduced the scanning time by a big factor is to change the auto-focus delay.

In class `AutoFocusManager` I have reduced the `AUTO_FOCUS_INTERVAL_MS` from 2000 milliseconds to 500. 


Not sure what will be the drawback of this (other than the load on camera), but as of now its seems to give great reponse.

Does anyone have any better idea? or solution?

**Comment by JakubNeukirch** [comment]
Hey, for me setting zoom in `AutoFocusManager` helped a lot. For me issue wasnt focus, but when the gs1 codes were small decoder had problems with decoding them.
This is what i done in AutoFocusManager constructor just before invoking `start` method:
`       Camera.Parameters params = camera.getParameters();
        params.setZoom(params.getMaxZoom()/2);
        camera.setParameters(params);`

**Comment by rkistner** [comment]
The focus behaviour can vary a lot over different devices.

If you do find a solution that performs better across multiple devices and barcode types, pull requests will be welcome.

**Comment by diegoflassa** [comment]
> `AUTO_FOCUS_INTERVAL_MS`

How do i change it, without changing the source?
