### ISSUE TITLE
DecoratedBarcodeView does not work below android 6.0

### ISSUE THREAD

**Issue by ivanessence** [journeyapps/zxing-android-embedded#451]
[Origin of the problem]
If I open activity with scanner I have black screen on Android < 6.0
I added camera permission in AndroidManifest.
In my layout I added this:

`    <com.journeyapps.barcodescanner.DecoratedBarcodeView
        android:id="@+id/barcode_scanner"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:layout_centerHorizontal="true"
        android:layout_marginStart="0dp"
        android:layout_marginEnd="0dp"
        android:layout_marginBottom="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/toolbar_barcode" />`

**Which phone/tablet are you using, and which Android version does it run?
Does the same happen on other devices or an emulator?**

I reproduced the problem on the following device/OS:

(Sim) Nexus 4, 4.4 (KITKAT, 19)
(Sim) Nexus 4, 5.0 (Lollipop, 21)
(Real) Xiaomi Redmi3 5.0.1 (Lollipop, 21)

**Which library version are you using?**

 zxing-android-embedded:3.6.0

**Can you reproduce the issue in the sample project included with the library? If not, can you
provide your own sample project or sample code that produces this error?**

No, sample work fine on Android < 6.0

**In the case of an error do you have a stack trace or adb logs?**

No

**Comment by rkistner** [comment]
1. Check the adb logs for any possible errors.
2. Since the sample app is working, start by copying one of the samples and seeing where the difference lies.

**Comment by ivanessence** [comment]
I used in project only  barcode_scanner from XML, with methods  barcode_scanner.resume() and  barcode_scanner.pause(). I tryed to use code from sample class " ToolbarCaptureActivity" with CaptureManager and it work fine on all android versions. Thx.
