### ISSUE TITLE
DecoratedBarcode consumes first click.

### ISSUE THREAD

**Issue by giampa** [journeyapps/zxing-android-embedded#453]
#### Description of the problem:
DecoratedBarcodeView is consuming the first click on a button inside a custom scanner activity.

**Which library version are you using?**

Latest.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

Android emulator and Nexus 5X.

**Does the same happen on other devices or an emulator?**

Nope, this happens only in emulator.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

    <?xml version="1.0" encoding="utf-8"?>
     <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
         xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:id="@+id/relative_custom_scanner_activity"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:ignore="UnusedAttribute">

        
        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="?attr/colorPrimary"
            android:minHeight="?attr/actionBarSize"
            android:theme="@style/Ecommerce.Smart.Theme.Overlay"
            app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

            <com.journeyapps.barcodescanner.DecoratedBarcodeView
            android:id="@+id/zxing_barcode_scanner"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_below="@+id/toolbar"
            app:zxing_scanner_layout="@layout/custom_barcode_scanner" />

        <Button
            android:id="@+id/button_discount_code"
            android:layout_width="match_parent"
            android:layout_height="60dp"
            android:layout_alignParentBottom="true"
            android:layout_centerHorizontal="true"
            android:layout_margin="20dp"
            android:background="@drawable/rect_rounded"
            android:fontFamily="sans-serif-medium"
            android:text="@string/digit_code_manually"
            android:textAllCaps="true"
            android:textColor="@android:color/white"
            android:textSize="20sp" />
    </RelativeLayout>

The rest of the code is the same of the sample project for custom UI scanner.

**Comment by rkistner** [comment]
There is nothing in the library that intercepts clicks. If it's only an issue in the emulator, it is probably some emulator bug.
