### ISSUE TITLE
Do not destroy CaptureActivity when app is paused

### ISSUE THREAD

**Issue by woprandi** [journeyapps/zxing-android-embedded#454]
#### Description of the problem:

When the capture activity is on the foreground and the app is paused / resumed (via home button for example), the activity has been destroyed and went back to the caller activity. I don't understand this behavior and that would be good if it could be overriden 

**Which library version are you using?** 3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)** Galaxy Tab A 2018, Android 8

**Comment by rkistner** [comment]
There is no code in the library doing this, and I could not reproduce the issue. The camera preview and scanning is paused, but the Activity should stay open.

If you do have more info on how to reproduce, open a new issue.
