### ISSUE TITLE
App crashes, when back button is clicked instead of scanning while scanner is on

### ISSUE THREAD

**Issue by chiragchaplot** [journeyapps/zxing-android-embedded#46]
When I am scanning while the scanning activity is on and I press the back button instead of scanning the app crashes. Can anyone explain to me how to tackle it?

**Comment by rkistner** [comment]
I'll need some more info, specifically:

1. Which version of the library are you using?

2. What phone/tablet are you using, and which Android version does it run?

3. Does the same happen on other devices?

4. Can you get a stack trace from the crash? Android Studio has a log window for this, otherwise you can use the `adb logcat` command-line tool.

**Comment by chiragchaplot** [comment]
1. Library Version - SDK Platform API 16 ver 5 and SDK Platform-tools ver 22

2. Micromax Canvas 2 A110 - Android 4.2.1

3. Yes, I used it on Nexus 5 - 5.0.1 and yet it still crashed

4. I solved the problem on my own. 

IntentResult scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent);
        if (scanResult.getContents() != null)
        {

My mistake was that instead of using scanResult.getContents() I used only scanResult i.e. 

if(scanResult != null) and hence my app was crashing.

Thanks for helping though

**Comment by suneeljami** [comment]
when i am click on back without scann qr code and come back scanner or opening camer it shows amera error occured

**Comment by rkistner** [comment]
@suneeljami A stack trace would help to debug. Most often the issue is somewhere in the Activity openening the scanner. If you do find an issue in the library, open a new issue.

**Comment by Rofinho** [comment]
I think your application hangs because in your function onActivityResult (int requestCode, int resultCode, intent data)
you try to use the answer without a tester beforehand if it exists.

try to make a test of its kind.


if (result != null && resultCode !=0) {
yor code here.

}
