### ISSUE TITLE
IntentIntegrator not available

### ISSUE THREAD

**Issue by davidhowe** [journeyapps/zxing-android-embedded#460]
IntentIntegrator class not available with latest lib version 3.6.0. Review your lib and readme.md file
Had to pull snapshot version com.github.journeyapps:zxing-android-embedded:65aaa93a27 for it to work

**Comment by rkistner** [comment]
IntentIntegrator is still available as `com.google.zxing.integration.android.IntentIntegrator`, and is used in many of the examples in the project.
