### ISSUE TITLE
Suitable library version for Android SDK 22

### ISSUE THREAD

**Issue by Kameswari** [journeyapps/zxing-android-embedded#464]
Hi,

We are having one hardware device which runs with customized Android SDK version 22. The app which I am developing should run on that device and hence compile SDK version should be put as 22 only and hence support libraries also should be put as 22.x.x.

Could you please suggest which version of your library I can use to scan the QR code?

Thanks in advance.

Thanks & Regards,
Kameswari

**Comment by rkistner** [comment]
This project currently has a targetSdk of 27 and minSdk of 14. Usually it's not an issue to target a later SDK version than the device has - the built code stays compatible.

If you do need to change the targetSdk, you should be able to do that in your app, but you'll have to check Android's documentation for that.

If you need to rebuild this with different build tools, you'll need to fork this library. The latest version will probably not build with older build tools - you'll have to check which of the past versions can work with that. But I really doubt this will be required.
