### ISSUE TITLE
ViewFinderView doesn't resize correctly 

### ISSUE THREAD

**Issue by sohail-aziz** [journeyapps/zxing-android-embedded#465]
Hi, 

I am using library version 3.6.0 on Nokia-8 android version 9.0. 

I am using the DecoratedBarCodeView with ViewFinderView in a DialogFragment. With fixed height and width of parent layout it works fine but if we use match_parent it breaks. ViewFinderView moves to the the bottom left corner and becomes very small.

Also if soft keyboard is opened it doesn't resize itself correctly and QR scanning doesn't work inside the viewFinderView but outside of its  boundaries.

![screenshot_20190305-110113](https://user-images.githubusercontent.com/4012626/53798460-94485e80-3f38-11e9-8104-34be3f1bb8fc.png)
![screenshot_20190305-110137](https://user-images.githubusercontent.com/4012626/53798461-94485e80-3f38-11e9-97e5-4ba103d9542b.png)
![screenshot_20190305-110326](https://user-images.githubusercontent.com/4012626/53798462-94485e80-3f38-11e9-95f8-c33a63354f87.png)

**Comment by meierjan** [comment]
+!

**Comment by rkistner** [comment]
Please post a sample project demonstrating the issue - it is difficult to diagnose the issue without it.
