### ISSUE TITLE
When i focus camera on a empty space , camera reading some default value 

### ISSUE THREAD

**Issue by ajayglobalnest** [journeyapps/zxing-android-embedded#466]
#### Description of the problem:
When i focus camera on a empty space , camera reading some default value 

**Which library version are you using?**  3.3.3.

**Which phone/tablet are you using, and which Android version does it run?
Sony Xperia 

**Does the same happen on other devices or an emulator?
Othr devices Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?
Yes i am able to 

**In the case of an error do you have a stack trace or adb logs?
NO

**Comment by rkistner** [comment]
This may be a side-effect of specific barcode decoders (often for 1D barcodes), which is outside the control of this library.
