### ISSUE TITLE
Creation of new logo

### ISSUE THREAD

**Issue by debpedrano** [journeyapps/zxing-android-embedded#467]
Good day project owner, 

About the enhancement of the project, it would be better to have its own logo for a clearer view and can be recognized easily. Just my opinion, just mention me and im ready to create a new one!.

**Comment by 1458883958** [comment]
Did you implement adding a logo?

**Comment by debpedrano** [comment]
i can pull request the logo to be added on this project

**Comment by rkistner** [comment]
Thanks, but no logo is required for this project.
