### ISSUE TITLE
No way to run the ViewFinder from a Fragment

### ISSUE THREAD

**Issue by BRAINBLENDr** [journeyapps/zxing-android-embedded#47]
Hello, 

At this moment, it seems to be impossible to show the ViewFinder in a Fragment, without starting a new Activity to show the ViewFinder.

Any way on how to do this?

**Comment by rkistner** [comment]
This is supported in the [3.x branch](https://github.com/journeyapps/zxing-android-embedded/tree/3.x), but note that the API may still change slightly before the 3.0 release.

In the 3.x branch there is a CompoundBarcodeView class that can be embedded in any layout (including inside a Fragment), and can perform the same functionality. It's not well documented yet, so you'll need to look at the code samples.
