### ISSUE TITLE
Scan by pressing a button

### ISSUE THREAD

**Issue by goodibunakov** [journeyapps/zxing-android-embedded#472]
I need scan event by pressing button.
Is it possible?

**Comment by rodekker** [comment]
Sure, have a look at http://www.skholingua.com/android-basic/other-sdk-n-libs/zxing

Cheers.

**Comment by goodibunakov** [comment]
@rodekker i need to start parse process. not to get bitmap

**Comment by rkistner** [comment]
Look at the continuous scanning example - it can be paused and resumed.
