### ISSUE TITLE
How to make a delay/gap time/pause in continuous scan

### ISSUE THREAD

**Issue by dvlwj** [journeyapps/zxing-android-embedded#473]
Hi, i really need the continuous scan, but at the same time i don't want it instantly scan every bar code in front of the camera. Because we need to have a sec or more to move the bar code.

In my case i make an increment every time a same bar code is scanned, because this its always reach 10 scan per 2-3 secs.

I already read some discussion in other discussion thread. Like check `system.currentTimeMillis` and compare it to a variable and then do something with if else condition, etc. Which is not working at all.

Do anyone have a suggestion or opinion?

Regards and Thanks

**Comment by rkistner** [comment]
The easiest option would be to just filter out results if it is too close to the previous one. The ContinuousCaptureActivity sample already has code to discard the result if it's the same as the previous scan. All you need to do is add another check to compare the time since the last scan.

**Comment by P1NG2WIN** [comment]
I did this by this code in BarcodeCallback's barcodeResult

```

            GlobalScope.launch(Dispatchers.Main) {
                barcodeView.barcodeView.stopDecoding()
                delay(100)
                toggleScan()
            }

```



  ```
  private fun toggleScan() {
        barcodeView.decodeContinuous(callback)
    }
```

**Comment by ArunKumar-Arumugam** [comment]
> 
> 
> I did this by this code in BarcodeCallback's barcodeResult
> 
> ```
> 
>             GlobalScope.launch(Dispatchers.Main) {
>                 delay(100)
>                 toggleScan()
>             }
> ```
> 
> ```
> private fun toggleScan() {
>       decoratedBarcodeView.decodeSingle(callback)
>   }
> ```

Whats a GlobalScope in this and can you give a piece of code for callback
