### ISSUE TITLE
In portrait mode,my device's preview is scale

### ISSUE THREAD

**Issue by Seejun** [journeyapps/zxing-android-embedded#475]
Hello all:
  I have the issue,can everyone help me?thanks!
  My device is in portrait mode,and the lib works well,but the device's preview is scale.
  Then I change the following in CameraManager.java(setParameters() method)

  **Camera.Size realPreviewSize = camera.getParameters().getPreviewSize();
        if (realPreviewSize == null) {
            previewSize = requestedPreviewSize;
        } else {
            if (realPreviewSize.width>realPreviewSize.height)
                previewSize = new Size(realPreviewSize.height, realPreviewSize.width);
            else
                previewSize = new Size(realPreviewSize.width, realPreviewSize.height);
        }
        cameraPreviewCallback.setResolution(previewSize);**

  The device's preview is in normal,but the lib does not work,it can not scan QR code anymore.

**Comment by rkistner** [comment]
This is likely a device-specific issue - on all my test devices scanning works fine in portrait mode, with no scaling issues.
