### ISSUE TITLE
扫描完成，相机未立刻释放，在进入扫描页 或 进入一个需要打开相机业务的页面 会提示 CameraService::connect X (PID 5048) rejected (camera 0 is opened ,can not open two camera) 

### ISSUE THREAD

**Issue by hw1015** [journeyapps/zxing-android-embedded#476]
扫描完成，相机未立刻释放，在进入扫描页 或 进入一个需要打开相机业务的页面 会提示 CameraService::connect X (PID 5048) rejected (camera 0 is opened ,can not open two camera) 
Camera 1: unable to initialize device: Too many users (-87)

3.3.0jar  vivo mate20 等都不行

**Comment by Hellopcj** [comment]
哈哈 也遇到这个问题

**Comment by rkistner** [comment]
Please post issues in English only.

The camera is managed by a separate thread for performance reasons. This means that the camera may not be immediately available when the Activity is closed. You'll have to handle this in your application.
