### ISSUE TITLE
getRawBytes() on scanning Aztec Code returns NULL

### ISSUE THREAD

**Issue by iSDP** [journeyapps/zxing-android-embedded#48]
getRawBytes() on scanning Aztec Code returns NULL

**Comment by iSDP** [comment]
Issue is in zxing's core lib, but i can't fix it: https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/aztec/decoder/Decoder.java#L79

**Comment by rkistner** [comment]
I see you already reported the issue in the core zxing library as well. This library should be compatible with any version of zxing core, so you can just use your modified version instead of the `com.google.zxing:core:3.2.0` one.
