### ISSUE TITLE
how to set orientation vertical ?

### ISSUE THREAD

**Issue by Alireza-hr** [journeyapps/zxing-android-embedded#483]
i search around of your documents and issues but i dont find answer to my question !
i have android pie

**Comment by Alireza-hr** [comment]
this is my code in java  : 
  IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
        integrator.setPrompt("Scan a QR Code");
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(true);
        integrator.setOrientationLocked(false);
        integrator.initiateScan();

and manifest : 
<activity ....
  android:screenOrientation="fullSensor"
            tools:replace="screenOrientation"
/>

**Comment by alizaidi606** [comment]
you need to create a new activity and extend it from `CaptureActivity `of this library.


```
import com.journeyapps.barcodescanner.CaptureActivity;
public class PortraitCaptureActivity extends CaptureActivity {

}
```

Then in AndroidManifest simply set this activity's orientation to portrait.

```
<activity android:configChanges="keyboard|keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize|uiMode"
android:screenOrientation="portrait"
android:name=".Utility.PortraitCaptureActivity"/>
```

Then while initiating `IntentIntegrator` just set `PortraitCaptureActivity` as capture activity by calling `setCaptureActivity`.

```
IntentIntegrator integrator = new IntentIntegrator(this);
integrator.setCaptureActivity(PortraitCaptureActivity.class);
```

**Comment by nandur93** [comment]
#368

**Comment by rkistner** [comment]
Duplicate issue.
