### ISSUE TITLE
Inverted DataMatrix

### ISSUE THREAD

**Issue by kuleshovdv** [journeyapps/zxing-android-embedded#485]
Hi!
How you think does possible to ZXing reading barcode like this [https://wiki.lineris.ru/_detail/marka/tobacco/mark_code.jpg](https://wiki.lineris.ru/_detail/marka/tobacco/mark_code.jpg)
This is inverted DataMatrix.
`intentIntegrator.addExtra(Intents.Scan.SCAN_TYPE, Intents.Scan.INVERTED_SCAN)`
doesn't work

**Comment by rkistner** [comment]
Inverted mode should be working - I'm guessing there's another issue with this barcode, such as the white squares.

Unfortunately we cannot provide support for non-standard barcodes such as these, but you're welcome to post updates if you do find a solution.
