### ISSUE TITLE
Blocking Screenshots and Screen Recording

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [journeyapps/zxing-android-embedded#486]
#### Description of the problem:
Our Application need to block all the screenshots and Recording of screen. **com.journeyapps.barcodescanner.CaptureActivity** is not having **FLAG_SECURE** for the Screenshot protection. Shall we expect change in next version?

**Which library version are you using?** 3.4.0.

**Comment by rkistner** [comment]
You can use a custom Activity for this - see the readme and other docs.
