### ISSUE TITLE
missing setMaskColor in ViewfinderView

### ISSUE THREAD

**Issue by AbhinayMe** [journeyapps/zxing-android-embedded#487]
#### Description of the problem:
missing setMaskColor in ViewfinderView

**Which library version are you using?** E.g. 3.2.0.
3.6.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Android 6.0

**Does the same happen on other devices or an emulator?**
Not sure

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Import dependency in Gradle or download source zip from the releases

**Comment by rkistner** [comment]
This will be available in v4.0.0.
