### ISSUE TITLE
CustomCaptureActivity - Intents.Scan.QR_CODE_MODE

### ISSUE THREAD

**Issue by Chesteer89** [journeyapps/zxing-android-embedded#49]
Hi,

I know it should be possible, but how can i set embedded scanner recognize only QR codes? I understand i should use custom decoder thread with decodeFormats, but do you have any tips?

**Comment by rkistner** [comment]
You do this by creating a DecoderFactory. DefaultDecoderFactory is a simple implementation, which accept formats and other hints, which are passed to a MultiFormatReader.

        Collection<BarcodeFormat> decodeFormats = Arrays.asList(BarcodeFormat.QR_CODE);
        DecoderFactory factory = new DefaultDecoderFactory(decodeFormats, null, null);
        barcodeView.setDecoderFactory(factory);

**Comment by Chesteer89** [comment]
Thanks, i thought i need to pass decodeHints and characterSet too. Works like a charm.
