### ISSUE TITLE
Custom Laytout Not working 

### ISSUE THREAD

**Issue by khalid2105** [journeyapps/zxing-android-embedded#490]
#### Description of the problem:
Please enlist steps to  add my custom layout in the library.
Problem : i need toolbar when scanning the QR. 

for :  com.journeyapps:zxing-android-embedded:3.6.0

**Comment by khalid2105** [comment]
The steps already mentioned for custom layout are not described well.

**Comment by rkistner** [comment]
Custom layouts are considered an advanced feature. There are some examples in the code, but no further support is provided. Pull requests for better documentation are welcome.
