### ISSUE TITLE
Update xzing core to 3.4.0

### ISSUE THREAD

**Issue by ethanwa** [journeyapps/zxing-android-embedded#491]
The core has been updated with better QR code detection.

**Comment by rkistner** [comment]
This can currently be done by manually including this line:

```gradle
implementation 'com.google.zxing:core:3.4.0'
```

ZXing 3.4.0 does require API 24 / Android 7.0 according to the release notes, so will have to consider the impact of dropping support for older devices before making this the default.

**Comment by rkistner** [comment]
This will be the new default in v4.0.0 - see #494.
