### ISSUE TITLE
Unable to downgrade minsdk

### ISSUE THREAD

**Issue by kenshin171** [journeyapps/zxing-android-embedded#507]
Library version 4.0.2 with zxing 3.3.3.
Android Studio 3.5.1 wuth android build tools 29.0.2 

Unable to downgrade to minsdk 21 due to gradle complaining and failing the gradle build.

`ERROR: The minSdk version should not be declared in the android manifest file. You can move the version from the manifest to the defaultConfig in the build.gradle file.`

due to 
`<uses-sdk android:minSdkVersion="14" tools:overrideLibrary="com.google.zxing.client.android" />`

Issue can be resolved by taking out `android:minSdkVersion="14"` resulting with 

`<uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />`

**Comment by rkistner** [comment]
Thanks, updated the readme.
