### ISSUE TITLE
Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by JayeshDankhara** [journeyapps/zxing-android-embedded#513]
#### Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 28610 (om.busfro.uflyp), pid 28610

**zxing-android-embedded** 

** nexus 6p are using for tasting this library abd show upper giver error and crash continues**

**Comment by rkistner** [comment]
Please follow the issue template - all the info is needed for a bug report.
