### ISSUE TITLE
missing laserVisibility ViewfinderView

### ISSUE THREAD

**Issue by zhupengxiang** [journeyapps/zxing-android-embedded#515]
#### Description of the problem:

missing laserVisibility ViewfinderView

version: 4.0.2

I cannot find the laserVisibility  property in ViewfinderView

![image](https://user-images.githubusercontent.com/17894209/70126133-55a42800-16b3-11ea-8b98-146e19ff01d2.png)

**Comment by rkistner** [comment]
This will be included in the next release.

**Comment by zhupengxiang** [comment]
Thanks! 😄

**Comment by rkistner** [comment]
Thanks, released in 4.1.0.
