### ISSUE TITLE
Can i select camera OR use front camera for QR scan ?

### ISSUE THREAD

**Issue by ronak91** [journeyapps/zxing-android-embedded#517]
I want to use the front camera for the QR scan. So, is it possible?

**Comment by rkistner** [comment]
Yes, this sample shows how you can specify the front camera:

https://github.com/journeyapps/zxing-android-embedded/blob/9319110de8927fb4771b928eaf795e43999d8529/sample/src/main/java/example/zxing/MainActivity.java#L71-L75

Currently there is no support for dynamically switching cameras.
