### ISSUE TITLE
ERROR???

### ISSUE THREAD

**Issue by lydlovezjr** [journeyapps/zxing-android-embedded#518]
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.journeyapps:zxing-android-embedded:4.0.2] C:\Users\LYD\.gradle\caches\transforms-2\files-2.1\8ba3c39e41e98bfcfa34b8df293232d6\zxing-android-embedded-4.0.2\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.google.zxing.client.android" to force usage (may lead to runtime failures)

**Comment by rkistner** [comment]
The error message says it all. The library supports minSdk of 24 by default, so you'll have to use this in your project. If you want to support older versions, follow the instructions in the readme.
