### ISSUE TITLE
Veracode Issue on CaptureManager.java

### ISSUE THREAD

**Issue by robimoltewhp** [journeyapps/zxing-android-embedded#520]
Hello,

I am using Veracode Tool for code static analysis
https://www.veracode.com
and I am facing one security issue on your component

The issue says:

CaptureManager.java: 360

Description: This call to java.io.File.createTempFile() may create insecure temporary files depending on which version of the Java runtime is in use. In versions before 1.6.0_11, filenames are predictable under certain conditions. Creating and using insecure temporary files can leave application and system data vulnerable to attack.
Remediation: Be sure to use the latest version of the Java runtime. If the application has the potential to be deployed in environments with outdated Java installations, consider implementing a custom function that uses SecureRandom() to generate temporary filenames.

**Comment by rkistner** [comment]
Please check the issues from automated security tools before posting.

This is not an actual issue:
1. Android uses a different runtime (not "versions before 1.6.0_11").
2. The file is in the application's private cache, so cannot be accessed by any other applications.
