### ISSUE TITLE
missing setResultDisplayDuration(long ms)

### ISSUE THREAD

**Issue by Bmooij** [journeyapps/zxing-android-embedded#53]
Is there a reason why this function has been removed?

I tried:

``` java
        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.addExtra("RESULT_DISPLAY_DURATION_MS", 5000L);
        integrator.initiateScan();
```

But this doesn't work

**Comment by rkistner** [comment]
It requires a non-trivial UI to display the result, so this added some complexity to the codebase, and was simply not included in the rewrite. In most cases the result is displayed in the calling activity anyway, so this is often redundant. However, pull requests to add the feature again are welcome.

**Comment by Bmooij** [comment]
ok, thank you for the quick reply

**Comment by rkistner** [comment]
Closing as out of scope.
