### ISSUE TITLE
Updated readme API 14+ versions won't build

### ISSUE THREAD

**Issue by Solidogen** [journeyapps/zxing-android-embedded#531]
Hi, in readme in you recently swapped version to 4.0.2 in API 14+ section. This doesn't build.

```
Execution failed for task ':app:processDevMockDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.journeyapps:zxing-android-embedded:4.0.2] /Users/patrycjuszblaszczuk/.gradle/caches/transforms-2/files-2.1/ef6f724dc0aa523bb372f4c8cdfa1462/zxing-android-embedded-4.0.2/AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.google.zxing.client.android" to force usage (may lead to runtime failures)
```

**Comment by rkistner** [comment]
See this section in the readme:

> By default, Android SDK 24+ is required because of `zxing:core` 3.4.0.
> To support SDK 14+, downgrade `zxing:core` to 3.3.0 -
> see [instructions](#adding-aar-dependency-with-gradle). You'll also need this in your Android manifest:
> 
> ```xml
> <uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />
> ```

**Comment by Solidogen** [comment]
Thanks a lot, I missed this one. Consider moving this info to dependencies paragraph by the way, I didn't read About section because I'm a long-time user :)
