### ISSUE TITLE
Can we read both QR code and Barcode using zxing library

### ISSUE THREAD

**Issue by ruhamadavid** [journeyapps/zxing-android-embedded#534]
Can we read both QR and bar code using zxing library,

Below i mentioned how I'm calling my Intent for scanning. It works only for bar code event the scan mode refers to 'All Types', 

Intent intentSacn = new Intent(com.google.zxing.client.android.SCAN);
intentSacn.putExtra("SCAN_MODE", "ALL_CODE_TYPES");
If I use separate call for QR code is written means its  working for QR code only.
like dis: 
Intent intentSacn = new Intent(ACTION_SCAN);
intentSacn.putExtra("SCAN_MODE", "QR_CODE_MODE");

**Comment by rkistner** [comment]
If you are using the `com.google.zxing.client.android.SCAN` Intent, you are using the Barcode Scanner application directly: https://github.com/zxing/zxing
Please post your question there.
