### ISSUE TITLE
Zxing misreads

### ISSUE THREAD

**Issue by rajar11** [journeyapps/zxing-android-embedded#538]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rajar11** [comment]
Using version 3.6.0 with zxing 3.3.3 on android and having barcode misreads.
Anyone experience that ? Anyway to prevent this from happening. Scanning barcode 128, code 39 and code 93.

**Comment by rkistner** [comment]
This is a limitation with scanning 1D barcodes using a camera in general. There may be better algorithms out there, but that is outside the scope of this project.
