### ISSUE TITLE
Error during including 

### ISSUE THREAD

**Issue by yusdenis** [journeyapps/zxing-android-embedded#54]
I tried to use the library on a personal project (zxing-android-embedded)
The configuration file Gradle (build.gradle) is:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:cardview-v7:22.0.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile project(':intro-slider-lib')
    compile project(':parallax-effect-lib')
    compile project(':odoo-rpc-v2')
    compile(project(':zxing-android-embedded')) { transitive = true }
}

However, gives me this error when compiling.
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	D:\dev\tools\android-sdk-windows\build-tools\21.1.2\dx.bat --dex --no-optimize --output D:\geomovil\p13 delivery\Odoo\app\build\intermediates\dex\debug --input-list=D:\geomovil\p13 delivery\Odoo\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/android/camera/open/OpenCameraInterface;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

**Comment by rkistner** [comment]
I recommend you include it directly from the repository, as documented in the readme:

    compile 'com.journeyapps:zxing-android-embedded:3.0.0@aar'
    compile 'com.google.zxing:core:3.2.0'

Your error typically means that the class is included twice from different places. `./gradlew dependencies` usually helps to see why this is happening.

**Comment by yusdenis** [comment]
I change gragle configuration to:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:cardview-v7:22.0.0'
    compile 'com.google.android.gms:play-services:7.0.0'
    compile project(':intro-slider-lib')
    compile project(':parallax-effect-lib')
    compile project(':odoo-rpc-v2')
    compile 'com.journeyapps:zxing-android-embedded:3.0.0@aar'
    compile 'com.google.zxing:core:3.2.0'
}

After that I clean project, rebuild project.  
Despite this, when I compile, I have the same error: 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	D:\dev\tools\android-sdk-windows\build-tools\21.1.2\dx.bat --dex --no-optimize --output D:\geomovil\p13 delivery\Odoo\app\build\intermediates\dex\debug --input-list=D:\geomovil\p13 delivery\Odoo\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/android/camera/open/OpenCameraInterface;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

**Comment by rkistner** [comment]
Can you give me the output of the `./gradlew dependencies` command? That should explain the error.

**Comment by yusdenis** [comment]
+--- com.android.support:appcompat-v7:22.0.0
|    \--- com.android.support:support-v4:22.0.0
|         \--- com.android.support:support-annotations:22.0.0
+--- com.android.support:cardview-v7:22.0.0
+--- com.google.android.gms:play-services:7.0.0
|    +--- com.google.android.gms:play-services-ads:7.0.0
|    |    +--- com.google.android.gms:play-services-base:7.0.0
|    |    |    \--- com.android.support:support-v4:22.0.0 (*)
|    |    \--- com.google.android.gms:play-services-analytics:7.0.0
|    |         \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-analytics:7.0.0 (*)
|    +--- com.google.android.gms:play-services-appindexing:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-appstate:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-cast:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-drive:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-fitness:7.0.0
|    |    +--- com.google.android.gms:play-services-base:7.0.0 (*)
|    |    \--- com.google.android.gms:play-services-location:7.0.0
|    |         +--- com.google.android.gms:play-services-base:7.0.0 (*)
|    |         \--- com.google.android.gms:play-services-maps:7.0.0
|    |              \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-games:7.0.0
|    |    +--- com.google.android.gms:play-services-base:7.0.0 (*)
|    |    \--- com.google.android.gms:play-services-drive:7.0.0 (*)
|    +--- com.google.android.gms:play-services-gcm:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-identity:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-location:7.0.0 (*)
|    +--- com.google.android.gms:play-services-maps:7.0.0 (*)
|    +--- com.google.android.gms:play-services-nearby:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-panorama:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-plus:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-safetynet:7.0.0
|    |    \--- com.google.android.gms:play-services-base:7.0.0 (*)
|    +--- com.google.android.gms:play-services-wallet:7.0.0
|    |    +--- com.google.android.gms:play-services-base:7.0.0 (*)
|    |    +--- com.google.android.gms:play-services-identity:7.0.0 (*)
|    |    \--- com.google.android.gms:play-services-maps:7.0.0 (*)
|    \--- com.google.android.gms:play-services-wearable:7.0.0
|         \--- com.google.android.gms:play-services-base:7.0.0 (*)
+--- project :intro-slider-lib
|    \--- com.android.support:support-v4:21.0.3 -> 22.0.0 (*)
+--- project :parallax-effect-lib
+--- project :odoo-rpc-v2
\--- project :zxing-android-embedded
     \--- com.google.zxing:core:3.2.0

**Comment by rkistner** [comment]
Ok, there's nothing obvious there showing where the class would be defined a second time.

Some fixes you can try:
1. Clean the project
2. Upgrade the Android Gradle plugin to the latest version, and use the latest version of build-tools.
3. Try the solution here: http://stackoverflow.com/a/24025291/214837

**Comment by mrThinBone** [comment]
did you solve this problem? I face the same, try all but doesn't help.

**Comment by rkistner** [comment]
Is it perhaps possible to create a small sample project producing this error? I haven't been able to reproduce it myself yet.

**Comment by mrThinBone** [comment]
As you guest, i try to create completely new project (not create as module) and it work for now. That's weird.
