### ISSUE TITLE
Default interface methods are only supported starting with Android N (--min-api 24): void com.journeyapps.barcodescanner.BarcodeCallback.possibleResultPoints(java.util.List)

### ISSUE THREAD

**Issue by ayush-sri** [journeyapps/zxing-android-embedded#547]
Default interface methods are only supported starting with Android N (--min-api 24): void com.journeyapps.barcodescanner.BarcodeCallback.possibleResultPoints(java.util.List)
solution provided in implementation i.e,
implementation('com.journeyapps:zxing-android-embedded:4.1.0') { transitive = false }
not working

**Comment by ayush-sri** [comment]
**add this in you app level build.gradle**
android { 
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by nicholemnl** [comment]
Hello im experiencing this now but the weird thing it works if i installed the app via AndroidStudio.. and not if I run via command ./gradlew and adb install
