### ISSUE TITLE
Error on add android support design library 

### ISSUE THREAD

**Issue by epool** [journeyapps/zxing-android-embedded#55]
I'm getting this error after add `compile 'com.android.support:design:22.2.0'` to my gradle file:
`.../app/build/intermediates/exploded-aar/com.journeyapps/zxing-android-embedded/3.0.0/res/values/values.xml` with this message `Error:(1) Attribute "insetForeground" has already been defined`.

**Comment by rkistner** [comment]
While I also get this error in one of my projects when I add the design library, I do not believe this has anything to do with this library (even though the error message seems to indicate otherwise). Let me know if you find a solution.

**Comment by rkistner** [comment]
I my case I got other duplicate attributes, which seems to be caused by HoloEverywhere / ActionbarSherlock that I'm including in my project.

I'm not sure where the "insetForeground" attribute is duplicated, but searching for it through your project may help.
