### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by zimuouyang** [journeyapps/zxing-android-embedded#553]
#### Description of the problem:

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

3.4.0 android version 23

**Comment by rkistner** [comment]
See this section in the readme: https://github.com/journeyapps/zxing-android-embedded#older-sdk-versions

**Comment by Catfriend1** [comment]
yes, and what exactly is the solution here?

**Comment by rkistner** [comment]
@Catfriend1 I see you did implement the fix now in https://github.com/Catfriend1/syncthing-android/commit/81d6b311de6efd68f8e68f36ae1ec29d3b2d9a47
