### ISSUE TITLE
Associated Flaws by CWE ID

### ISSUE THREAD

**Issue by odejinmi** [journeyapps/zxing-android-embedded#561]
#### Description of the problem:

**Which library version are you using?**4.1.0

After building the app, it was scan for vulnerability test and your library was one of the vulnerabilities with the issues below:

Insecure Temporary File (CWE ID 377)(1 flaw*)
 Fix Required by Policy
Description
Creating and using insecure temporary files can leave application and system data vulnerable to attack. In particular,
file names created by the tmpnam family of functions can be easily guessed by an attacker. If an attacker can predict
the filename and create a malicious collision, he may be able to manipulate the behavior of the application. 
Ensure that unpredictable names are used for temporary files and that files are created in a secure directory with
appropriate permissions. Using mkstemp() is a reasonably safe way to create temporary files. It will attempt to create
and open a unique file based on a filename template provided by the user, combined with a series of randomly
generated characters. Note that mkstemp() is safe if only the descriptor is used and the returned filename is not used
in a subsequent function call with extra privileges. Using mkstemp() does not completely eliminate race conditions but
does provide better protection than other methods.

**Comment by rkistner** [comment]
See #416.

**Comment by odejinmi** [comment]
Thanks
