### ISSUE TITLE
Can't recognize the QR code

### ISSUE THREAD

**Issue by Scorpio-fyx** [journeyapps/zxing-android-embedded#564]
#### Description of the problem:

**Which library version are you using?** 
4.1.0.

**Which phone/tablet are you using, and which Android version does it run? 
OPPO A5,  Android 7.0

**Does the same happen on other devices or an emulator?**
yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes unrecognized

**Comment by Scorpio-fyx** [comment]
[
![a626d174468c9aced9227ae2a4ed587](https://user-images.githubusercontent.com/44666761/88246436-158ac780-cccd-11ea-8d0f-09e76757835d.png)
](url)

**Comment by aazhevsky** [comment]
Had the same issue. After clearing the project and removing the .gradle folder, everything works fine.

**Comment by rkistner** [comment]
This is not a valid QR code - the square on one corner is cut off (top right).
