### ISSUE TITLE
How to set minimum length of an accepted barCode?

### ISSUE THREAD

**Issue by edu1525** [journeyapps/zxing-android-embedded#569]
#### Description of the problem:
In Brazil we have a default format of barcodes used for bank slips, its an ITF barCode with 44 characters, the problem is that sometimes this library recognizes smaller barCodes, with only some digits of the original barCode, it generates a false scan to user, because the beep is reproduced and the activity is closed when a barCode is found. Is there a way to specify the min number of characters to be recognized as a valid read?

**Which library version are you using?**  4.1.0.

**Which phone/tablet are you using, and which Android version does it run?** Samsung Galaxy S7 

**Does the same happen on other devices or an emulator?** Yes, on other devices too

**Comment by manoellribeiro** [comment]
hey @edu1525, have you found some workaround to read brazilian barcodes?
