### ISSUE TITLE
AutoFocus becomes disabled after BarcodeView.setTorch(true);

### ISSUE THREAD

**Issue by andressantiago** [journeyapps/zxing-android-embedded#57]
The AutoFocus becomes disabled after turning on the torch. When the torch is turned off, the autofocus does not turn back on either.

Seems to be that ```stopped``` never gets set back to ```false``` in the ```start()``` method in AutoFocusManager.java

The way it is now, once ```focus()``` is called, autofocus will never be reenabled after the torch is turned on once.

Thank you all at journeyapps for all your hard work! Really appreciate this library.

**Comment by rkistner** [comment]
Great catch!

Fixed in 069b556241691967f423bc8894117cdecc50de8e.

**Comment by andressantiago** [comment]
Thank you very much! You guys/gals are fantastic!

**Comment by andressantiago** [comment]
QQ, when will the update be pushed for us to use?

**Comment by rkistner** [comment]
I'll probably make a new release in the next week.

If you want to use it before then, you build it locally: https://github.com/journeyapps/zxing-android-embedded/#building-locally

You can also publish it to your own Maven repo, although that's a little more trouble.

**Comment by andressantiago** [comment]
I can wait for the release, thanks again.

**Comment by rkistner** [comment]
Released in v3.0.1.

**Comment by Ramji01** [comment]
hi i want to know how to enable flash light in zxing

**Comment by rafaelpivetta** [comment]
Ramji01, you can read the issue #212 https://github.com/journeyapps/zxing-android-embedded/issues/212
