### ISSUE TITLE
How can I use  androidx.fragment.app.Fragment instead of  android.app.Fragment?

### ISSUE THREAD

**Issue by qubyedev** [journeyapps/zxing-android-embedded#571]
I am not using 'com.journeyapps:zxing-android-embedded:4.1.0' and i wanna use the IntentIntegrator.forFragment(this).initiateScan(); function in my fragment.

But my fragment imported androidx.fragment.app.Fragment, so i cant use this function, how can I fix this issue?

**Comment by rkistner** [comment]
Use `IntentIntegrator.forSupportFragment()` for that.
