### ISSUE TITLE
Possible to Launch this app from another app? 

### ISSUE THREAD

**Issue by RonEskinder** [journeyapps/zxing-android-embedded#574]
#### Description of the problem:
Have an app that currently launches [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) app from IntentIntegrator and then get results back to the app. (User has to download the app if is not installed)

The requirement is to not embed the scanner into the app, so Im trying to build my own app so instead of calling Barcode Scanner i call my own, is this possible with this project?

**Which library version are you using?** E.g. 4.2.0.

**Comment by rkistner** [comment]
It is possible, but outside this scope of this project.

You'll have to implement this yourself using Android's Intent mechanisms.
