### ISSUE TITLE
Is ViewFinder moving?

### ISSUE THREAD

**Issue by halilozel1903** [journeyapps/zxing-android-embedded#579]
Hi,

I want to ViewFinder moving.

Is there up and down movement support?

![Screenshot_1605180460](https://user-images.githubusercontent.com/22895813/98934640-7a279780-24f3-11eb-9ce6-915eefae9c87.png)

**Comment by rkistner** [comment]
There is currently no support or plans for this.

**Comment by halilozel1903** [comment]
Thanks. I see.
