### ISSUE TITLE
Disable beep sound

### ISSUE THREAD

**Issue by vaxus** [journeyapps/zxing-android-embedded#58]
I'm looking for some guidance on how to disable the beep sound during scans. I am currently using the scanner from a Fragment using the IntentIntegrator as follows:

        IntentIntegrator.forSupportFragment(this).setPrompt("Scan  QR Code").setDesiredBarcodeFormats(IntentIntegrator.QR_CODE_TYPES).initiateScan();

Cheers

**Comment by rkistner** [comment]
I'll add support for doing that via IntentIntegrator in the next release.

**Comment by vaxus** [comment]
Excellent. That would be really great!

**Comment by rkistner** [comment]
Implemented in 6cd9c7b3d312f5ed7d41645d958b3d4cf5122ed4, released in v3.0.1.
