### ISSUE TITLE
Is possible border put in the Barcode corners?

### ISSUE THREAD

**Issue by halilozel1903** [journeyapps/zxing-android-embedded#580]
Hello,

I want to put border in the Barcode corners.

Like this one.

![IMG-20201106-WA0000](https://user-images.githubusercontent.com/22895813/98950995-c0d4bc00-250a-11eb-84be-6f84de5be377.jpg)

**Comment by phannaly** [comment]
Maybe you can override `onDraw()` in `ViewfinderView` but for the easy way, you can just create your custom layout. Align your qrcode frame image to fit the scanning area. Let check the example in `custom_barcode_scanner.xml`

**Comment by halilozel1903** [comment]
Yeah. Is there no example about it?

**Comment by phannaly** [comment]
Oh now someone makes pull request for it. #558

**Comment by niharika2810** [comment]
@phannaly I hope they can merge it now. Otherwise, you can use it for your own purpose :-)

**Comment by phannaly** [comment]
Okay thank you for that pull request. I'll check it.

**Comment by halilozel1903** [comment]
> Oh now someone makes pull request for it. #558

Thanks.

**Comment by halilozel1903** [comment]
@phannaly How you doin’ I cloned your app but I want to use like this picture. how I do?

![](https://user-images.githubusercontent.com/22895813/98950995-c0d4bc00-250a-11eb-84be-6f84de5be377.jpg)

**Comment by phannaly** [comment]
@halilozel1903  Just add QR code frame image.

<img width="1281" alt="Screen Shot 2020-11-17 at 1 16 59 PM" src="https://user-images.githubusercontent.com/13119017/99774980-22b3a800-2b41-11eb-849a-5942dd0f181a.png">

**Comment by halilozel1903** [comment]
my layout.xml file. Can you share arcade_frame? @phannaly 

<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
       xmlns:tools="http://schemas.android.com/tools"
       xmlns:app="http://schemas.android.com/apk/res-auto">

    <com.journeyapps.barcodescanner.BarcodeView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_barcode_surface"
        app:zxing_framing_rect_width="250dp"
        app:zxing_framing_rect_height="250dp"/>

    <com.journeyapps.barcodescanner.ViewfinderView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/zxing_viewfinder_view"
        app:zxing_possible_result_points="@color/zxing_custom_possible_result_points"
        app:zxing_result_view="@color/zxing_custom_result_view"
        app:zxing_viewfinder_laser="@color/zxing_custom_viewfinder_laser"
        app:zxing_viewfinder_laser_visibility="true"
        app:zxing_viewfinder_mask="@color/zxing_custom_viewfinder_mask"/>

    <TextView
        android:id="@+id/zxing_status_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal"
        android:background="@color/zxing_transparent"
        android:text="@string/zxing_msg_default_status"
        android:textColor="@color/zxing_status_text"/>

</merge>

**Comment by phannaly** [comment]
Just add one more view for qr code frame. Check the pic above again
