### ISSUE TITLE
Hello I have a question.

### ISSUE THREAD

**Issue by seonghoonjung** [journeyapps/zxing-android-embedded#582]
Hello I have a question.
After recognizing the QR code, it sends data as result while exiting the scan screen.
I am wondering how to prevent the scanning screen from being closed.
Thanks for reading.

**Comment by rkistner** [comment]
Yes - look at this sample:

https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

**Comment by seonghoonjung** [comment]
For your help

Thank you very much.

2020년 12월 2일 (수) 오후 9:17, Ralf Kistner <notifications@github.com>님이 작성:
