### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by Catfriend1** [journeyapps/zxing-android-embedded#591]
#### Description of the problem:
I see a lot ot PR's outstanding but no recent merges? Now have it in my app and i'm frightened bugs in the library gettint not fixed in the future.

**Which library version are you using?** E.g. 3.2.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**

**Does the same happen on other devices or an emulator?**

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
The project is still active, but a little behind in maintenance. Most current pull requests and issues are for new functionality.

**Comment by Catfriend1** [comment]
Thanks for the Feedback. Then I'll wait.
