### ISSUE TITLE
Switch Camera on custom layout

### ISSUE THREAD

**Issue by vtni** [journeyapps/zxing-android-embedded#60]
Is it possible to switch the camera in a custom layout like `capture_appcompat.xml`? I want to switch between front and back camera with a button. The `CompoundBarcodeView` has no function like `setCameraId` so i wanted to ask, if there is another solution to this?

**Comment by vtni** [comment]
i could solve it on my own:

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_capture_portrait_orientation);

        barcodeView = (CompoundBarcodeView) findViewById(R.id.barcode_scanner);
        barcodeView.decodeContinuous(callback);
        barcodeView.setStatusText(null);
        Button useOtherCamera = (Button) findViewById(R.id.useOtherCamera);
        //if phone has only one camera, hide "switch camera" button
        if(Camera.getNumberOfCameras() == 1){
            useOtherCamera.setVisibility(View.INVISIBLE);
        }
        else {
            useOtherCamera.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    CameraSettings settings = barcodeView.getBarcodeView().getCameraSettings();


                    if(barcodeView.getBarcodeView().isPreviewActive()) {
                        barcodeView.pause();
                    }

                    //swap the id of the camera to be used
                    if (settings.getRequestedCameraId() == Camera.CameraInfo.CAMERA_FACING_BACK) {
                        settings.setRequestedCameraId(Camera.CameraInfo.CAMERA_FACING_FRONT);
                    } else {
                        settings.setRequestedCameraId(Camera.CameraInfo.CAMERA_FACING_BACK);
                    }
                    barcodeView.getBarcodeView().setCameraSettings(settings);

                    barcodeView.resume();
                }

            });
        }
    }

**Comment by rkistner** [comment]
Great - that is the correct approach to follow currently.

I'll see if I can add some helper functions for that at some point.

**Comment by kamleshkarwande** [comment]
Is there any helper function added for this feature?

**Comment by sushantebt** [comment]
Thank you very much..
I almost spend whole day on this.
