### ISSUE TITLE
Could not GET 'https://repo.spring.io/libs-snapshot/com/journeyapps/zxing-android-embedded/4.1.0/zxing-android-embedded-4.1.0.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by IgorSt** [journeyapps/zxing-android-embedded#602]
#### Description of the problem:

I have the error when build project:

Could not GET 'https://repo.spring.io/libs-snapshot/com/journeyapps/zxing-android-embedded/4.1.0/zxing-android-embedded-4.1.0.pom'. Received status code 401 from server: Unauthorized
Disable Gradle 'offline mode' and sync project

**I use the version 4.1.0 of zxing-android-embedded**

**Android Studio 4.1.1**

**Comment by rkistner** [comment]
This project does not use the repo.spring.io repository. Make sure you use the `jcenter()` one.

**Comment by rkistner** [comment]
`jcenter()` is missing from the last `repositories` list in your screenshots, try adding it there.

**Comment by IgorSt** [comment]
this resolve my problem, i add jcenter() in repositories!
Thanks @rkistner
