### ISSUE TITLE
Migrate artifacts to a different repository

### ISSUE THREAD

**Issue by zehemz** [journeyapps/zxing-android-embedded#606]
#### Description of the problem:
Jfrog is going to deprecate and disable jcenter services - artifact migration will be needed

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by rkistner** [comment]
Thanks for the notice, will find a new repository soon.

**Comment by GuilhE** [comment]
[This](https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/) may also help.

**Comment by rkistner** [comment]
Thanks for that link. Will get the next releases into Sonatype OSSRH and Maven Central.

Not sure whether it's feasible to also migrate all the old releases over, since at minimum we'd need additional metadata. Perhaps a couple of the most actively-used releases.

**Comment by DaphnevdVeeke** [comment]
That's great news! I don't know if it is the same for others, but I would specifically need version 3.3.0 (`com.journeyapps:zxing-android-embedded:3.3.0`), because higher versions are not compatible with SDK<24 and the apps I'm using the library in still support minSdkVersion 21.

**Comment by zx2c4** [comment]
> That's great news! I don't know if it is the same for others, but I would specifically need version 3.3.0 (`com.journeyapps:zxing-android-embedded:3.3.0`), because higher versions are not compatible with SDK<24 and the apps I'm using the library in still support minSdkVersion 21.

Likewise.

**Comment by GuilhE** [comment]
Another nice helping article: [Migrating old artifacts from JCenter to MavenCentral](https://www.marcogomiero.com/posts/2021/move-libray-jcenter-to-maven/)

This helps you manual migrate desired versions easely

**Comment by mtwalli** [comment]
Any updates?

**Comment by zehemz** [comment]
It seems like JCenter will keep the artifacts 1 extra year. - No hurry so far
