### ISSUE TITLE
Migrate from jCenter to mavenCentral

### ISSUE THREAD

**Issue by joaoeudes7** [journeyapps/zxing-android-embedded#619]
Need migration of splitties packages, not available in repositories of mavenCentral.
JCenter deprecation and end of service: https://developer.android.com/studio/build/jcenter-migration

On Sync gradle receives:
Failed to resolve: com.journeyapps:zxing-android-embedded:3.4.0

**Comment by rkistner** [comment]
See #606.

Version 3.4.0 has not been migrated - can you upgrade to a later version?

**Comment by joaoeudes7** [comment]
@rkistner Good, thanks!
