### ISSUE TITLE
Custom UI (Not found resources) and no camera preview showing up

### ISSUE THREAD

**Issue by sushantkhanna** [journeyapps/zxing-android-embedded#64]
Hey!

I am trying to create a custom UI using this library.
The default scanning works fine.
But when I try to create a custom layout, by following the examples that you gave, i run into two problems

1) zxing_view and zxing_finder do not have the attributes that you use in your example. Hence including them, code does not compile.

2) Leaving those out, if I just add a CompoundBarcodeView, all I get is a black screen.

Can you please help me fix this ASAP.

**Comment by rkistner** [comment]
Did you use the code from the sample app directly? That should work.

I can try to see what the issue is if you can give me a sample project.

**Comment by sushantkhanna** [comment]
Hey Ralf

Understood the problem I think.
I was using the sample code under the master branch. Did not notice that you use a seperate version release branch.
Will try and get back to you.

One question though.
My objective for customization is to remove the viewfinder, or rather make it the same size as the camera preview.
Can that be done with this library?
If yes, how?

Thanks!

**Comment by rkistner** [comment]
Yes, just use BarcodeView instead of CompundBarcodeView.

The scan cropping rectangle will still be where the viewfinder was, I can't
remember if there's a simple way to change it's size.

**Comment by sushantkhanna** [comment]
So basically the rectangle will still be there, it just won't be visible?
And is there a way to change it inside the library?
If you can point me, I will simply make the change and include it in my
build directly.

**Comment by rkistner** [comment]
Yes, that's correct. It's calculated in calculateFramingRect in
CameraPreview. You can subclass BarcodeView and override that method.

**Comment by sushantkhanna** [comment]
OK. Will try tomorrow and close this.

**Comment by sushantkhanna** [comment]
Tried it and got it working.
Though have to say, it was not that straight forward.
Closing this for now, but maybe we can take a feature request to enhance customizability?

**Comment by rkistner** [comment]
Yes, feature requests are welcome.

Some types of functionality may make it into the core lib, other just as
samples. I'm not sure where this will fit, but I'm happy to look at it if
you show me what you wanted to achieve with this, and what you had to do to
achieve it.
