### ISSUE TITLE
Custom request code check issue

### ISSUE THREAD

**Issue by karan2vel** [journeyapps/zxing-android-embedded#642]
#### Description of the problem:

When I set the own request code as below 

```
IntentIntegrator integrator = new IntentIntegrator(this);
integrator.setRequestCode(1);
integrator.initiateScan();
```

and when I try to parse the Activity result it give me null result.

`IntentResult result = IntentIntegrator.parseActivityResult(1, resultCode, data);`

In the parseActivityResult method source I see you are comparing **REQUEST_CODE** and I suppose you should compare **_requestCode_** variable instead because the **setRequestCode** method assign the value to **_requestCode_** variable.

 ```
public static IntentResult parseActivityResult(int requestCode, int resultCode, Intent intent) {
        if (requestCode == REQUEST_CODE) {
            return parseActivityResult(resultCode, intent);
        }
        return null;
    }
```

Could you please confirm the issue/behavior ?

**Comment by rkistner** [comment]
If you use `setRequestCode`, you'll need to check the requestCode yourself, and use the `parseActivityResult(resultCode, data)` version (which doesn't check the request code).
