### ISSUE TITLE
Error:(1) Attribute "rippleColor" has already been defined - while importing "android support library(compile 'com.android.support:design:22.2.0')".

### ISSUE THREAD

**Issue by yatintaluja** [journeyapps/zxing-android-embedded#65]
/Users/yatintaluja/Documents/github/SocialCops-Android/core/build/intermediates/exploded-aar/com.journeyapps/zxing-android-embedded/3.0.1/res/values/values.xml

Error:Execution failed for task ':core:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/yatintaluja/Library/Android/sdk/build-tools/22.0.1/aapt'' finished with non-zero exit value 1

**Comment by rkistner** [comment]
`aapt` reports the error in the wrong location - there is no `rippleColor` defined in this library.

See #55 for more details.
