### ISSUE TITLE
Robolecric support

### ISSUE THREAD

**Issue by commjoen** [journeyapps/zxing-android-embedded#67]
Hi, 
I am currently creating Robolectric based unit tests for a library that uses this library. I am using:

    compile 'com.journeyapps:zxing-android-embedded:3.0.1@aar'
    compile 'com.google.zxing:core:3.2.0'

However, the tests give me `Caused by: java.lang.NoClassDefFoundError: com/google/zxing/client/android/R$layout`. What can this be?

**Comment by rkistner** [comment]
Do you have a sample project that produces this error? Then I can look into it.

**Comment by commjoen** [comment]
Maybe a bit of a dumb question, but how should I present a sample project? Do i need to create my own public repository to do so?

**Comment by commjoen** [comment]
The issue can be closed, it was a Robolectric issue. If it re-occurs and it is not up to the framework, I will post an issue with sample project here.
