### ISSUE TITLE
QR codes not getting recognized if it has a background

### ISSUE THREAD

**Issue by NathanFallet** [journeyapps/zxing-android-embedded#682]
#### Description of the problem:

My app is generating a QR code on a background. The code is well recognized by my iOS app, but on Android, only the code without background works.

_Exemple :_
This one is not getting recognized:
![IMG_4728](https://user-images.githubusercontent.com/30439790/147411530-52c6331d-0690-4e39-becc-55a4ae4261f1.PNG)
While the raw code, is:
![IMG_4722](https://user-images.githubusercontent.com/30439790/147411524-686d649d-15e0-4773-83e0-a284810854fd.JPG)

**Which library version are you using?**
4.3.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Tested on my Wiko running Android 5.0, on my girlfriend Xiaomi (don't know the Android version but it's something recent), and on the emulator (Pixel 3a) running Android API 31.

**Does the same happen on other devices or an emulator?**
It happens on all the device I tested and mentioned above.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes, using the two images I uploaded above. One is getting recognized while the other not.

**In the case of an error do you have a stack trace or adb logs?**
There is no error. Nothing happens while pointing the code on a background.

**Comment by rkistner** [comment]
The standard scan mode is for black / dark foreground on a white / light backround.

To handle a case like this, use the "Inverted" scan mode.

**Comment by NathanFallet** [comment]
@rkistner Is there a mode in which both can be recognized? Because both can be used by users. And I have my iOS app handling both of them too, so I would like my Android app to do the same.

**Comment by rkistner** [comment]
Yes, you can use the `MIXED_SCAN` mode:

https://github.com/journeyapps/zxing-android-embedded/blob/2324a5403e8b89b66631977b357d1b998f1caf7e/sample/src/main/java/example/zxing/MainActivity.java#L60

**Comment by NathanFallet** [comment]
Thanks!

**Comment by Nurlibay** [comment]
Awesome
