### ISSUE TITLE
Get resultCode, is it possible?

### ISSUE THREAD

**Issue by jfoucry** [journeyapps/zxing-android-embedded#694]
#### Using a customScannerView:

**Which library version are you using?** 

4.3.0.

**Which phone/tablet are you using, and which Android version does it run?**
OnePlus 5T/FP3

**Does the same happen on other devices or an emulator?**
Does not use emulator my computer is too weak for that.

I have a customScanncerActivity, with a custom layout. 
- Three buttons:
  -  torch on/off → work well;
  - cancel → work weel;
  - use keyboard → use a returnCode in order to launch an other activity.
 
How can I get this returnCode?

In `custom_barcode_scanner.xml`
```
<ImageButton
        android:id="@+id/keyboard_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|end"
        android:layout_margin="@dimen/fab_margin"
        android:backgroundTint="@android:color/transparent"
        android:contentDescription="@string/button_keyboard"
        android:onClick="onKeyboard"
        android:src="@drawable/ic_keyboard_black_24dp" />
```

In `customScannerActivity.java`

```
    public void onKeyboard(View view) {
        setResult(3);
        finish();
    }
```
So in `ActivityResultLauncher<ScanOptions> barcodeLauncher = registerForActivityResult(new ScanContract(),..`
`result.getContent()` is `null`, is there a way to get the resultCode?

**Comment by rkistner** [comment]
You'll need to implement a custom `ActivityResultContract`. See the default implementation here:

https://github.com/journeyapps/zxing-android-embedded/blob/2324a5403e8b89b66631977b357d1b998f1caf7e/zxing-android-embedded/src/com/journeyapps/barcodescanner/ScanContract.java#L18-L20

See the Android documentation for details:
https://developer.android.com/training/basics/intents/result#custom

**Comment by jfoucry** [comment]
Ok thanks, That exactly what I fear about. I close the issue thanks for your time and your advice.
