### ISSUE TITLE
IntentIntegrator is defined multiple times

### ISSUE THREAD

**Issue by PekinioElFamoso** [journeyapps/zxing-android-embedded#699]
#### Description of the problem:

Hey can i have some help , i got this error : Type com.google.zxing.integration.android.IntentIntegrator is defined multiple times:

I have tried many things without success ...

    minSdkVersion 24
        targetSdkVersion 30

**Comment by rkistner** [comment]
That indicates you have multiple conflicting copies of the library, or a combination of this library and `com.google.zxing:android-integration`.

1. Which version of this library are you using?
2. What other dependencies do you have?

**Comment by PekinioElFamoso** [comment]
> 

i use this 
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.google.android.play:core:1.10.3'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation files('libs/gson-2.8.5.jar')
    implementation 'com.android.volley:volley:1.2.1'
    implementation project(path: ':otpview')
}

**Comment by rkistner** [comment]
Nothing standing out in those dependencies, unless there is a conflicting .jar file in the libs folder.

Does the error log give any indication on where the duplicates are defined?

**Comment by PekinioElFamoso** [comment]
I just have this but I don't understand... 

Except a json lib nothing

`Type com.google.zxing.integration.android.IntentIntegrator is defined multiple times: C:\Users\tcollin\AndroidStudioProjects\wadaco\app\build\intermediates\project_dex_archive\release\out\com\google\zxing\integration\android\IntentIntegrator.dex, C:\Users\tcollin\AndroidStudioProjects\wadaco\app\build\intermediates\external_libs_dex\release\mergeExtDexRelease\classes.dex`

**Comment by rkistner** [comment]
I don't think this one should be there:

```
build\intermediates\project_dex_archive\release\out\com\google\zxing\integration\android\IntentIntegrator.dex
```

Do you have an IntentIntegrator.java source file somewhere? (You should not have that in your project)

If it still fails, also try doing a clean build.

**Comment by PekinioElFamoso** [comment]
> 

I deleted the java file but still the same... I don't understand

**Comment by PekinioElFamoso** [comment]
> I don't think this one should be there:
> 
> ```
> build\intermediates\project_dex_archive\release\out\com\google\zxing\integration\android\IntentIntegrator.dex
> ```
> 
> Do you have an IntentIntegrator.java source file somewhere? (You should not have that in your project)
> 
> If it still fails, also try doing a clean build.

Ok is good working THX
