### ISSUE TITLE
Espresso Support

### ISSUE THREAD

**Issue by commjoen** [journeyapps/zxing-android-embedded#70]
Hi,
I am now using Zxing Embedded 3.0.2 and am trying to figure out on how to mock a result of a scan; is there a way in which I can prepare the application under test with some mock BarcodeResult?

I am using the CompoundBarcodeScanner which is placed within a fragment and I want to test whether the callback execution (BarcodeCallback) leads to the proper results.
with kind regards,
Jeroen

**Comment by rkistner** [comment]
I haven't worked with Espresso before, so I have no idea how to approach this.

Let me know if there is something I should change in the library to make this easier.

**Comment by commjoen** [comment]
Which testingframework do you use to automate tests then? (So I can check that path too ;-)).

**Comment by rkistner** [comment]
At the moment there are no automated tests for this unfortunately.

**Comment by commjoen** [comment]
I will then experiment myself. (Note: it took some additional effort, but it was relatively easy to use Robolectric 3.0 for unit tests) I will let you know if I need help or modifications.

**Comment by commjoen** [comment]
Ok, it would be nice to find a way to mock out the actual BarcodeResult by providing a mock-camera source. Can you help me with that?

**Comment by rkistner** [comment]
Do you want to mock the camera and test the decoding, or just provide a mock BarcodeResult to be passed back?

Just providing a mock BarcodeResult should be fairly easy.

**Comment by commjoen** [comment]
I want to mock the camera & decoding: it should always return a valid result

**Comment by commjoen** [comment]
I do provide a mock BarcodeResult right now, which is good enough for the tests, but it would be nice if we can take other approaches as well.

**Comment by ajans** [comment]
Maybe this older camera-source library is adaptable?
http://www.tomgibara.com/android/camera-source

**Comment by rkistner** [comment]
This is not something I can spend time on now unfortunately. I'll be happy to accept pull requests for this (as long as it doesn't make the code significantly more complicated).

**Comment by kelvinwatson** [comment]
@commjoen would you be able to share your code for your mock barcode result testing?

**Comment by commjoen** [comment]
The code looks something like:

`public static void callBarcodeCallback(final Fragment scanFragment, Application application) {

        QrIdLoader qrIdLoader = new QrIdLoader(scanFragment, new QrIDLoaderCallback() {
            @Override
            public void onQrIdRetrievalSuccess(String qrID) {
                SourceData sourceData = new SourceData(new byte[0], 0, 0, 0, 0);
                Result result = new Result("data that you want from the QR", new byte[0], new ResultPoint[0], BarcodeFormat.QR_CODE);
                BarcodeResult barcodeResult = new BarcodeResult(result, sourceData);
                scanFragment.getBarcodeCallback().barcodeResult(barcodeResult);
            }

            @Override
            public void onQrIdRetrievalFailed(Exception e) {
                Log.e(TAG, "error while retrieving the qr", e);
            }
        }, "someURL", application);
        qrIdLoader.execute();
    }`

We call this method in our tests to fake the loading of data based on the BarcodeResult. Most importantly is that you have your own SourceData, which you put, together with the Result - containing the barcodedata - into a BarcodeResult, which you then offer to the barcodeCallback.

**Comment by swapnilghadge2390** [comment]
@rkistner  I am using zxing-android-embedded library for scanning barcode but if result contains some other language (language other than english) i am getting result like %20%C3%84%C3%96%C3%9C%C3%9F. Can you please help me. Thanks in advance.

**Comment by rkistner** [comment]
Espresso support is currently outside the scope of this project, but pull requests would still be accepted.

**Comment by hlandim** [comment]
Im my case I managed to mock it by using [Espresso-Intents](https://developer.android.com/training/testing/espresso/intents).

```

@get:Rule
val intentsTestRule: IntentsRule = IntentsRule()

val resultData = Intent().apply {
    putExtra(Intents.Scan.RESULT, "BARCODE RESULT STRING")
}
val result = Instrumentation.ActivityResult(Activity.RESULT_OK, resultData)
// Intents.Scan.ACTION in in import com.google.zxing.client.android.Intents
intending(hasAction(Intents.Scan.ACTION)).respondWith(result)
```
