### ISSUE TITLE
Pause scanning in continuous capture mode

### ISSUE THREAD

**Issue by bs2015** [journeyapps/zxing-android-embedded#71]
Hello,
I have been trying to figure out how to solve this -
In continuous capture mode ( e.g. ContinuousCaptureActivity.java in the sample project) , the camera is scanning the code repeatedly as long as the camera is placed on a QR code. I want to display a confirmation dialog with "Confirm", "Cancel" button, and a input box. When the dialogbox is active it should stop scanning but not the camera preview. When user press the "Confirm" or "Cancel" button it should start scanning again. 
I tried "barcodeView.pause();" but it stops the scanning as well as camera preview. Can we pause scanning (but not the camera preview) when it detects a barcode?. (Which is well done in Zxing official Barcode Scanner app)

**Comment by rkistner** [comment]
The easiest would be to just do a single scan each time. When the user
presses confirm or cancel, you just start another scan (you can do this
without closing the activity or stopping the preview).

**Comment by bs2015** [comment]
Thank you very much for quick reply. I did as you mentioned above and is working perfectly now.

**Comment by vidyajejurkar** [comment]
@bs2015 Hi How did u print all scanned barcode? I need help.
I need result in following format.any suggestion?
![image](https://cloud.githubusercontent.com/assets/6360660/26188244/cb6b4080-3bbb-11e7-89ed-eb13c4ea5920.png)
