### ISSUE TITLE
How can I only reshape the ViewfinderView?

### ISSUE THREAD

**Issue by commjoen** [journeyapps/zxing-android-embedded#73]
Hi,
I would like to reuse the compoundbarcodeview, but only rewrite the ViewfinderView. How can I still do this?

Basically what I want to achieve is to slightly change the edges of the ViewfinderView only.

**Comment by rkistner** [comment]
This should work:

1. Create a new class, subclassing ViewfinderView, with your changed logic.

2. Create a new layout file. using [this](https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/res/layout/custom_barcode_scanner.xml) as an example, but with your new class.

3. Use this layout file for the CompoundBarcodeView. See [CustomScannerActivity](https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/CustomScannerActivity.java) for an example of doing this.

**Comment by commjoen** [comment]
If I try step 1, it says: cannot inherit from final 'com.jouneyapps.barcodescanner.ViewfinderView'

**Comment by commjoen** [comment]
ViewfinderView should not be final and then I can extend from it.

**Comment by commjoen** [comment]
https://github.com/journeyapps/zxing-android-embedded/pull/75

**Comment by commjoen** [comment]
Thanks! Can you please update the version and publish so I can use the changes :)?

**Comment by commjoen** [comment]
You can close this issue as soon as the new version contains the PR :)

**Comment by rkistner** [comment]
Released in v3.0.3.
