### ISSUE TITLE
barcodeScannerView.setTorchOn(); doesn't work if it is called from onCreate

### ISSUE THREAD

**Issue by bs2015** [journeyapps/zxing-android-embedded#74]
Hello,

I have kept Torch on/off option in settings which get saved in SharedPreferences. When the camera activity starts it reads SharedPreferences and checks if torch is enabled, if so it will call barcodeScannerView.setTorchOn();. I have written the codes in onCreate() function but nothing happens! In the same activity, if I call barcodeScannerView.setTorchOn(); from a button press event it works fine.

My sample code is as follows-
if (PreferencesHelper.isTorchEnabled(this)) {
	barcodeScannerView.setTorchOn();
}

**Comment by rkistner** [comment]
Currently the setTorchOn() method has no effect if the preview hasn't started yet.

Something like this should work:

```java
barcodeScannerView.getBarcodeView().addStateListener(new StateListener() {
        public void previewSized() {
        }

        @Override
        public void previewStarted() {
             barcodeScannerView.setTorchOn();
        }

        @Override
        public void previewStopped() {
        }

        @Override
        public void cameraError(Exception error) {
        }
});
```

**Comment by bs2015** [comment]
It worked perfactly :-). Thanks for the great work. 
I also copied displayFrameworkBugMessageAndExit() function from CaptureManager called inside cameraError. Is that a right approach?

**Comment by rkistner** [comment]
Yes, that's the correct approach to handle errors.

**Comment by bs2015** [comment]
Thanks.
