### ISSUE TITLE
At the 4.3.0 version, the library is not working for some types of QR formats.

### ISSUE THREAD

**Issue by Nurlibay** [journeyapps/zxing-android-embedded#741]
#### Description of the problem:

** I'm using 4.3.0 version

** Device - Xiomi Redmi 10C, Android 13

** This problem happening my device (above)

** Issue happening qr format [here](https://drive.google.com/file/d/1Pb3Vw9LOxHcs4PZdcz4df9iSdXVHy1kc/view?usp=sharing)

** Project link [here](https://github.com/Nurlibay/barcode-scanner)

**Comment by rkistner** [comment]
QR code specifies black dots on a white background, this is the other way around.

You can scan this using inverted or [MIXED_SCAN](https://github.com/journeyapps/zxing-android-embedded/issues/682#issuecomment-1001537586) mode.

**Comment by Nurlibay** [comment]
How to set 
```
val options = ScanOptions()
                    .addExtra(Intents.Scan.SCAN_TYPE, Intents.Scan.MIXED_SCAN)
                    .setOrientationLocked(false)
                    .setCaptureActivity(CustomScannerActivity::class.java)
                    .setCameraId(0)
                    .setBeepEnabled(false)
                    .setBarcodeImageEnabled(true)
                    .setDesiredBarcodeFormats(ScanOptions.QR_CODE)
```
                    
to dialog?
                    
I open camera in DialogFragment.
