### ISSUE TITLE
can it generate QR code？

### ISSUE THREAD

**Issue by pengkv** [journeyapps/zxing-android-embedded#76]

**Comment by rkistner** [comment]
Yes, there is a helper class that can create a Bitmap for you: [BarcodeEncoder](https://github.com/journeyapps/zxing-android-embedded/blob/master/zxing-android-embedded/src/com/journeyapps/barcodescanner/BarcodeEncoder.java#L67)

It's just a very thin wrapper around MultiFormatWriter from zxing:core, which does the actual encoding.
