### ISSUE TITLE
Scanning without a preview

### ISSUE THREAD

**Issue by AugustoEst** [journeyapps/zxing-android-embedded#77]
Is it possible to do the scanning in the background of an app's view? Without showing the scanning preview.

**Comment by rkistner** [comment]
Currently you need the scanning preview. It may be possible to use some hack to hide it, for example by placing an overlay on top of it or making the preview very small, but it may give issues on some devices (some devices may have a minimum preview size for example).

The Android Camera2 API, available from Android 5.0+, would support capturing the camera data without any preview as far as I know. This library doesn't support it yet though.

**Comment by AugustoEst** [comment]
Thanks for the answer. Unfortunately I'm using the Google Glass, so stuck at Android 4.4.4.

**Comment by rkistner** [comment]
It may be possible on Android 4.x, using SurfaceTexture. See this post: http://stackoverflow.com/a/14227517/214837. It's not something I plan to support in the library, but it should be possible to fork this library and do something like that.

**Comment by mschewe** [comment]
Do you know if there is a fork implementing this?
