### ISSUE TITLE
Enable torch for scanning , IntentIntegrator 

### ISSUE THREAD

**Issue by abarboutis** [journeyapps/zxing-android-embedded#79]
This is my first android project  , I didnt find a way to open the torch while scanning , my code is like this

        IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
        integrator.setPrompt("Scan the barcode");
        integrator.setCameraId(0);  // Use a specific camera of the device
       integrator.setBeepEnabled(true);
        integrator.setCaptureActivity(CaptureActivityAnyOrientation.class);
        integrator.setOrientationLocked(false);
        integrator.initiateScan();

**Comment by rkistner** [comment]
There isn't currently a method to do that via the intent. The user can however control the flashlight with the volume up/down keys. If you need more control than that, you can create a custom Activity.

**Comment by abarboutis** [comment]
Thank you very much , i didnt know about the volume keys , it solves my problem

**Comment by meilleureVie** [comment]
please add torch control also in barcodeview

**Comment by mehdipol** [comment]
You can use the ActionBar to add a button
