### ISSUE TITLE
Doesn't work inside Fragments

### ISSUE THREAD

**Issue by seguri** [journeyapps/zxing-android-embedded#8]
The problem is not avoidable with `IntentIntegrator.initiatescan(getActivity())` because it wouldn't trigger Fragment `onActivityResult`.

Current workaround:

```
Intent i = IntentIntegrator.createScanIntent(getActivity(), null, null);
i.setAction(Intents.Scan.ACTION);
i.putExtra("RESULT_DISPLAY_DURATION_MS", 0L);
startActivityForResult(i, IntentIntegrator.REQUEST_CODE);
```

**Comment by aungtuntun** [comment]
Thanks for your suggestion. My problem is scanning QRCode from DialogFragment. So I did it like this:

 IntentIntegrator.forSupportFragment(this).setPrompt("Scan a barcode or QRCode").initiateScan();

This is worked for me.
