### ISSUE TITLE
Changing the position of the camerapreviewframingRect

### ISSUE THREAD

**Issue by commjoen** [journeyapps/zxing-android-embedded#80]
Hi,
what would be a good way to move the camerapreviewframingRect? I teems I have to extend CameraPreview before I can manipulate it. Is there no other way?

**Comment by rkistner** [comment]
Fixed with #87.

**Comment by rkistner** [comment]
To clarify, #87 makes it easier to specify the size. If you want a specific position (not centered), you still need to override CameraPreview/BarcodeView to provide your own logic.
