### ISSUE TITLE
CompoundBarcodeView throw NoClassDefFoundError and not display ScannerView on Android Studio

### ISSUE THREAD

**Issue by kienntk** [journeyapps/zxing-android-embedded#81]
First of all, thanks for your great project!

I use your project to develop an BarcodeScanner application.
And I want to use it on Portrait screen and it displayed on a part of screen.

![capture](https://cloud.githubusercontent.com/assets/13272329/9955027/e37f33c6-5e17-11e5-84cb-09724d053f4b.PNG)

Here's my XML code:
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:zxing_view="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="#00CC00"
    android:orientation="vertical"
    android:weightSum="100">

    <com.journeyapps.barcodescanner.CompoundBarcodeView
        android:id="@+id/barcode_scanner"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="40"
        >

    </com.journeyapps.barcodescanner.CompoundBarcodeView>

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginTop="5dp"
        android:layout_weight="40">
                //Other component
    </RelativeLayout>
</LinearLayout>
```
My build.gradle include:
```
repositories {
    mavenCentral()
    maven {
        url "https://raw.github.com/embarkmobile/zxing-android-minimal/mvn-repo/maven-repository/"
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile files('src/main/jniLibs/httpclient-4.0.jar')

    compile 'com.journeyapps:zxing-android-embedded:3.0.3@aar'
    compile 'com.google.zxing:core:3.2.0'
}
```
And I used CompoundBarcodeView in fragment:
```
public class CMCSMOFragment extends Fragment implements View.OnClickListener {
private CompoundBarcodeView barcodeView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        if (container == null) {
            return null;
        }
        //My Code

        barcodeView = (CompoundBarcodeView) v.findViewById(R.id.barcode_scanner);
        barcodeView.decodeContinuous(callback);

        return v;
    }
        private BarcodeCallback callback = new BarcodeCallback() {
        @Override
        public void barcodeResult(BarcodeResult result) {
            if (result.getText() != null) {
                barcodeView.setStatusText(result.getText());
            }

            edtCommand.setText(result.getText());
        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
        }
    };
}
```
But when I build this application, the CompoundView only show a blackscreen with the text from ZXing. Could you please help me to explain or solve this problem. Thank you very much!

**Comment by rkistner** [comment]
The screenshot shows an error from the layout editor, which is hard to debug. Do you get any errors when compiling, or from the Android logs when running?

**Comment by kienntk** [comment]
No, Sir. 
When compiling, it works fine. and the CompoundView only shows a Black Screen, not open camera.
My manifest.xml file is added necessary permissions and features. 
If you need, I could send you my project.

**Comment by kienntk** [comment]
Could you please check the CompoundView again? I build app successfully, but it's not display camera for scanning :(. Only a black screen.

**Comment by rkistner** [comment]
I haven't had a chance to look at this yet.

Can you send me the app so I can have a look?

**Comment by kienntk** [comment]
https://github.com/kienntk/SNBarcodeScanRes/tree/master/SNScanWebService

Here is the link of my application.
Thank you very much for your time!

**Comment by kienntk** [comment]
@rkistner : I'm so sorry about inconvenient, Sir. 
Do you have the result?
My deadline come to an end soon :(

**Comment by rkistner** [comment]
You're missing calls to `barcodeView.resume()` and `barcodeView.pause()` from your `onResume()` and `onPause()` calls. See the sample: https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/ContinuousCaptureActivity.java

**Comment by kienntk** [comment]
Thank you very much, Sir. It's solved.
