### ISSUE TITLE
Dont have setBarcodeImageEnabled

### ISSUE THREAD

**Issue by youyi1314** [journeyapps/zxing-android-embedded#82]
Hi, 
Why i cant set setBarcodeImageEnabled in this?
![app](https://cloud.githubusercontent.com/assets/8391468/10126853/8cda5972-65cb-11e5-86ea-97ae3e0721ee.png)
![barcodeimage](https://cloud.githubusercontent.com/assets/8391468/10126854/8d06bfd0-65cb-11e5-949d-41b8b95ba447.png)

Thanks

**Comment by rkistner** [comment]
That functionality was added in version 3.0.3, just update your library version.

**Comment by youyi1314** [comment]
Oh~Thanks, it work now after change to 3.0.3.

**Comment by rkistner** [comment]
Sorry, missed the edit

**Comment by rkistner** [comment]
The path can be retrieved with `IntentResult#getBarcodeImagePath()`. You can then load the image using the standard Android tools.

You cannot override the beep via the intents yet. However, you can instead create your own Activity using CompoundBarcodeView, and add your own beep.

Please open a new issue for the crash. Also include Android version and device details - it may be specific to some devices.
