### ISSUE TITLE
Crash when Rotate Phone [Vivo XShot] with AnyOrientationCaptureActivity

### ISSUE THREAD

**Issue by youyi1314** [journeyapps/zxing-android-embedded#83]
Reopen New Issue from : https://github.com/journeyapps/zxing-android-embedded/issues/82 

ERROR LOG Below:
![image](https://cloud.githubusercontent.com/assets/8391468/10247495/1d186e10-694c-11e5-85d7-76011df5b90d.png)

Phone :
Vivo XShot
Android 4.4.2

**Comment by rkistner** [comment]
Should be fixed by #133.

**Comment by rkistner** [comment]
Fix released in [v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0).

Please re-open if you still have this issue.
