### ISSUE TITLE
Is it possible to use CompoundBarcodeView for 2 fragments in an application?

### ISSUE THREAD

**Issue by kienntk** [journeyapps/zxing-android-embedded#85]
Hi Sir ,

I want to develop an application with 2 fragments and display CompoundBarcodeView for Continuous scanning in both of them.
But it only displays for the first fragment, in 2nd fragment is a black screen.

Is it possible to use CompoundBarcodeView for 2 fragments in an application? If it's not, could you please add function `stopScan` into CompoundBarcodeView to stop camera when change between fragments? It's helpful in my opinion!

Thanks for your consideration!

**Comment by rkistner** [comment]
Do you have both fragments in the same activity, or different activities?

The `pause()` method does release the camera, but not immediately, as it happens in a background thread.

**Comment by kienntk** [comment]
I use both fragments with ViewPager in the same activity, Sir.

**Comment by rkistner** [comment]
That's something I haven't tried yet. There's no fundamental reason it shouldn't work, but I'm not sure what will need to change in the library to fix it.

**Comment by kienntk** [comment]
Would `pause()` method release camera? I will try again.

**Comment by rkistner** [comment]
Yes, it will release the camera, but in a background thread.

**Comment by kienntk** [comment]
Yes, it works. Thank you very much for your time! So sorry about my little knowledge.

**Comment by kienntk** [comment]
@rkistner : Sorry for this, but do you know the reason of [this problem] (http://stackoverflow.com/questions/32965547/zxing-is-overflow-between-2-tabs-in-viewpager)? I don't want to open an issue, it's not good :D.

**Comment by rkistner** [comment]
That is related this: https://github.com/journeyapps/zxing-android-embedded/issues/68#issuecomment-131570770.

WIth a ViewPager it may be difficult to solve the issue. I'm guessing the only approach would be to use TextureView instead of SurfaceView, which would require a refactoring in the library.

**Comment by kienntk** [comment]
Wait for your next release ^^
