### ISSUE TITLE
Is it possible to disable auto-focus?

### ISSUE THREAD

**Issue by acrolink** [journeyapps/zxing-android-embedded#86]
I need to turn this feature off for my app. This is because I will have the scanner on for long periods and I don't want the continious auto-focus activity damage the motor of my camera. Thanks.

**Comment by rkistner** [comment]
Yes, you can call `barcodeView.getCameraSettings().setAutoFocusEnabled(false)`, before starting the preview.

This has to be done with a custom activity currently, no option for it via the IntentIntegrator.

**Comment by acrolink** [comment]
First, thanks for this super fast barcode scanner solution :-)

I have tried to implement the above mentioned code in a custom activity but I get an error:

````
The method getCameraSettings() is undefined for the type CompoundBarcodeView
````

**Comment by rkistner** [comment]
It's defined on the `BarcodeView` class, try `barcodeView.getBarcodeView().getCameraSettings().setAutoFocusEnabled(false)`.

**Comment by acrolink** [comment]
Thank you.

**Comment by acrolink** [comment]
@rkistner 

Your suggestion works perfectly but I have to use this to start the scannner activity, instead of IntentIntegrator:

```
Intent intent = new Intent(this, ScannerActivity.class);
startActivity(intent);
```

**Comment by myusufbo** [comment]
how can i set auto focus? 
Thanks in Advance :)
