### ISSUE TITLE
Changing size of framing rectangle in BarcodeView

### ISSUE THREAD

**Issue by SunhoY** [journeyapps/zxing-android-embedded#87]
Hi,

We -my team- have tried to change the size of framing rectangle in the CameraPreview, and we found out it has constant logic to set the margins. 
So we think it could be nice if we can set our own size for framing rectangle.

We already have the code and we can raise pull request if you are interested in this feature.

**Comment by XDex** [comment]
+1

**Comment by erikny** [comment]
+1

**Comment by kienntk** [comment]
+1

**Comment by porkchai** [comment]
+1

**Comment by simonxcheng** [comment]
+1

**Comment by rkistner** [comment]
Thanks @SunhoY! I moved the logic to CameraPreview, and merged into master. Will be part of the next release.
