### ISSUE TITLE
failed to reslove: com.journeyapps:zxing-android-embedded:3.0.3

### ISSUE THREAD

**Issue by k-lam** [journeyapps/zxing-android-embedded#88]
I use android studio
I add the follow code in build.gradle of module as you suggest

compile 'com.journeyapps:zxing-android-embedded:3.0.3@aar'
compile 'com.google.zxing:core:3.2.0'

but gradle throw this error:
failed to reslove: com.journeyapps:zxing-android-embedded:3.0.3

**Comment by rkistner** [comment]
Make sure you include this:

```gradle
repositories {
    jcenter()
}
```

**Comment by k-lam** [comment]
yes,I have included this

**Comment by rkistner** [comment]
In that case I'll need more details / log output. There's no reason I know of that that shouldn't work.

**Comment by k-lam** [comment]
in your sample module, i comment compile(project(':zxing-android-embedded')) { transitive = true }
and add 
compile 'com.journeyapps:zxing-android-embedded:3.0.3@aar'
compile 'com.google.zxing:core:3.2.0'

it still not work

**Comment by rkistner** [comment]
That works for me without any issue. It could be some network issue on your side. I can maybe help you if you give me detailed logs (e.g. build with `--trace` or `--debug`).

**Comment by k-lam** [comment]
I have checked the net,it's ok and aar has download in my module floder when I used VPN.But it still goes wrong when I when './gradlew assemble',and I has checked the log but don't find any reason.Today it is ok,I just restart the mac,and it's ok now.....
Thank you for your help.

**Comment by kienntk** [comment]
I had got this issue, too. So I download lib and add it into `libs` folder ^^.

**Comment by Meetpatel-09** [comment]
if your Android SDK version is above 28, Android SDK > 28. Then use this dependency.

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.journeyapps:zxing-android-embedded:4.2.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
}

android {
    buildToolsVersion '28.0.3' // Older versions may give compile errors
}
