### ISSUE TITLE
Failed to open camera in Marshmallow

### ISSUE THREAD

**Issue by freakazoid1988** [journeyapps/zxing-android-embedded#89]
I have a problem when I run 

```Java
IntentIntegrator.forSupportFragment(this).setOrientationLocked(true).setBeepEnabled(true).initiateScan();
```

I tried to run the same application in Lollipop, where it works flawlessly, and in Marshmallow, where I get an alert: "Sorry, the Android camera encountered a problem, etc. etc.".

I'm running on the 3.0.3 version, although it happens on the 3.0.1 and 3.0.2 as well. It happens on both my Nexus 5 and the emulator.

That's the stacktrace:

```
D/CameraPreview: resume()
D/CameraInstance: Opening camera
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb3fd4140
W/CameraBase: An error occurred while connecting to camera: 0
E/CameraInstance: Failed to open camera
E/CameraInstance: java.lang.RuntimeException: Fail to connect to camera service
E/CameraInstance:     at android.hardware.Camera.<init>(Camera.java:495)
E/CameraInstance:     at android.hardware.Camera.open(Camera.java:341)
E/CameraInstance:     at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:121)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:158)
E/CameraInstance:     at android.os.Handler.handleCallback(Handler.java:739)
E/CameraInstance:     at android.os.Handler.dispatchMessage(Handler.java:95)
E/CameraInstance:     at android.os.Looper.loop(Looper.java:148)
E/CameraInstance:     at android.os.HandlerThread.run(HandlerThread.java:61)
W/EGL_emulation: eglSurfaceAttrib not implemented
W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xabebff00, error=EGL_SUCCESS
D/CameraInstance: Configuring camera
W/CameraManager: Failed to set rotation.
W/CameraManager: Camera rejected even safe-mode parameters! No configuration
E/CameraInstance: Failed to configure camera
E/CameraInstance: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraManager.setParameters(CameraManager.java:359)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:139)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:171)
E/CameraInstance:     at android.os.Handler.handleCallback(Handler.java:739)
E/CameraInstance:     at android.os.Handler.dispatchMessage(Handler.java:95)
E/CameraInstance:     at android.os.Looper.loop(Looper.java:148)
E/CameraInstance:     at android.os.HandlerThread.run(HandlerThread.java:61)
D/CameraPreview: pause()
D/CameraInstance: Closing camera
```

**Comment by fahimk** [comment]
If you are compiling against sdk 23, you need to ask for camera permissions with the new permissions api before the scanner is launched

**Comment by freakazoid1988** [comment]
That did in fact work. Sorry for wasting your time, this is the first time I compile against SDK 23. Cheers.

**Comment by rkistner** [comment]
Thanks @fahimk. I'll add a note on that soon. I haven't looked at version 23 of the SDK myself yet.

**Comment by tuxtux59** [comment]
I'm facing kind of same problem, i'm using an AR library wich use oubviously use Camera and I develop my app from 16 and above but on marshmallow an exception occured "Failed to connect to Camera Service" So I read your comments  so my Manisfest has this three lines : 

<uses-permission-sdk-23 android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />

and in my graddle file : 

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "XXXX"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

Am I wrong  somewhere?

**Comment by commjoen** [comment]
It works at my machine ^^. Basically you need to ask for a camera permission at runtime for using the camera.

**Comment by tuxtux59** [comment]
Yes thanks I found the same answer and ask at the begining to allow access to camera if user disabled it before launch.

**Comment by dschuermann** [comment]
In case it helps, this is how we are doing it currently: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/QrCodeCaptureActivity.java

**Comment by rkistner** [comment]
Thanks @dschuermann. I implemented something like that in 3.1.0 now.

**Comment by wseemann** [comment]
These changes don't appear to be fool proof. When using the latest version if you

1.) Grant permission to the camera and open a `CaptureActivity`
2.) Minimize the app, turn the camera permission off
3.) Return to the app

This will produce a crash. There should be a check when resuming the camera to ensure the permission has been granted.

**Comment by Rajatsonii** [comment]
@wseemann  have you find solution? I face same issue
