### ISSUE TITLE
Use it in a fragment without activity ref

### ISSUE THREAD

**Issue by carmas123** [journeyapps/zxing-android-embedded#91]
Can I use it in a fragment and get the result into it without use any activity refer?

**Comment by rkistner** [comment]
Yes, you can do it like this (from the readme):

```
IntentIntegrator.forFragment(this).initiateScan();
```

Note that if the Activity overrides `onActivityResult`, it *must* call `super.onActivityResult`, otherwise the result will never get passed on to the fragment.

**Comment by carmas123** [comment]
Oh yer but I need the result listener on the fragment and not in activity.
How can I handle the scan result directly on the fragment??

Il domenica 18 ottobre 2015, Ralf Kistner <notifications@github.com> ha
scritto:

**Comment by rkistner** [comment]
Just override `onActivityResult` in your Fragment, same as in an Activity.

See this sample:
https://github.com/journeyapps/zxing-android-embedded/blob/master/sample/src/main/java/example/zxing/MainActivity.java#L121

**Comment by carmas123** [comment]
Thank you so much I've only a problem, when onActivityResult get the activity result how can I close (terminate) the scannign process?

**Comment by rkistner** [comment]
If you're using it via intents it will close automatically. If you're using BarcodeView directly, that's up to you.

**Comment by carmas123** [comment]
This is my code

        scannerIntegrator = IntentIntegrator.forSupportFragment(CameraScanFragment.this);
        scannerIntegrator.setPrompt("Scan barcode");
        scannerIntegrator.setCameraId(Camera.CameraInfo.CAMERA_FACING_FRONT);
        scannerIntegrator.setBeepEnabled(false);
        scannerIntegrator.setOrientationLocked(true);
        scannerIntegrator.initiateScan();

and this is my activityresult

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {

        // Gestione risultato scansione barcode con fotocamera
        IntentResult result = IntentIntegrator.parseActivityResult(requestCode, resultCode, data);
        if (result != null) {
            // Chiudo il fragment
            scanDone(result.getContents());
        }
        else
                super.onActivityResult(requestCode, resultCode, data);
    }

**Comment by WinnyPig** [comment]
Hi, it doesn't work on my fragment any help?
