### ISSUE TITLE
Help importing in Android Studio

### ISSUE THREAD

**Issue by prgpascal** [journeyapps/zxing-android-embedded#93]
Hi, I'm trying to import this library in Android Studio but I get the message: 

Error:(6, 1) A problem occurred evaluating project ':zxing-android-embedded'.
> Could not find property 'zxingCore' on project ':zxing-android-embedded'.

All I've done is:
File -> New -> Import module... and imported the library.

What I'm missing? :/ 
Can you please explain to me how to implement this library correctly?

Thank you :D

**Comment by rkistner** [comment]
Follow this section: https://github.com/journeyapps/zxing-android-embedded#adding-aar-dependency-with-gradle

There is no need to clone the project or import the library - you just add the gradle dependency.

**Comment by prgpascal** [comment]
I'm so sorry... I thought I should add dependencies after importing the project in Android Studio.
Thanks a lot, now it seems to work correctly :)
