### ISSUE TITLE
Decouple capture activity orientation from camera orientation

### ISSUE THREAD

**Issue by jcabotage** [journeyapps/zxing-android-embedded#94]
I'm working on an app where the GUI for the capture activity has been designed to be in portrait mode (title bar at the top, information buttons oriented in portrait), but as you know on older devices portrait barcode scanning doesn't work. I would like to be able to set the capture activity orientation as portrait in the Android Manifest for ease with working with the GUI layout, but to be able to set the camera orientation to be landscape so I can still actually scan barcodes. I tried to see if I could do this myself by extending CameraPreview, but the class has private access to the SurfaceHolderCallback and the methods which set it, which is where I could try and set the camera's orientation.

**Comment by rkistner** [comment]
Changing the camera orientation will break the preview (the preview will be rotated 90 degrees to reality).

What you can do is set a custom DefaultDecoderFactory & Decoder on the BarcodeView, and rotate the image before decoding.
