### ISSUE TITLE
Is it possible to add custom button/togglebutton on cameralayout?

### ISSUE THREAD

**Issue by qiyuanchen** [journeyapps/zxing-android-embedded#96]
Hello,
 
First of all thank you for this wonderful library. 
I have added to my custom camera layout a toggle button. I am having trouble finding a way to implement the toggle button handler. Is this possible to do right now?

Thanks again.

**Comment by rkistner** [comment]
Yes - that's nothing specific to this library, you can do it the same as in any other Android project.
