### ISSUE TITLE
Is it possible to force the scanner to return only barcodes with a specific predefined length?

### ISSUE THREAD

**Issue by acrolink** [journeyapps/zxing-android-embedded#99]
Thanks.

**Comment by rkistner** [comment]
Yes, you can do that by specifying a custom DecoderFactory and Decoder on
the BarcodeView. You can override the default one, and filter out any
barcodes that do not have the specific length.  There's no docs for that
currently, so you'll have to go through the source code.

Alternatively you can just keep on scanning barcodes, as in the example for
continuous scanning, and stop once you find a barcode of the length you
want.
